<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_idcs-signin-basic-signin-for_2f0e89</name>
   <tag></tag>
   <elementGuidId>74b86dda-5f63-47e2-8b1f-3189c2de1263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idcs-signin-basic-signin-form-password|input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Password&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>220cec0a-bc5d-42ba-830f-c0e8ef0f2579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b7184a7b-82a5-4367-a7db-67fb6d1b5466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>cbf4b1b3-886a-4c3f-91c9-be99250aea2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oj-inputpassword-input oj-component-initnode</value>
      <webElementGuid>cd9e78e7-a97c-4cad-8718-6216e379dc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idcs-signin-basic-signin-form-password|input</value>
      <webElementGuid>b1e00954-f467-42b3-acbe-970a54f7544e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idcs-signin-basic-signin-form-password|input&quot;)</value>
      <webElementGuid>c3c18e27-abad-489b-a212-ab6e3f20b105</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idcs-signin-basic-signin-form-password|input']</value>
      <webElementGuid>d9c9b370-cadf-403d-8b6e-d4fddb2ac252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//oj-input-password[@id='idcs-signin-basic-signin-form-password']/input</value>
      <webElementGuid>5c014728-00c2-4863-a196-193c8d7a2af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//oj-input-password/input</value>
      <webElementGuid>0af2fbf6-fd07-4177-9394-68ed9e1a10fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password' and @id = 'idcs-signin-basic-signin-form-password|input']</value>
      <webElementGuid>d255238c-2c05-4878-9ca5-4cf74c9a2b30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
