<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Name_idcs-signin-basic-signin-fo_93898c (11)</name>
   <tag></tag>
   <elementGuidId>9f4c2f5f-facd-4608-affb-80e30e31b744</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idcs-signin-basic-signin-form-username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idcs-signin-basic-signin-form-username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;User name or email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eea4398f-c6fd-44a1-879c-eddc5e23b4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idcs-signin-basic-signin-form-username</value>
      <webElementGuid>b18b68ad-faeb-4926-8b72-18c15c72a2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idcs-placeholder-translation-id</name>
      <type>Main</type>
      <value>idcs-username-placeholder</value>
      <webElementGuid>50785231-8ba0-405b-a336-c1dd165c66b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>886a9f48-6af5-4e66-a448-491fdfd1a8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oj-sm-12 oj-form-control oj-inputtext-nocomp</value>
      <webElementGuid>45c45eb5-2a21-4722-8722-1c3ff99102bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:class</name>
      <type>Main</type>
      <value>[[{'idcs-signin-rw-floating-input': isOracleEmployeeRedwood || isCustomerRedwood}]]</value>
      <webElementGuid>dc77ef79-8c13-4451-835d-2846223a6b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>4dc9af30-45be-4212-a646-86510b8b3902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>63b1c904-1767-4bf1-aed4-e05433bfd90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0cc6228b-c7d1-415f-afc9-2247cdd032f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:placeholder</name>
      <type>Main</type>
      <value>[[bundle('signin.usernamePlaceHolder')]]</value>
      <webElementGuid>ceff3c01-bfde-4a2e-abcb-3f074f9bfd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:disabled</name>
      <type>Main</type>
      <value>[[$params.disableInput]]</value>
      <webElementGuid>0b127222-3a8e-40de-b5ff-913ddf2e917e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: username</value>
      <webElementGuid>34677cb2-e817-40f2-8518-40b2b76a814e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idcs-enable-right-click</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b72564e3-87c0-456e-a7b6-400842faee11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User name or email</value>
      <webElementGuid>ff2b7b79-171d-4bfe-9db1-2f549bd174a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idcs-signin-basic-signin-form-username&quot;)</value>
      <webElementGuid>644b533b-e603-4986-9d14-0da1174778da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idcs-signin-basic-signin-form-username']</value>
      <webElementGuid>52be4e70-1f5b-4bc9-922e-87c7cf9a48ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idcs-app-shell-signin-background']/div/div/div[2]/div/div/oj-module/div/oj-module/div/div/div/div/div/input</value>
      <webElementGuid>52ed89e4-d1df-4fc8-9317-b2a25c11b3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8caebdef-412c-44e8-b0eb-a2970c35ffc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'idcs-signin-basic-signin-form-username' and @type = 'text' and @placeholder = 'User name or email']</value>
      <webElementGuid>8f000dd3-5e78-410c-a85b-32312fbd1443</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
