<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Source Location ID_order_releasesourcexid</name>
   <tag></tag>
   <elementGuidId>271c8278-9031-4e1d-a673-1adccd412517</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='order_release/source/xid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Source Location ID&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9249ac70-1224-466a-9ed8-c461740be2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>56e01c2b-e7cb-41b8-b636-9f223fa207da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Source Location ID</value>
      <webElementGuid>24ed69d9-10c5-4960-837c-2f44880e112d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>99999</value>
      <webElementGuid>fbcbe76f-485e-42d5-8702-e875428f1049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_release/source/xid</value>
      <webElementGuid>76ed2405-0522-42a9-b0f2-885e70ebaacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_release/source/xid</value>
      <webElementGuid>615a6ad0-5678-4475-9a29-988bb91cd2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f75ee6a4-0e6d-45ad-b251-0454649a3753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>autoCompleteKeyEventListener(event, 'order_release/source/xid'); return pickListHandler('glog.server.query.servprov.LocationQuery', 'search', 'order_release/source/xid', 'Source\x20Location\x20ID', 'false', 'false', 'false', 'false', '', '', '', '', '', '', '', event, 'multiple', '', 'false', null, '', '');</value>
      <webElementGuid>2970dc3b-1c6c-481f-8211-6b805570b4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>autoCompleteKeyEventListener(event, 'order_release/source/xid');</value>
      <webElementGuid>7a4eebd5-6df5-4557-9942-0bff90242cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>autoCompleteHandler('glog.server.query.servprov.LocationQuery', 'search', 'order_release/source/xid', '', '', '', '', event, '', 'false', 3, null, '', '');</value>
      <webElementGuid>f63732c8-7668-4b44-a661-823584403416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>return onPickBlur(this,false);</value>
      <webElementGuid>f87a3296-8eac-48a7-8aff-d5032370c848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_release/source/xid&quot;)</value>
      <webElementGuid>b6637ed4-fc6f-4147-9bf7-302320c44ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Order Releases Finder/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>00c02fd6-3ef9-4eba-be22-29d7f913c237</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='order_release/source/xid']</value>
      <webElementGuid>5c45aecd-c2c1-4261-b7e5-654cebc8c557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyDataDiv']/table/tbody/tr/td/table/tbody/tr/td/div/table/tbody/tr/td/input</value>
      <webElementGuid>ac40f28a-6eff-4b77-a493-0fbfe75c725f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>61c47807-53fc-41f5-bc08-300af8064be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'order_release/source/xid' and @id = 'order_release/source/xid']</value>
      <webElementGuid>e118dc0a-2227-484c-991f-6b7d6e577149</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
