<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BXC.DEFAULT_TL</name>
   <tag></tag>
   <elementGuidId>2e2d76f6-8195-4e7d-b707-43da2024b487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rgSGSec.2.1.1.3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=rowheader[name=&quot;BXC.DEFAULT_TL&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d445fce3-e1f9-4f96-9aa6-53e174e867d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0aa5f444-5457-4a81-9333-334c156b181d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rgSGSec.2.1.1.3</value>
      <webElementGuid>823bcd2e-b46d-4e94-b524-da18cf1b3658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sgBodyCol</value>
      <webElementGuid>27d89ddf-dc9e-4500-a2eb-610738db05ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BXC.DEFAULT_TL</value>
      <webElementGuid>0bc9f98d-3631-4d42-8249-3b43e107be64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>BXC.DEFAULT_TL</value>
      <webElementGuid>df027880-c1d0-427b-b15c-9bc1a885401a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>rowheader</value>
      <webElementGuid>eaa7f758-a024-4eb4-8f02-737045b5e56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BXC.DEFAULT_TL</value>
      <webElementGuid>5ad5b974-b7fb-4fa5-95d0-62f4afcfd561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rgSGSec.2.1.1.3&quot;)</value>
      <webElementGuid>6895de70-a4cd-4c7a-9bbd-d6177214dee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Match Rule Profiles Result/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>999750a6-80bb-4c3e-92f5-b1dab7ae9398</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='rgSGSec.2.1.1.3']</value>
      <webElementGuid>2959ff35-eed2-4166-a874-72c17d36259f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rgSGSec.2.1.1']/div[3]</value>
      <webElementGuid>3c6f9ab2-49c9-4ee9-a380-5d9de3c495bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Domain Name'])[1]/following::div[7]</value>
      <webElementGuid>4a627cd0-34e5-4b4b-b606-60005499d044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Match Rule Profile Description'])[1]/following::div[9]</value>
      <webElementGuid>cc8d7109-a351-4dcb-9ad8-ccd9bc4580fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BXC.DEFAULT_RAIL'])[1]/preceding::div[3]</value>
      <webElementGuid>cd43f985-02d6-4df7-b47d-44a2198b3d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div[3]</value>
      <webElementGuid>b5f9d99e-783c-4071-be43-48e28e08d302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rgSGSec.2.1.1.3' and @title = 'BXC.DEFAULT_TL' and (text() = 'BXC.DEFAULT_TL' or . = 'BXC.DEFAULT_TL')]</value>
      <webElementGuid>b39de083-bdd6-4238-8407-051e6989331c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
