<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bulk Plan - Buy</name>
   <tag></tag>
   <elementGuidId>6f066bf8-1684-4078-89cf-45ed03f1b95e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='actionTree.1_6_1_3.k']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Bulk Plan - Buy&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6e3bffe5-bdba-4838-82d2-9def8059120e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionTree.1_6_1_3.k</value>
      <webElementGuid>cd2862ba-2cb8-4928-98d5-e76d9e2a4e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b8c5fe30-745f-4edc-a2e5-245cefaf6448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:executeAction('\x2FGC3\x2Fglog.webserver.util.QueryResponseServlet\x2F1750431455910\x3FbcKey\x3DMTc1MDQzMTQ1NTkxMTox\x26action_name\x3Dbulk_plan_buy\x26finder_set_gid\x3DORDER_RELEASE_WO_STOP')</value>
      <webElementGuid>ce8a0e35-afa9-40af-a500-50b5eb983e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bulk Plan - Buy</value>
      <webElementGuid>613c4c06-51d5-4e77-8e8c-d9f644f98351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionTree.1_6_1_3.k&quot;)</value>
      <webElementGuid>ec068b7f-35c6-482c-95ed-3ee0c193fd3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Bulk plan objects/Page_Order Releases Result/iframe_concat(id(, , actionFrame, , ))_actionFrame</value>
      <webElementGuid>849c98d2-8fa4-4ed7-ba32-e1f5c0c1dae8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='actionTree.1_6_1_3.k']</value>
      <webElementGuid>e92dc579-af5e-43fc-9c6c-7a46f9ee3b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='actionTree.1_6_1_3.l']/a</value>
      <webElementGuid>afb9c670-fda2-4d05-ab94-5f6a3a953b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bulk Plan - Buy')]</value>
      <webElementGuid>e5927a1f-b973-43dd-abfb-f456ae5a5a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build Buy Shipment On Primary Leg Show Consol Options'])[1]/following::a[1]</value>
      <webElementGuid>1c05e99b-0a42-4a8a-9340-9d322bb5cecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build Buy Shipment On Primary Leg'])[1]/following::a[2]</value>
      <webElementGuid>783ab7e1-7ba4-446c-bd24-5cd84868ba60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direct'])[1]/preceding::a[1]</value>
      <webElementGuid>0ff8a594-15d3-49e4-ad83-ddc3cea992e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual'])[1]/preceding::a[2]</value>
      <webElementGuid>50728986-ba53-4670-b4fb-e6848302bfc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bulk Plan - Buy']/parent::*</value>
      <webElementGuid>56910a3c-9ad5-46d4-ada0-589453e93988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:executeAction('\x2FGC3\x2Fglog.webserver.util.QueryResponseServlet\x2F1750431455910\x3FbcKey\x3DMTc1MDQzMTQ1NTkxMTox\x26action_name\x3Dbulk_plan_buy\x26finder_set_gid\x3DORDER_RELEASE_WO_STOP')&quot;)]</value>
      <webElementGuid>3b0c5b79-ec22-4098-bbf8-e7b1aa6c7051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td/div/table/tbody/tr[2]/td/div/table/tbody/tr[3]/td/span[2]/a</value>
      <webElementGuid>3b613d4c-717b-4c82-a141-62ed62f43e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'actionTree.1_6_1_3.k' and @href = concat(&quot;javascript:executeAction(&quot; , &quot;'&quot; , &quot;\x2FGC3\x2Fglog.webserver.util.QueryResponseServlet\x2F1750431455910\x3FbcKey\x3DMTc1MDQzMTQ1NTkxMTox\x26action_name\x3Dbulk_plan_buy\x26finder_set_gid\x3DORDER_RELEASE_WO_STOP&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Bulk Plan - Buy' or . = 'Bulk Plan - Buy')]</value>
      <webElementGuid>287d2ee0-0528-4b59-8303-a60a2b449fa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
