<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BXC.SO_TEST646952_Selected</name>
   <tag></tag>
   <elementGuidId>b5e22c1f-cde5-43de-895b-024035ffd4d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='Selected'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;BXC.SO_TEST364072&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d016b7a-3982-426d-85f6-69a3b8e4a9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>BXC.SO_TEST364072</value>
      <webElementGuid>bfba2c99-05e6-4a3e-9e6d-826d057f8b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e3b0c57f-a11f-45b1-84b3-169e78b1c976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>resultGrid.selectRow(this);handleSelectionOnServer(finderSetGid, callerID,'BXC.SO_TEST364072', this)</value>
      <webElementGuid>db771c80-91fd-4e81-8733-9395da2eb71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BXC.SO_TEST364072</value>
      <webElementGuid>aa92cbce-9d89-4a92-903a-973cb1233708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>511c1c96-55d5-407e-a747-d583b90d460a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Selected</value>
      <webElementGuid>7a2fc2ce-7c4b-4db4-bb6c-68ec731e73f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sgBodyCheck</value>
      <webElementGuid>88773bcd-d9ae-47cb-9693-d15ed0a3f8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rgSGSec.2.1.3.1&quot;)/input[@class=&quot;sgBodyCheck&quot;]</value>
      <webElementGuid>50ea2557-b40a-47b1-8b47-44b5c8651908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Bulk plan objects/Page_Order Releases Result/iframe_PRAJYOT.DABHADEBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>00a0faca-172a-486d-a097-294fdfb39c61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='Selected'])[3]</value>
      <webElementGuid>67a83e5e-c946-42d3-a994-5badcd87b235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rgSGSec.2.1.3.1']/input</value>
      <webElementGuid>c5986f63-5d76-49bc-9548-37b4d5556b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>8fe82133-4af2-48bc-a65b-20b3da8575dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'Selected']</value>
      <webElementGuid>72b606db-8e50-447a-899d-8cc71789d874</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
