<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create Buy Shipment</name>
   <tag></tag>
   <elementGuidId>e8667665-45d8-4f8a-bae2-7f9d804a5e19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='actionTree.1_6_1.l']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Create Buy Shipment&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>121df20f-672b-4f3c-84e6-317563902fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionTree.1_6_1.l</value>
      <webElementGuid>08e0f8ca-f63c-4473-8999-7a237fb9eddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>oc</value>
      <webElementGuid>68065071-8ab0-42f8-a1e6-5f3599f670f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>l</value>
      <webElementGuid>e53af377-697e-4f2b-ae5b-58b9f41583ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>fbed4fa0-d3c7-4184-927c-24eb5aea46d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Buy Shipment</value>
      <webElementGuid>ec5992d9-f606-40db-9320-a9b790d46edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionTree.1_6_1.l&quot;)</value>
      <webElementGuid>34edf0eb-2adf-443a-acae-3381d3c6fcce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Bulk plan objects/Page_Order Releases Result/iframe_concat(id(, , actionFrame, , ))_actionFrame</value>
      <webElementGuid>72c61fe0-4cbc-4d0d-80e7-ebe8892c1460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='actionTree.1_6_1.l']</value>
      <webElementGuid>997845f0-ee08-435f-9707-c17adf137367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='actionTree.1_6_1']/td/span[2]</value>
      <webElementGuid>7ad574d1-f626-42df-8b3f-24e63ea68973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operational Planning'])[1]/following::span[2]</value>
      <webElementGuid>42a6f70a-79b3-4dcf-9db3-88b9356fba47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perform Prediction'])[1]/following::span[4]</value>
      <webElementGuid>37d5b889-c366-41f2-91b6-9151a100fa14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build Buy Shipment On Primary Leg'])[1]/preceding::span[2]</value>
      <webElementGuid>37d7a661-5e2a-4949-bdb0-02edae48ac6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build Buy Shipment On Primary Leg Show Consol Options'])[1]/preceding::span[4]</value>
      <webElementGuid>13e44d5b-2372-4383-9a65-98525a112555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Buy Shipment']/parent::*</value>
      <webElementGuid>5ddc65fb-4444-4331-8c8f-76709d6ac9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td/div/table/tbody/tr/td/span[2]</value>
      <webElementGuid>76e3dda7-7ac3-4ded-86d1-668bc6b4d3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'actionTree.1_6_1.l' and @type = 'oc' and (text() = 'Create Buy Shipment' or . = 'Create Buy Shipment')]</value>
      <webElementGuid>824ce767-1688-4f46-b12c-8640e8b07985</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
