<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Customer Data Management (1)</name>
   <tag></tag>
   <elementGuidId>9573b057-9484-420a-a10d-20f47e90e56f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#groupNode_customer_data_management</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='groupNode_customer_data_management']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Customer Data Management&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>202f97e5-809e-4924-bfaf-8197c668573c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c106cb5b-cd09-4ac0-bd7d-fd9abf9ed80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>groupNode_customer_data_management</value>
      <webElementGuid>8baa30aa-7f4b-4d90-95b0-543d7f1de1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupNode_customer_data_management</value>
      <webElementGuid>e6d1d46a-77dd-454b-9af9-62196806c677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d61accc3-c132-4bc1-b371-b1659c6a349a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flat-tabs-text</value>
      <webElementGuid>66d35f1e-e0b9-4324-9cfc-7c5eb0f7baf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>760c0edd-5d4f-499a-aa71-124e25e25cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer Data Management</value>
      <webElementGuid>1f95d240-b4a7-4d05-a092-1f1782149688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;groupNode_customer_data_management&quot;)</value>
      <webElementGuid>0025ca4c-bb93-412c-a0ba-59aa5b2537a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='groupNode_customer_data_management']</value>
      <webElementGuid>831c89dc-739f-40a3-befa-10edfa7c0b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navmenu-container']/div[3]/a</value>
      <webElementGuid>fa49e7aa-78b7-4141-955b-a7c537b2ab7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Customer Data Management')]</value>
      <webElementGuid>5c3d61de-3829-4b75-aff7-ec357db571c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Good evening, Prajyot Dabhade'])[1]/following::a[3]</value>
      <webElementGuid>206469bf-9ebe-4a1b-abaa-e82c99cf542e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UAT Environment'])[1]/following::a[20]</value>
      <webElementGuid>d1b77c0a-f212-407e-81c5-2e26c359c94b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Actions'])[1]/preceding::a[5]</value>
      <webElementGuid>50e05862-e454-4233-86b8-3eaa36998a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apps'])[1]/preceding::a[14]</value>
      <webElementGuid>f3eefe22-d92a-4ad3-a8b6-4e193237d77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Customer Data Management']/parent::*</value>
      <webElementGuid>a19ea0fa-e7ec-4a01-a016-b0be2b389e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[15]</value>
      <webElementGuid>96588dd1-f361-4b7b-9129-7c637013ec42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>292f00bf-f3ef-421b-91af-d0ed10604192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'groupNode_customer_data_management' and @name = 'groupNode_customer_data_management' and (text() = 'Customer Data Management' or . = 'Customer Data Management')]</value>
      <webElementGuid>6e2ace8f-9557-4e35-939b-4928437e1580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
