<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Oracle Transportation and Global Trade Cl_c81655</name>
   <tag></tag>
   <elementGuidId>cbe4a3f7-7fbd-46d2-8e43-4977510a2f08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='table-section']/div[3]/div/div[6]/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Oracle Transportation and Global Trade Cloud Services&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f74bd291-cde0-45b0-8984-ddb159a9bf8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>97a08c3c-61bf-4e57-82b3-2ce0bc89835e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {href: $data.url, title: $data.urlTooltip}, text: $data.name, visible: !$data.urlClick</value>
      <webElementGuid>ef824190-2768-45cd-b260-2a19b02419a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://otmgtm-dev2-summit1.otmgtm.us-ashburn-1.ocs.oraclecloud.com:443</value>
      <webElementGuid>f12b747b-a9d4-4137-b409-4b00671e361e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Open User Console</value>
      <webElementGuid>42e22df8-10c9-46f4-9991-73b5a18772c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oracle Transportation and Global Trade Cloud Services</value>
      <webElementGuid>6e38a136-04e9-47cc-8553-058d0667545b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-section&quot;)/div[@class=&quot;cloudhome-section-item&quot;]/div[@class=&quot;oj-flex cloud-panelwrapper&quot;]/div[@class=&quot;oj-flex-item oj-flex oj-sm-flex-items-1 oj-sm-12 oj-md-4 oj-lg-3 oj-xl-2&quot;]/div[@class=&quot;oj-flex-item oj-panel cloudhome-tile&quot;]/div[2]/a[1]</value>
      <webElementGuid>a177aadf-15bc-4b5d-b65f-28f71526e5ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table-section']/div[3]/div/div[6]/div/div[2]/a</value>
      <webElementGuid>953676d7-1cc6-4dc0-be72-e44034400444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Oracle Transportation and Global Trade Cloud Services')])[3]</value>
      <webElementGuid>1a000520-c309-47cc-9970-e35eb17f4af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[4]/following::a[1]</value>
      <webElementGuid>9653a79c-598a-4b94-989c-d9bbf332f904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[3]/following::a[2]</value>
      <webElementGuid>2fb6ad0e-f16b-4b0c-a847-2cc635d785d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oracle Transportation and Global Trade Cloud Services'])[4]/preceding::a[1]</value>
      <webElementGuid>7e995429-c78a-4182-b8cd-dd8d6cc3cf7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/preceding::a[2]</value>
      <webElementGuid>3238c18b-358b-47a1-b002-5ea6492c1bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://otmgtm-dev2-summit1.otmgtm.us-ashburn-1.ocs.oraclecloud.com:443')])[2]</value>
      <webElementGuid>0b0e615b-f4cd-4538-b2cf-ac508e04897e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/a</value>
      <webElementGuid>ef599826-458e-48c6-9d45-4a6f904ecbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://otmgtm-dev2-summit1.otmgtm.us-ashburn-1.ocs.oraclecloud.com:443' and @title = 'Open User Console' and (text() = 'Oracle Transportation and Global Trade Cloud Services' or . = 'Oracle Transportation and Global Trade Cloud Services')]</value>
      <webElementGuid>80030d25-264a-4595-ae6d-1be7da5d8c6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
