<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Equipment Group ID_equipment_groupxid_find</name>
   <tag></tag>
   <elementGuidId>5f9ea08b-eb95-4fb8-99cd-1461a762231c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;equipment_group/xid_find&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='equipment_group/xid_find']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Equipment Group ID Search&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bd55b58d-015d-401f-95ce-cbd3e4fbae4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>dd929068-fad0-4a1a-8553-4437c56b790d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>f6e63915-caa2-4724-b5a2-951e9f198443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>73fa85f9-3c2d-4bba-a20e-3aaf108df4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Equipment Group ID Search</value>
      <webElementGuid>46d87bfd-888c-4ca0-8601-793ea8329320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(1);</value>
      <webElementGuid>47dfc5a2-5c83-4e76-b590-062ec394bd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pickListFinderLink</value>
      <webElementGuid>454a4043-cca9-408c-ba97-fb15855eef77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OpenPickList('glog.webserver.finder.models.AllEquipmentGroupFinderModel', 'management_main', 'equipment_group/xid', 'false', 'single', '', '', '', '', '','','','');</value>
      <webElementGuid>68644c60-2d54-47a1-8f0b-a44f32ac38d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>equipment_group/xid_find</value>
      <webElementGuid>6e7c509a-fd0d-4c8b-9bda-4b192e12f7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;equipmentGroup&quot;)/div[@class=&quot;fieldCont&quot;]/table[@class=&quot;noTbSp&quot;]/tbody[1]/tr[1]/td[2]/table[@class=&quot;noTbSp&quot;]/tbody[1]/tr[1]/td[1]/a[@class=&quot;pickListFinderLink&quot;]</value>
      <webElementGuid>cbcbeae3-e570-4a47-a726-de0d57bd2ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Change Equipment Group/iframe_concat(id(, , mainBodyFrame, , ))_mainBody</value>
      <webElementGuid>0e1b1a56-ea98-44be-a427-226335c21a13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='equipment_group/xid_find']</value>
      <webElementGuid>9e1694d7-486b-439d-8135-28ce2cfcb6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='equipmentGroup']/div/table/tbody/tr/td[2]/table/tbody/tr/td/a</value>
      <webElementGuid>a55fae70-ec36-46a6-977d-6c1a4ec6241a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(1);')]</value>
      <webElementGuid>d2b02bfa-7ab2-4cd8-abb0-715ea6caab98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>f060e705-360c-4a6b-8aa1-bc0d0f455d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Search' and @alt = 'Search' and @href = 'javascript:void(1);' and @name = 'equipment_group/xid_find']</value>
      <webElementGuid>84ad07d8-c3c6-439b-826c-91b0fd68007a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
