<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_mainBody</name>
   <tag></tag>
   <elementGuidId>2043c13e-765f-4f62-9b4e-8a49a83f9499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainBodyFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainBodyFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;mainBody&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>edd7c8f3-d300-44d6-9be2-d8cec3c4c937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframeBody</value>
      <webElementGuid>ee3fe290-b65d-4be3-8130-b4575ae9372a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>03f63f1f-53ba-47be-9819-07a8928ea2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mainBody</value>
      <webElementGuid>900390a0-a7bf-48e6-95cf-ca2fc2d37b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainBodyFrame</value>
      <webElementGuid>1efe9c6a-3c88-4e9d-b55e-f9edf3dd774a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.util.QueryResponseServlet/1748433615086?bcKey=new&amp;action_name=change_equipgroup&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.6007</value>
      <webElementGuid>54c5bf4e-2f68-4096-8fdc-fad5bb7b13c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainBodyFrame&quot;)</value>
      <webElementGuid>eafd8a7e-4627-4886-8e0f-4ebcf01eaf49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainBodyFrame']</value>
      <webElementGuid>78706084-5923-44be-affc-5aeb921f3d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>f3187c2a-c590-4af2-93a5-47ef79a8dcdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1748433615086?bcKey=new&amp;action_name=change_equipgroup&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.6007']</value>
      <webElementGuid>276a8ee1-2d88-4473-bd77-d2e18f85d4db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
