report.videoRecorderOption="{\\"enable\\"\:false,\\"useBrowserRecorder\\"\:true,\\"videoFormat\\"\:\\"AVI\\",\\"videoQuality\\"\:\\"LOW\\",\\"recordAllTestCases\\"\:false,\\"allowedRecordIfFailed\\"\:true,\\"allowedRecordIfPassed\\"\:false}"
mailConfig.encryptionEnabled=false
mailConfig.host="smtp.gmail.com"
mailConfig.port="587"
mailConfig.username="testautomationblx@gmail.com"
mailConfig.password="bjvs ravu nkaz pkqb"
mailConfig.securityProtocol="TLS"
mailConfig.attachment=true
mailConfig.subject="Katalon Summary Report for ${suiteName} ${suiteCollectionName}"
mailConfig.cc=""
mailConfig.bcc=""
mailConfig.useUsernameAsSender=true
mailConfig.sender="testautomationblx@gmail.com"
mailConfig.reportRecipients="Prajyot.Dabhade@BlueLinxCo.com;Gaurav.Prasad@BlueLinxCo.com"
mailConfig.reportFormat="[\\n  \\"HTML\\"\\n]"
mailConfig.sendTestSuiteReport=true
mailConfig.sendReportTestFailedOnly=false
mailConfig.sendTestSuiteCollectionReport=false
mailConfig.skipIndividualTestSuiteReport=false
