<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transportation and Global Trade Manage_f1b5a4</name>
   <tag></tag>
   <elementGuidId>0a476563-ade2-4428-ba13-8f8ad104f83c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//oj-button[@id='homeButton']/button/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-home.tm-ugh-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Home&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>66bcc508-ae90-47b5-89ef-31096d3293b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>slot</name>
      <type>Main</type>
      <value>startIcon</value>
      <webElementGuid>17ef4579-c764-41a5-820f-1bdbefc2a8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-home tm-ugh-icon</value>
      <webElementGuid>6302d09e-bd16-43ac-a702-13c6cb373126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homeButton&quot;)/button[@class=&quot;oj-button-button&quot;]/div[@class=&quot;oj-button-label&quot;]/span[@class=&quot;oj-button-icon oj-start&quot;]/span[@class=&quot;fa fa-home tm-ugh-icon&quot;]</value>
      <webElementGuid>52e1ac85-82fb-4b49-a20c-785195ecf82c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//oj-button[@id='homeButton']/button/div/span/span</value>
      <webElementGuid>79910fc7-fccf-4df6-a561-ad9427aa6f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/oj-button/button/div/span/span</value>
      <webElementGuid>ba6bada3-2bd1-4bcf-8ed5-74c4f4ce72b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
