<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Category</name>
   <tag></tag>
   <elementGuidId>5d6395cc-6205-408c-a6a4-51513f26f2fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.p_AFSelected.p_AFFocused.xem > td:nth-of-type(2) > div > table > tbody > tr > td.xen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pt1:_FOr1:1:_FONSr2:0:MAt2:0:pt1:ItemC1:0:simplePanel1:region2:0:shuttleRnIdAddFields:0:ATR4:_ATTp:ATRr4::db&quot;]/table[2]/tbody/tr[1]/td[2]/div/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Category&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9bec18d4-56a1-4278-94dc-12e1f88c6db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xen</value>
      <webElementGuid>c6d18b7c-350e-4d6b-b32f-99e0681301cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_afrndcol</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>84592c96-b983-44f3-8aba-1a517ef5326e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c1abdb2c-b29d-43f0-815b-c6457bae0128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Category</value>
      <webElementGuid>4ac7af2d-7d24-4e3d-aba8-834edba43552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAt2:0:pt1:ItemC1:0:simplePanel1:region2:0:shuttleRnIdAddFields:0:ATR4:_ATTp:ATRr4::db&quot;)/table[@class=&quot;x1hi x1i6&quot;]/tbody[1]/tr[@class=&quot;p_AFSelected p_AFFocused xem&quot;]/td[2]/div[1]/table[1]/tbody[1]/tr[1]/td[@class=&quot;xen&quot;]</value>
      <webElementGuid>4d3938fe-2109-44c0-8a00-18e54d3d06ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAt2:0:pt1:ItemC1:0:simplePanel1:region2:0:shuttleRnIdAddFields:0:ATR4:_ATTp:ATRr4::db']/table[3]/tbody/tr[2]/td[2]/div/table/tbody/tr/td</value>
      <webElementGuid>3ef211c8-e950-4bc9-bd86-50b57cff0f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catalog'])[2]/following::td[3]</value>
      <webElementGuid>1a49b301-220b-44a8-b884-88d4c82bf3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catalog'])[1]/following::td[7]</value>
      <webElementGuid>3564e5ed-e683-422d-b18b-9ac5c6446551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Competitor'])[1]/preceding::td[3]</value>
      <webElementGuid>2b429819-bedf-4bf5-955d-e1acadeb3185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr[2]/td[2]/div/table/tbody/tr/td</value>
      <webElementGuid>5bb5de29-7ade-4bbb-899b-fd3ffe417390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Category' or . = 'Category')]</value>
      <webElementGuid>998ad58a-e933-4bea-8ad1-0233653efd93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
