<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__ship_unit_equip_ref_unit_joinequipment_r_c4d8f5</name>
   <tag></tag>
   <elementGuidId>fb17f9dd-777a-4d69-8575-c9bf1b3f14e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='ship_unit_equip_ref_unit_join/equipment_reference_unit_xid_find']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;ship_unit_equip_ref_unit_join/equipment_reference_unit_xid_find&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Equipment Reference Unit ID Search&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0efc1e0a-8862-4c71-88ca-22e9b757d53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9aba9653-9650-4967-925e-2e7a41606a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Equipment Reference Unit ID Search</value>
      <webElementGuid>0fe1b24a-f45e-4412-a947-a08e1447e1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(1);</value>
      <webElementGuid>4607f762-ff51-4b6c-a57b-af2e00e7b275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pickListFinderLink</value>
      <webElementGuid>01fae99c-c606-4f58-8d4e-ed08181d811b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>e3702044-5679-4377-9f1f-e92075d77995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>643f8bb4-5551-4fa1-a717-6f08a2f64609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OpenPickList('glog.server.query.powerdata.EquipmentReferenceUnitQuery','management_main','ship_unit_equip_ref_unit_join\x2Fequipment_reference_unit_xid','false','single','','','','','Please\x20pass\x20in\x20a\x20valid\x20argument','');</value>
      <webElementGuid>0cbd74ba-6308-4ffb-b4ac-c21773afac94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ship_unit_equip_ref_unit_join/equipment_reference_unit_xid_find</value>
      <webElementGuid>b1a143e0-ab2b-4534-93fb-3868982d90de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_ship_unit_equip_ref_unit_join_grid&quot;)/tbody[1]/tr[1]/th[@class=&quot;gridHeadCell&quot;]/div[@class=&quot;fieldCont&quot;]/table[@class=&quot;noTbSp&quot;]/tbody[1]/tr[1]/td[2]/table[@class=&quot;noTbSp&quot;]/tbody[1]/tr[1]/td[1]/a[@class=&quot;pickListFinderLink&quot;]</value>
      <webElementGuid>08cd21dc-5f83-462d-99fe-fd7f317e118a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Order Release - Ship Unit/iframe_PRAJYOT.DABHADEBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>bd6a2247-1670-4881-98d4-96e5bb62e5b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='ship_unit_equip_ref_unit_join/equipment_reference_unit_xid_find']</value>
      <webElementGuid>cacfb268-2745-4414-8221-f954522a0480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_ship_unit_equip_ref_unit_join_grid']/tbody/tr/th/div/table/tbody/tr/td[2]/table/tbody/tr/td/a</value>
      <webElementGuid>2971765f-4e04-4a3c-b151-321d5af271d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(1);')])[15]</value>
      <webElementGuid>f24cfd59-e59b-474f-87ca-49c499535201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/table/tbody/tr/th/div/table/tbody/tr/td[2]/table/tbody/tr/td/a</value>
      <webElementGuid>cc73dfdb-e29c-48e1-84bb-0afe71c61b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(1);' and @title = 'Search' and @alt = 'Search' and @name = 'ship_unit_equip_ref_unit_join/equipment_reference_unit_xid_find']</value>
      <webElementGuid>f97db169-4f7e-4747-a91f-195e54ed68de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
