<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Name_idcs-signin-basic-signin-fo_93898c</name>
   <tag></tag>
   <elementGuidId>c26018fd-ab7b-41d2-bb3f-b7e22bdf5f95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idcs-signin-basic-signin-form-username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idcs-signin-basic-signin-form-username</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;User name or email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f0b4f17-8cc6-4a50-a0c4-136c8a2eb364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idcs-signin-basic-signin-form-username</value>
      <webElementGuid>5cf8b05e-4df1-4cf9-bfdd-d86cf6f0c95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idcs-placeholder-translation-id</name>
      <type>Main</type>
      <value>idcs-username-placeholder</value>
      <webElementGuid>78705e62-cdc1-437c-8124-57315f13d2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b5f0ea5a-52d5-44b6-870a-b45cfff24aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oj-sm-12 oj-form-control oj-inputtext-nocomp</value>
      <webElementGuid>8cabfb4d-889c-484b-8698-2c537979898d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:class</name>
      <type>Main</type>
      <value>[[{'idcs-signin-rw-floating-input': isOracleEmployeeRedwood || isCustomerRedwood}]]</value>
      <webElementGuid>cd5c000a-a57d-4f8b-b58d-9cc36cd1cd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>b893a9da-92a4-4b16-a2ef-e7207c4014e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ebb0c3cd-a775-49f7-a6b7-63d5ad354179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b57008fa-87cf-459e-aadb-c168d401e46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:placeholder</name>
      <type>Main</type>
      <value>[[bundle('signin.usernamePlaceHolder')]]</value>
      <webElementGuid>0223d81a-1a1f-417f-bbff-540c9936e1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:disabled</name>
      <type>Main</type>
      <value>[[$params.disableInput]]</value>
      <webElementGuid>c42e66ad-05ad-4bff-92bc-716faa54dfbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: username</value>
      <webElementGuid>d09b5680-94de-4e0b-a923-50fa38206a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idcs-enable-right-click</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>40077753-91fe-46d6-aa6d-ac2af9161071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User name or email</value>
      <webElementGuid>7a8a886e-94c9-43a2-84c7-d98504a90211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idcs-signin-basic-signin-form-username&quot;)</value>
      <webElementGuid>a773bc08-c61e-4008-a236-6f7d87a7146d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idcs-signin-basic-signin-form-username']</value>
      <webElementGuid>3c206b59-3046-4b27-871a-b182236124bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idcs-app-shell-signin-background']/div/div/div[2]/div/div/oj-module/div/oj-module/div/div/div/div/div/input</value>
      <webElementGuid>e1ce4dea-a371-43ca-9bad-8e5fbb5075f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1c6b3482-9996-42e3-94ba-51f8fc8b29c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'idcs-signin-basic-signin-form-username' and @type = 'text' and @placeholder = 'User name or email']</value>
      <webElementGuid>bf9693dc-5f45-4a10-adb9-45d91f3d7d5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
