<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BXC.IAR_FREIGHT_ANALYST</name>
   <tag></tag>
   <elementGuidId>ca017d4b-68f9-4a47-b17e-0a9d2e4f46ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='rgSGSec.2.1.1.3.k']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;BXC.IAR_FREIGHT_ANALYST&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b503b8d8-6349-4616-8334-3a2da706157f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rgSGSec.2.1.1.3.k</value>
      <webElementGuid>449f2a71-4049-43c5-be65-9c50e5b976c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4c1d2443-1214-4755-9d2f-8df798485315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>e0a566cb-8b79-471b-8ca4-269150f1693b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OpenTarget('/GC3/glog.webserver.fprule.AutoApproveRuleManagementServlet?bcKey=MTc0NzkyODM1MjM1ODox&amp;pk=BXC.IAR_FREIGHT_ANALYST&amp;finder_set_gid=AUTO_APPROVE_RULE&amp;management_action=edit'); return addToRecentlyViewed(finderSetGid,'BXC.IAR_FREIGHT_ANALYST', 'EDIT');</value>
      <webElementGuid>47574a4f-8023-4542-aadf-cb5693eefa5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BXC.IAR_FREIGHT_ANALYST</value>
      <webElementGuid>73829132-a7c4-4c86-b4a5-c4f927009b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rgSGSec.2.1.1.3.k&quot;)</value>
      <webElementGuid>5a5af827-38f3-491f-992a-c37c215b213a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Invoice Approve Rules Result/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>05112000-8591-4304-bd46-32b6041c150e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='rgSGSec.2.1.1.3.k']</value>
      <webElementGuid>e892a91a-812e-4922-b444-12fa800963dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rgSGSec.2.1.1.3']/a</value>
      <webElementGuid>3733e3a2-25cd-43fe-a54a-942cec0c5cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BXC.IAR_FREIGHT_ANALYST')]</value>
      <webElementGuid>b6af725b-0ff4-4c8c-ac88-eda398079e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Domain Name'])[1]/following::a[2]</value>
      <webElementGuid>8a13611d-2b81-492a-90a4-747ffca114e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Weight Rule'])[1]/following::a[2]</value>
      <webElementGuid>5b888d35-5f02-44cf-8dde-a76e54bd2a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BXC.DEFAULT_IAR_ROAD'])[1]/preceding::a[2]</value>
      <webElementGuid>f3b7d4e0-7fb1-40b9-be85-32e2d742ad6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BXC.DEFAULT_IAR_RAIL'])[1]/preceding::a[4]</value>
      <webElementGuid>a3f43627-0f10-41df-82e9-a4c70dce288f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BXC.IAR_FREIGHT_ANALYST']/parent::*</value>
      <webElementGuid>590d70de-51d5-472f-961a-6aac8304e754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[2]</value>
      <webElementGuid>cf0e8acb-8097-4347-976f-72efcd1f75a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>690658a3-eaba-498d-b384-5dc313f8e536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'rgSGSec.2.1.1.3.k' and @href = 'javascript:void(0);' and (text() = 'BXC.IAR_FREIGHT_ANALYST' or . = 'BXC.IAR_FREIGHT_ANALYST')]</value>
      <webElementGuid>6b362f92-db43-4608-9c10-55906cc097d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
