<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Finished</name>
   <tag></tag>
   <elementGuidId>29d27b2d-65e4-4797-b88b-0feb0e9fb045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='finished_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;finished_button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Finished&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bde54a35-73aa-43de-818f-644ce5d280e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enButton</value>
      <webElementGuid>92baa246-0725-47b3-b4ba-27140133e61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a1ab88e2-f069-4238-a29b-1f042ab0abee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>function t() { javascript:setLogProfile('dataQueryType', 'data', 'logProfile@ID'); return true; } if(t.call(this) !== false) { javascript:createFinishedURL('/GC3/IeShipmentstatusCustSave/1750408117800?bcKey=MTc1MDQwODExNzQ0MTow&amp;step=Header'); } else { return false; }</value>
      <webElementGuid>0153d5b6-44d6-4f3f-816f-159d76f82ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>finished_button</value>
      <webElementGuid>9cbff804-1db5-4c75-8ccf-5bdd70a6e5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Finished</value>
      <webElementGuid>16eec6d0-4ca1-4cdf-aac8-fdd9d4df82d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;body1&quot;]/div[@class=&quot;bodyHeaderCont&quot;]/table[@class=&quot;hdLine&quot;]/tbody[1]/tr[1]/td[2]/table[@class=&quot;buttonsCont&quot;]/tbody[1]/tr[1]/td[3]/div[@class=&quot;buttonCont&quot;]/button[@class=&quot;enButton&quot;]</value>
      <webElementGuid>a78e0fa9-0816-47fb-8c9d-839d94ad5563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tracking Event - Identification/iframe_concat(id(, , mainBodyFrame, , ))_mainBody</value>
      <webElementGuid>006a14b1-4789-4759-8997-10408a9a591c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='finished_button']</value>
      <webElementGuid>ad23c67a-bd2b-4c7c-9ee6-8fafc43ebf14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[1]/following::button[1]</value>
      <webElementGuid>b8676112-792d-4291-bbe2-38d63b15877b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracking Event'])[1]/following::button[2]</value>
      <webElementGuid>2308a167-d595-4a7e-9d9c-31e5d664b074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Profile'])[1]/preceding::button[1]</value>
      <webElementGuid>70083eee-ed26-4c61-8704-58800d92a34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identification'])[1]/preceding::button[1]</value>
      <webElementGuid>0930fb3a-0bab-458f-977b-2f10b74f70a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Finished']/parent::*</value>
      <webElementGuid>4a138859-3a3c-45d5-89f5-f52400e1522d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/button</value>
      <webElementGuid>0670c4a1-0ec3-401c-9649-fea1e820e169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'finished_button' and (text() = 'Finished' or . = 'Finished')]</value>
      <webElementGuid>94e60767-b97f-41b2-9016-853cb77457bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
