<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transportation and Global Trade Manage_f1b5a4</name>
   <tag></tag>
   <elementGuidId>c230d703-92f6-4a58-8a22-bdb2a337947f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//oj-button[@id='homeButton']/button/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-home.tm-ugh-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Home&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d2dd4ffc-7fd4-4538-a494-9c0085f1f130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>slot</name>
      <type>Main</type>
      <value>startIcon</value>
      <webElementGuid>80fa170c-eac9-4baf-ad2c-4a1b47dd49c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-home tm-ugh-icon</value>
      <webElementGuid>920f587b-20aa-4116-ad94-5ef5347a74ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homeButton&quot;)/button[@class=&quot;oj-button-button&quot;]/div[@class=&quot;oj-button-label&quot;]/span[@class=&quot;oj-button-icon oj-start&quot;]/span[@class=&quot;fa fa-home tm-ugh-icon&quot;]</value>
      <webElementGuid>9e6f4848-9440-491b-b77b-31b717f13d4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//oj-button[@id='homeButton']/button/div/span/span</value>
      <webElementGuid>b1ece29c-3f09-458a-b798-543e0d15ca40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/oj-button/button/div/span/span</value>
      <webElementGuid>3d00f1b3-f3a3-44af-ab88-7ada8814b0dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
