<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , mainBodyFrame, , ))_mainBody_1</name>
   <tag></tag>
   <elementGuidId>2267ad8f-4cce-40ca-9315-6c12291895eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainBodyFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainBodyFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;mainBody&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>42ca4e3d-daab-45fe-9a4a-0bebdc97008f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframeBody</value>
      <webElementGuid>05893055-578e-4978-af6c-88855db97cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c1873cfe-235b-4ee5-9922-94caa6d96991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mainBody</value>
      <webElementGuid>abbc0cea-3b8e-4092-90a1-d6ae5e25e894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainBodyFrame</value>
      <webElementGuid>4e1462e7-e397-4b89-98e2-091e6b7682e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.util.QueryResponseServlet/1756978583636?bcKey=new&amp;action_name=bulk_plan_buy&amp;finder_set_gid=BXC.ORDER%20RELEASE_UPDATE&amp;management_action=go&amp;finder_set_gid=BXC.ORDER%20RELEASE_UPDATE&amp;pk=BXC.SO_17552398</value>
      <webElementGuid>d0c1037d-fd2c-4da1-865f-e10e73670275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainBodyFrame&quot;)</value>
      <webElementGuid>571c2922-3e57-4085-9c72-4e9a3d395258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainBodyFrame']</value>
      <webElementGuid>8b6e3aa4-f6ba-4659-81a5-87307e89f6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>95d28008-22b8-4d4f-b69c-35d543960f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1756978583636?bcKey=new&amp;action_name=bulk_plan_buy&amp;finder_set_gid=BXC.ORDER%20RELEASE_UPDATE&amp;management_action=go&amp;finder_set_gid=BXC.ORDER%20RELEASE_UPDATE&amp;pk=BXC.SO_17552398']</value>
      <webElementGuid>b30f4ab5-4739-48d9-aaa9-b81c95ab5f90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
