<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_000102030405060708091011121314151617_d567da</name>
   <tag></tag>
   <elementGuidId>853bac98-dfcf-45b9-8cf0-8a7c2cd20dcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='order_release/early_pickup_date::popChooseDate::hrs']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Hours&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>873e2a94-09ed-457d-a67b-887cd5523903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_release/early_pickup_date::popChooseDate::hrs</value>
      <webElementGuid>08353e95-4cbf-4e43-9809-0e36bcc80995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Hours</value>
      <webElementGuid>89eea3d1-bc8c-4559-abf8-6d4ae61e4a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_release/early_pickup_date::popChooseDate::hrs</value>
      <webElementGuid>4f8df18a-ebd1-4fd4-bccb-5357e20bdd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>000102030405060708091011121314151617181920212223</value>
      <webElementGuid>55cc3f03-bd6c-4d79-9d6e-63bfb2b05fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_release/early_pickup_date::popChooseDate::hrs&quot;)</value>
      <webElementGuid>100b714b-9cb4-4045-8a17-de9a0f6bd196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Folder (1)/Page_Change Pickup and Delivery Dates/iframe_mainBody</value>
      <webElementGuid>80e149a2-a28a-4b2a-97a0-59482b3a0325</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='order_release/early_pickup_date::popChooseDate::hrs']</value>
      <webElementGuid>29f6ea75-ab22-49b5-a222-03b91fbc64a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='order_release/early_pickup_date::popChooseDate']/tbody/tr[3]/td/table/tbody/tr/td/select</value>
      <webElementGuid>0de8d627-c81f-4da9-8460-e1f95ea0244b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::select[1]</value>
      <webElementGuid>57f8aeaa-03d8-451e-8477-7308e68ab2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::select[1]</value>
      <webElementGuid>31de1f10-9204-485c-b5d7-64d148c09b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr/td/select</value>
      <webElementGuid>40745cfb-c426-4e37-b4f7-e3724b122fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'order_release/early_pickup_date::popChooseDate::hrs' and @id = 'order_release/early_pickup_date::popChooseDate::hrs' and (text() = '000102030405060708091011121314151617181920212223' or . = '000102030405060708091011121314151617181920212223')]</value>
      <webElementGuid>beaa8dff-0279-4309-92a3-0c70c1fe9fb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
