<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Shipment_adder</name>
   <tag></tag>
   <elementGuidId>09d00914-8a1e-4512-a5ec-72d635c67db8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;RootPane_1_1&quot;]/wb-layout//*[@id=&quot;RootPane_1_1_region_0_addRows&quot;]/button/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
