<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_PRAJYOT.DABHADEBLUELINXCO.COM_mainIFrame (6)</name>
   <tag></tag>
   <elementGuidId>4bc0d5b3-b582-46bc-80fd-8871cc4d7385</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainIFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainIFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mainIFrame</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c41f18d7-1c0b-49dc-a812-0b10787c2860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainIFrame</value>
      <webElementGuid>1c0462ca-157a-4973-83ea-a413a33a3471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oj-web-applayout-content-nopad</value>
      <webElementGuid>7f799b05-7afa-4987-a5ff-88e0ddf9eb4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>mainIFrameOnLoad()</value>
      <webElementGuid>567f8ba0-206d-464b-b947-8cf59fc37f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr : {src: IFRAME_URL}</value>
      <webElementGuid>38ad6131-2626-42a0-9dfe-b07af3928e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.powerdata.PowerdataContractServlet?bcKey=new&amp;user_menu_layout_gid=ADMIN_MENU</value>
      <webElementGuid>20fd9425-b7a6-42ad-98e3-5fb56c3ab7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainIFrame&quot;)</value>
      <webElementGuid>0a51b373-e68c-493e-bdbd-252db64c65d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainIFrame']</value>
      <webElementGuid>da4855e4-bbb9-4577-81f2-2fd7bcb842ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//oj-module[@id='mainModule']/iframe</value>
      <webElementGuid>7f4cb345-e35b-4109-84e1-4bbe5cf501bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c8083ee8-53b9-4f4b-a770-0cf132e4ddd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'mainIFrame' and @src = '/GC3/glog.webserver.powerdata.PowerdataContractServlet?bcKey=new&amp;user_menu_layout_gid=ADMIN_MENU']</value>
      <webElementGuid>6f177195-66b0-4884-ac10-9d11a180b1b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
