<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Value_pt1_FOr11_FONSr20MAnt21AP1AT4_ATpta_54bda1</name>
   <tag></tag>
   <elementGuidId>e053b4af-b815-4a95-b300-2d2b6a8a3682</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Object Attribute Operator&quot;i] >> a >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8b2f5898-66af-408d-b959-71bbe69bbdae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>30bb06eb-fff9-4472-a56c-e837f0e20f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1kv</value>
      <webElementGuid>7ec9c468-4cf6-453b-8f5c-8d9c5d929a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:MAnt2:1:AP1:AT4:_ATp:table4:0:ruleObjName::drop</value>
      <webElementGuid>14bc14de-39fa-4261-8909-c7283af39dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:MAnt2:1:AP1:AT4:_ATp:table4:0:ruleObjName::drop&quot;)</value>
      <webElementGuid>46a16615-059b-438b-856d-44b93d0bef93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pt1:_FOr1:1:_FONSr2:0:MAnt2:1:AP1:AT4:_ATp:table4:0:ruleObjName::drop']</value>
      <webElementGuid>4b9b5207-a17c-45ee-8285-bc1897568b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pt1:_FOr1:1:_FONSr2:0:MAnt2:1:AP1:AT4:_ATp:table4:0:ruleObjName::cntrl']/a</value>
      <webElementGuid>17997ff0-580d-4f6c-b699-7824b7eeee25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/a</value>
      <webElementGuid>4f98cf9c-f5f1-4695-805f-798916335187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pt1:_FOr1:1:_FONSr2:0:MAnt2:1:AP1:AT4:_ATp:table4:0:ruleObjName::drop']</value>
      <webElementGuid>4fc25401-4043-4d3f-b64e-e3d614fc7218</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
