<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Address line 1</name>
   <tag></tag>
   <elementGuidId>f7e03e58-fae9-41a5-91de-2c25de3405ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='PrintMe'])[1]/following::li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Address line 1&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5434aaec-b7d7-4aeb-904b-82b26229dcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1l7</value>
      <webElementGuid>cbf1ec3f-fc38-4bde-973c-79665c57a035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_adfiv</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ed0b99cc-c56b-4736-bef3-16688e868350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Address line 1</value>
      <webElementGuid>99470030-7c3d-45ed-bc03-3a1571cd4c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:MAnt2:1:AP1:AT4:_ATp:table4:0:attributeName::pop&quot;)/li[@class=&quot;x1l7&quot;]</value>
      <webElementGuid>a6caf911-4941-4f29-9ecf-2d698047d6c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pt1:_FOr1:1:_FONSr2:0:MAnt2:1:AP1:AT4:_ATp:table4:0:attributeName::pop']/li[3]</value>
      <webElementGuid>1926c939-4965-4fa7-ac78-f38bd317114e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PrintMe'])[1]/following::li[3]</value>
      <webElementGuid>cef16d84-d999-4e88-8f13-d589db282407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[1]/following::li[3]</value>
      <webElementGuid>110d5807-5587-4125-9076-4bdc8cfba23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address line 2'])[1]/preceding::li[1]</value>
      <webElementGuid>e0b81e1d-2a5d-415e-8347-9262249c87c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/preceding::li[2]</value>
      <webElementGuid>9d5bf2c1-1c2c-4d64-9c43-f96597211ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Address line 1']/parent::*</value>
      <webElementGuid>7fb1a44a-3652-4f55-a33b-ba4e8a550014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/ul/li[3]</value>
      <webElementGuid>0180390e-4073-4df9-a917-3481963d150f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Address line 1' or . = 'Address line 1')]</value>
      <webElementGuid>0ccdb7ba-7093-423b-befa-e97a009a2e92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
