<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lane Service Providers_selectAllOTMSelected</name>
   <tag></tag>
   <elementGuidId>f1e6a0d2-ef7a-4489-b79e-3cfdf3ac00c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='selectAllOTMSelected']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;selectAllOTMSelected&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Collapse Lane Service Providers&quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e42595e-8c94-4db2-9aa5-5bebbdbf31ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7909115c-1900-480d-9008-50ef7d598eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>16b1b7b1-e9d2-465f-9696-9217ddd4e53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectAllOTMSelected</value>
      <webElementGuid>572dea0f-ea77-4bb0-8344-3dc7646908d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:CheckAll('lane_selected_servprov_xid', this);</value>
      <webElementGuid>6cf6620c-dbac-404a-8d0f-884e17a34558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bebba679-6f55-4c90-a7c4-737a057e824a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;label_serviceproviders&quot;)/input[1]</value>
      <webElementGuid>de2c3ba8-fe3b-411a-b8f1-8758e8f551b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Service Provider/iframe_mainBody</value>
      <webElementGuid>c32b19f5-29e0-45a1-a0ec-ac6bbb5cc3a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='selectAllOTMSelected']</value>
      <webElementGuid>373fec07-d20f-4124-9bde-4ca90f8128df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='label_serviceproviders']/input</value>
      <webElementGuid>dc5feeea-7754-44d7-ad65-e4f3ec1fe3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>cc43e148-e8a7-4444-b8ba-ec04c95b3e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @checked = 'on' and @name = 'selectAllOTMSelected']</value>
      <webElementGuid>24894c83-5a4b-4f56-9656-16519d8065a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
