<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , actionFrame, , ))_actionFrame</name>
   <tag></tag>
   <elementGuidId>a21a1982-f116-4453-8c6f-f6392dabada0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='actionFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#actionFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;actionFrame&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>cf608d46-9f7a-46be-ba5e-b7bcc154e959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actionFrame</value>
      <webElementGuid>bd873ad6-6de7-4d6b-9d1a-4bcfa3841f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionFrame</value>
      <webElementGuid>3844ee8c-0754-4392-bf37-f6e40f8f9c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iWinFrame</value>
      <webElementGuid>4100e1f6-1935-4d6c-84bc-36ebf90dd99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1148ecc2-1627-45eb-ab0a-77f86e6eae45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>bc6ec5ec-d229-412d-af41-e6b8139659c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.finder.ActionServlet/1747290446000?bcKey=MTc0NzI5MDQ0NjAwMDow&amp;query_name=glog.server.query.invoice.InvoiceInvoiceQuery&amp;finder_set_gid=INVOICE_INVOICE</value>
      <webElementGuid>c096a9b5-df88-4e33-a668-602498b0b4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pageloaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8e2cd73c-2d5c-4e4a-b0bf-74086f53f065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionFrame&quot;)</value>
      <webElementGuid>1fdad6aa-1b05-4f69-bed4-6fab4946f7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Invoices Result/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>749599e7-999d-4364-b351-b2536efcdbda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='actionFrame']</value>
      <webElementGuid>cf5fe500-7e8c-43fd-aa6a-4c77e7ab6e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/iframe</value>
      <webElementGuid>a9a63d71-6128-45e5-95f9-7d8b21eab869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'actionFrame' and @id = 'actionFrame' and @src = '/GC3/glog.webserver.finder.ActionServlet/1747290446000?bcKey=MTc0NzI5MDQ0NjAwMDow&amp;query_name=glog.server.query.invoice.InvoiceInvoiceQuery&amp;finder_set_gid=INVOICE_INVOICE']</value>
      <webElementGuid>defa51f8-4388-4bda-b4a8-484333f8e39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'actionFrame' and @id = 'actionFrame' and @src = '/GC3/glog.webserver.finder.ActionServlet/1745926052072?bcKey=MTc0NTkyNjA1MjA3Mzow&amp;query_name=glog.server.query.invoice.InvoiceInvoiceQuery&amp;finder_set_gid=INVOICE_INVOICE']</value>
      <webElementGuid>a89fea4d-4de2-4744-9215-ca5a85b32a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'actionFrame' and @id = 'actionFrame' and @src = '/GC3/glog.webserver.finder.ActionServlet/1745856208294?bcKey=MTc0NTg1NjIwODI5NTow&amp;query_name=glog.server.query.invoice.InvoiceInvoiceQuery&amp;finder_set_gid=INVOICE_INVOICE']</value>
      <webElementGuid>e02408cc-6903-4be6-9737-4d57c65b4fac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
