<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select Date and Time_shipmentend_timepopC_451a14</name>
   <tag></tag>
   <elementGuidId>0ccd0710-9deb-4542-9918-b82243a4f220</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='shipment/end_time::popChooseDate::nm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;shipment\/end_time\:\:popChooseDate\:\:nm&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a935852a-e534-4b47-9c47-f0ca4c4ccfca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shipment/end_time::popChooseDate::nm</value>
      <webElementGuid>259d16b7-1cb3-4b85-a150-448e1f081a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calNM</value>
      <webElementGuid>d85de09b-504a-41c8-9094-e3f981c4295e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>c9c216ce-b928-4d36-b6b2-b1a02326a46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>c6b939b5-b682-4e1b-9205-4d38b3c5a4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shipment/end_time::popChooseDate::nm&quot;)</value>
      <webElementGuid>7fce8f25-c769-4df5-9d72-9ee5121d7fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Buy Shipment - Identification/iframe_PRAJYOT.DABHADEBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>b723c88b-45f4-46b3-b883-de3b49fb50ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='shipment/end_time::popChooseDate::nm']</value>
      <webElementGuid>9da4d6ef-4463-4e70-8238-3d5fd7e0f51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='shipment/end_time::popChooseDate']/tbody/tr/td/table/tbody/tr/td[4]/a</value>
      <webElementGuid>39a7b521-a1df-4dbe-8a76-0fde0e846d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>c8830fef-0fe8-4388-9c52-7826c46e92eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/table/tbody/tr/td[4]/a</value>
      <webElementGuid>8372a2ad-5bf8-495f-a89b-23707fb54686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'shipment/end_time::popChooseDate::nm' and @href = 'javascript:void(0)']</value>
      <webElementGuid>6f1a9348-7240-4e45-bba9-80841a60fa1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
