<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Open in New Window_label8</name>
   <tag></tag>
   <elementGuidId>b5637622-6297-4943-b670-6ddf5459cedc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='label8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#label8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Menu&quot;s >> internal:text=&quot;Fleet Management&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fecebe7e-ea95-4d4a-89b6-3ea3e9f9a5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:id</name>
      <type>Main</type>
      <value>[[getLabelId(menu.index)]]</value>
      <webElementGuid>cd0844a2-09c0-47cd-8fa4-1503773ebc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tm-text-align-center tm-sb-tile-label</value>
      <webElementGuid>d1a10724-9a1f-42e1-a05e-64c5a39fca58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:style</name>
      <type>Main</type>
      <value>[[{'color':theme_main_font_color}]]</value>
      <webElementGuid>32aa9bad-1ab0-42e3-b7d9-a3876ae34aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>label8</value>
      <webElementGuid>3aa8cefc-0d35-417f-a27e-cda37c56d90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Fleet Management
                </value>
      <webElementGuid>6ddd64ba-72ab-486e-99d4-bbed5c786637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;label8&quot;)</value>
      <webElementGuid>2880c672-e5d2-4d26-98c8-a533ad293382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='label8']</value>
      <webElementGuid>b3694d31-5dd3-46c5-84fa-7325e866f983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sb_7']/div/div/div[2]</value>
      <webElementGuid>e6565f76-af0c-4f83-a7a1-65f98f50f61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open in New Window'])[11]/following::div[5]</value>
      <webElementGuid>d81973ec-014f-4a2a-8e11-b54b74b7280d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open in New Window'])[12]/preceding::div[1]</value>
      <webElementGuid>cc4f195a-0941-4909-86a1-a1386e672863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]</value>
      <webElementGuid>9d7f9fbe-5563-4f02-b360-73468cdf0196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'label8' and (text() = '
                  Fleet Management
                ' or . = '
                  Fleet Management
                ')]</value>
      <webElementGuid>987f401f-f91c-402d-b593-c708755defa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
