<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select Date and Time_driver_power_unit_jo_d1a10a</name>
   <tag></tag>
   <elementGuidId>d8dd180b-a259-4ea1-9653-0937f6677953</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='driver_power_unit_join/expiration_date::popChooseDate::nm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;driver_power_unit_join\/expiration_date\:\:popChooseDate\:\:nm&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>386905c8-699b-4ce8-863f-49583c90e192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>driver_power_unit_join/expiration_date::popChooseDate::nm</value>
      <webElementGuid>cc793205-35a0-4f54-b080-e0d837eb45ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calNM</value>
      <webElementGuid>f2f55940-36ae-44a2-8fd0-e7e26fc1a517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>c64d7282-358e-4ab5-896d-bbaf3482d28a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>b694b6e2-8633-4abe-bb62-9f43027282bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;driver_power_unit_join/expiration_date::popChooseDate::nm&quot;)</value>
      <webElementGuid>3281589f-43de-4072-9b5b-9aa813b683f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Driver - Driver/iframe_PRAJYOT.DABHADEBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>e5a6af17-c5f2-42c4-91fa-aa2473ddabcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='driver_power_unit_join/expiration_date::popChooseDate::nm']</value>
      <webElementGuid>5d368c3b-cc68-4d46-a6dc-f823cdac3ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='driver_power_unit_join/expiration_date::popChooseDate']/tbody/tr/td/table/tbody/tr/td[4]/a</value>
      <webElementGuid>7541b1c1-02db-46fa-bdf7-ff6c6fbbfc8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[4]</value>
      <webElementGuid>1be7a62b-a830-4306-a3f8-7bc86b1952b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/table/tbody/tr/td[4]/a</value>
      <webElementGuid>2ee834d2-2bff-4cbc-b722-c2a3a2f070f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'driver_power_unit_join/expiration_date::popChooseDate::nm' and @href = 'javascript:void(0)']</value>
      <webElementGuid>ba5f9bde-0c59-48da-a8d4-1d8b8bb95900</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
