<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Wrap_pt1_FOr11_FONSr20_FOTsr10pt1r10AP4_7a9f1d</name>
   <tag></tag>
   <elementGuidId>c33d6685-8128-4ae8-aa5a-942011e6dcf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Create']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Create&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b06dbda2-3e72-4c5d-8c6d-3d8640eda3e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:_FOTsr1:0:pt1:r1:0:AP4:partyHierarchySearchResultsId:_ATp:create::icon</value>
      <webElementGuid>4d5a7459-0b22-47db-b3d0-617a2c9affab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/crmUI/images/applcore/fuseplus/patterns/func_add_16_hov.png</value>
      <webElementGuid>32f3519d-82d1-40c7-82be-ad2065582f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>ec020d95-b2e5-49df-91e9-6e073a5da3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>bf18d47c-ece9-44c1-96ee-284db02da961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1kd</value>
      <webElementGuid>d5da30af-0b75-4f96-b765-15dbe6c6d1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:_FOTsr1:0:pt1:r1:0:AP4:partyHierarchySearchResultsId:_ATp:create::icon&quot;)</value>
      <webElementGuid>cd43ae56-4c55-4ae6-97c1-c8c1426b4faf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='pt1:_FOr1:1:_FONSr2:0:_FOTsr1:0:pt1:r1:0:AP4:partyHierarchySearchResultsId:_ATp:create::icon']</value>
      <webElementGuid>4e952d24-ef87-49e1-a78f-6e09829c93c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pt1:_FOr1:1:_FONSr2:0:_FOTsr1:0:pt1:r1:0:AP4:partyHierarchySearchResultsId:_ATp:create']/a/img</value>
      <webElementGuid>1bfc14d8-7a59-485b-a0fa-27d440a8ac41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Create']</value>
      <webElementGuid>4d2edde0-34a5-48cd-9db2-d33910d7565c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>305c58fa-53ce-495b-80c3-84b9e12d33fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'pt1:_FOr1:1:_FONSr2:0:_FOTsr1:0:pt1:r1:0:AP4:partyHierarchySearchResultsId:_ATp:create::icon' and @src = '/crmUI/images/applcore/fuseplus/patterns/func_add_16_hov.png' and @title = 'Create' and @alt = 'Create']</value>
      <webElementGuid>34f13674-c46f-47af-baea-c8fb3742ec71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
