<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Primary Unit of Measure_pt1_FOr11_FONSr20_69a4ec</name>
   <tag></tag>
   <elementGuidId>b3f80425-ab19-4ae0-aab9-dc042126c026</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sprimf:0:primaryUomCodeDispId::lovIconId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Search: Primary Unit of Measure&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d05ef65-9b53-4876-a107-fe66c80082bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>cddf8cef-5df3-412a-9f90-f2983ed278cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1o4</value>
      <webElementGuid>7d726956-22b5-419b-bfd5-f028d1cb85fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sprimf:0:primaryUomCodeDispId::lovIconId</value>
      <webElementGuid>a2b2240b-4ec0-4cea-8551-df320548c5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search: Primary Unit of Measure</value>
      <webElementGuid>429a15da-6a11-466a-aa59-b3ba4c53aa48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sprimf:0:primaryUomCodeDispId::lovIconId&quot;)</value>
      <webElementGuid>c6000ee9-8229-4214-967f-d67cc3e5b83b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sprimf:0:primaryUomCodeDispId::lovIconId']</value>
      <webElementGuid>f89f49be-064e-4020-90e0-8e1580862b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sprimf:0:primaryUomCodeDispId::cntnrSpan']/span/a</value>
      <webElementGuid>8fae6ebc-df6a-4f8f-a632-65d3ca89193d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span/a</value>
      <webElementGuid>cf49fd83-7c55-40ed-bd32-913fc4bcedd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sprimf:0:primaryUomCodeDispId::lovIconId' and @title = 'Search: Primary Unit of Measure']</value>
      <webElementGuid>f4d334c4-5e02-4731-a054-42bdf8b293a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
