<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Product Type_pt1_FOr11_FONSr20MAt30pt_130a14</name>
   <tag></tag>
   <elementGuidId>d0fc49b8-c282-4a68-8e8a-ac27be25b73e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:r1:0:dynamicFormRight_productTypeItemEffBaseEO5_ATTRIBUTE_CHAR21::content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Product Type&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce1f062c-c174-4f8a-84cb-ec3e686bd9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:r1:0:dynamicFormRight_productTypeItemEffBaseEO5_ATTRIBUTE_CHAR21::content</value>
      <webElementGuid>5b80ae0e-7e9c-4be2-9e67-6497415437d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:r1:0:dynamicFormRight_productTypeItemEffBaseEO5_ATTRIBUTE_CHAR21</value>
      <webElementGuid>29a5e000-2111-45dc-b5a0-0b7f45e89983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x25</value>
      <webElementGuid>7fdbebd9-c577-4cda-9206-60668c35a24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>f3c51d8c-7efb-4ba8-b2d5-3264f2b8be15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>50fb46e3-ea4f-4f9e-84bd-91a09c242455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4000</value>
      <webElementGuid>5158fcbf-aa76-4717-90de-90bc75fbe491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a75d02ec-8896-48b8-b5df-4dcc543b667c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>85b841d7-cf6d-4273-babb-c7869e4c0925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:r1:0:dynamicFormRight_productTypeItemEffBaseEO5_ATTRIBUTE_CHAR21::content&quot;)</value>
      <webElementGuid>9f5e13d4-df96-4bd6-9ffa-3ec03966e1a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:r1:0:dynamicFormRight_productTypeItemEffBaseEO5_ATTRIBUTE_CHAR21::content']</value>
      <webElementGuid>c40fd6d5-e404-43b5-96b3-d81ed1e88d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:r1:0:dynamicFormRight_productTypeItemEffBaseEO5_ATTRIBUTE_CHAR21']/td[2]/input</value>
      <webElementGuid>803870fa-4bfd-4245-af19-d8f32c33a851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/table/tbody/tr/td/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>d332d850-b1d6-4348-a1b4-3b89c629e481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:r1:0:dynamicFormRight_productTypeItemEffBaseEO5_ATTRIBUTE_CHAR21::content' and @name = 'pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:r1:0:dynamicFormRight_productTypeItemEffBaseEO5_ATTRIBUTE_CHAR21' and @type = 'text']</value>
      <webElementGuid>45fbb9b6-b4c3-4e4d-b2ca-f1badecf3985</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
