<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Run</name>
   <tag></tag>
   <elementGuidId>432987e8-7451-4c1a-b628-d62dd47ebd4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_report_grid']/tbody/tr[5]/td[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;BILL_OF_LADING This is the primary shipping document which transfers control of the shipment from the shipper to the carrier. BXC Run Schedule&quot;i] >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>35072889-9165-4933-b292-69185e2ac9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>window.status='';return true;</value>
      <webElementGuid>05cecaff-86ea-4eda-aabb-9cd1bc4ff36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.report.ReportParameterServlet/1751387291590?bcKey=MTc1MTM4NzI5MTU5MDow&amp;report_gid=BXC.BILL_OF_LADING&amp;DB=OLTP</value>
      <webElementGuid>ad1caac7-931a-447f-a73c-8e58a73ad669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Run</value>
      <webElementGuid>14007223-7f90-417b-8add-c07750f0ea13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_report_grid&quot;)/tbody[1]/tr[@class=&quot;rowOdd&quot;]/td[@class=&quot;gridBodyCell&quot;]/a[1]</value>
      <webElementGuid>0a236f2c-4b92-4357-b3fc-859c7663d74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Reports/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>c2d36a3b-b6b7-4258-9c57-9ea991cee8ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_report_grid']/tbody/tr[5]/td[4]/a</value>
      <webElementGuid>746d4441-39e9-4b81-8af9-a1202cd7d094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Run')])[3]</value>
      <webElementGuid>e9c127ad-3a09-49a8-a177-a6174f7ab527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BXC'])[1]/following::a[1]</value>
      <webElementGuid>14dfc898-15da-4e3d-b7a3-46cb0f3402dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BILL_OF_LADING'])[1]/following::a[1]</value>
      <webElementGuid>304d712e-4d50-4960-be04-18bfe03e7a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule'])[3]/preceding::a[1]</value>
      <webElementGuid>fc836573-019e-48df-94e5-bdcbcf328a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipment Detail Report'])[1]/preceding::a[2]</value>
      <webElementGuid>50a06839-6624-47a7-8bda-f6ebc9e37ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/GC3/glog.webserver.report.ReportParameterServlet/1751387291590?bcKey=MTc1MTM4NzI5MTU5MDow&amp;report_gid=BXC.BILL_OF_LADING&amp;DB=OLTP')]</value>
      <webElementGuid>22638994-1645-4d98-b5b9-7b8342d9d3ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[4]/a</value>
      <webElementGuid>9c0b83e7-12bf-489e-8907-8bb6d33c6f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/GC3/glog.webserver.report.ReportParameterServlet/1751387291590?bcKey=MTc1MTM4NzI5MTU5MDow&amp;report_gid=BXC.BILL_OF_LADING&amp;DB=OLTP' and (text() = 'Run' or . = 'Run')]</value>
      <webElementGuid>ab830da3-6476-491b-a7a6-8f7041e5a57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UNRESOLVED INVOICES'])[1]/preceding::a[2]</value>
      <webElementGuid>862bf6b7-c420-40b1-ad24-8c240c360e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/GC3/glog.webserver.report.ReportParameterServlet/1745496796288?bcKey=MTc0NTQ5Njc5NjI4ODow&amp;report_gid=BXC.BILL_OF_LADING&amp;DB=OLTP')]</value>
      <webElementGuid>e3d13a8f-5c83-4130-98ea-75b2a305d0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/GC3/glog.webserver.report.ReportParameterServlet/1745496796288?bcKey=MTc0NTQ5Njc5NjI4ODow&amp;report_gid=BXC.BILL_OF_LADING&amp;DB=OLTP' and (text() = 'Run' or . = 'Run')]</value>
      <webElementGuid>a86b3757-4ea7-42ae-a615-15a47258c40b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
