<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</name>
   <tag></tag>
   <elementGuidId>920a2f1d-7491-4c02-b49d-e594d1b978ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainIFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainIFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mainIFrame</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>09983073-a446-48d2-99c8-39baadc01e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainIFrame</value>
      <webElementGuid>abc92d31-9d0e-463d-b9ed-188dc41927b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oj-web-applayout-content-nopad</value>
      <webElementGuid>03f3d85a-9574-4133-89ab-24614879d8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>mainIFrameOnLoad()</value>
      <webElementGuid>7ac1352d-5f61-457a-a5c1-76a1cae9e90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr : {src: IFRAME_URL}</value>
      <webElementGuid>4e5843e1-228e-4f40-a64d-0faae48415c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.report.ViewReportGroupServlet?bcKey=new&amp;type=OTHER&amp;null=Y</value>
      <webElementGuid>9940e9b3-0487-458f-8a0a-1cf610ff9fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainIFrame&quot;)</value>
      <webElementGuid>a02f2bc9-4f41-40bd-80bc-184b72f0db6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainIFrame']</value>
      <webElementGuid>7fa9613d-8af2-4580-a0f1-a0c0ad4e33ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//oj-module[@id='mainModule']/iframe</value>
      <webElementGuid>6178a4bc-ed9a-40b5-9aa7-3119ab117b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4951dcaa-50c0-4ef5-984a-758ca0d469c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'mainIFrame' and @src = '/GC3/glog.webserver.report.ViewReportGroupServlet?bcKey=new&amp;type=OTHER&amp;null=Y']</value>
      <webElementGuid>aadf21ec-8a33-4d29-bf54-23cc12350824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
