<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Move__FOpt1_FOr10_FONSr20MAt20AppTe0selec_dd3ca8</name>
   <tag></tag>
   <elementGuidId>f5a6e570-45e8-489e-89e7-15cfed5ef2d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAt2:0:AppTe:0:selectManyShuttle1::moveall']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Move all items to: Selected List&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f9b82cc9-33e9-4623-b412-b3bcda94ccba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>311faa77-6ff4-468b-a307-e52cdc56b5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>01a80646-60df-43f5-86f2-a195c530482d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.focus();return false</value>
      <webElementGuid>2a9a0d71-059d-4e19-aba6-f2ae9148b699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1ff</value>
      <webElementGuid>a70e4b30-090c-42c0-9b40-28ebfd425229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAt2:0:AppTe:0:selectManyShuttle1::moveall</value>
      <webElementGuid>87556928-149a-440b-95c2-80de1a96954e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Move all items to: Selected List</value>
      <webElementGuid>87fbec47-22b1-4563-913d-b640c3ff0ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAt2:0:AppTe:0:selectManyShuttle1::moveall&quot;)</value>
      <webElementGuid>cf2c7cf4-fee3-4f21-964c-02a40c859cf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAt2:0:AppTe:0:selectManyShuttle1::moveall']</value>
      <webElementGuid>9939a643-1713-42f5-ada8-508e0fbe9b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAt2:0:AppTe:0:selectManyShuttle1::moveDiv']/table[2]/tbody/tr/td/div/a</value>
      <webElementGuid>5dfb91ea-10a8-4177-af10-a4d64bb7a0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[31]</value>
      <webElementGuid>7a77a68c-d44c-4771-8034-9b326c37ea56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/table[2]/tbody/tr/td/div/a</value>
      <webElementGuid>fd86a66f-4cfd-4bd2-8a00-0ae3e083651d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = '_FOpt1:_FOr1:0:_FONSr2:0:MAt2:0:AppTe:0:selectManyShuttle1::moveall' and @title = 'Move all items to: Selected List']</value>
      <webElementGuid>3a324ea5-1fd5-4689-b617-ad05f92438b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
