<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NMFC Class ID__FOpt1_FOr10_FONSr20MAt30pt_af3131</name>
   <tag></tag>
   <elementGuidId>542b43dd-3b9c-45c7-8435-2a7f4c0a5590</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[2]/table/tbody/tr[2]/td[2]/table/tbody/tr/td/table/tbody/tr/td[2]/table/tbody/tr/td/span/span/span/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;NMFC Class ID NMFC Class ID Search: Autocompletes on TAB&quot;s] >> internal:attr=[title=&quot;Search: &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>974c351b-db71-43cb-9ce5-ca7fbc65a8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ca458cc6-c7e2-4edf-9070-c1fbf758761b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1o4</value>
      <webElementGuid>a417b8bb-9081-4016-b638-7e115486c3fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:1:CTXRNj_ItemBluelinxPrivateVOOTM__Attributes:0:nmfcClassId::lovIconId</value>
      <webElementGuid>ac0df8ce-543a-4d0f-8fff-4ec333881793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search: </value>
      <webElementGuid>f426cac1-410b-4327-99ab-97b9ffa6dbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:1:CTXRNj_ItemBluelinxPrivateVOOTM__Attributes:0:nmfcClassId::lovIconId&quot;)</value>
      <webElementGuid>937be958-e7e2-47a3-9db4-fe80eaeda0fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:1:CTXRNj_ItemBluelinxPrivateVOOTM__Attributes:0:nmfcClassId::lovIconId']</value>
      <webElementGuid>780bb948-7ae2-4cb0-9722-283e811a2772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:1:CTXRNj_ItemBluelinxPrivateVOOTM__Attributes:0:nmfcClassId::cntnrSpan']/span/a</value>
      <webElementGuid>67a08594-9204-44b2-a22f-331c6cf51734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[2]/td[2]/table/tbody/tr/td/table/tbody/tr/td[2]/table/tbody/tr/td/span/span/span/span/a</value>
      <webElementGuid>3496d618-1afe-4bdf-9b14-6cb4bff1edec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:1:CTXRNj_ItemBluelinxPrivateVOOTM__Attributes:0:nmfcClassId::lovIconId' and @title = 'Search: ']</value>
      <webElementGuid>6ce40c8a-87bb-4f54-a776-a9c3359b234e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr/td/table/tbody/tr/td[2]/table/tbody/tr/td/span/span/span/span/a</value>
      <webElementGuid>ebb1693b-0c2a-4d40-8a87-c8a950c18e7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
