<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Unit__FOpt1_FOr10_FONSr20MAt30pt1ap1sspec_430135</name>
   <tag></tag>
   <elementGuidId>0472bfb6-b745-4611-b394-d4dd30fd1aad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[2]/table/tbody/tr[2]/td[2]/table/tbody/tr/td/span/span/span/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Unit Unit Search: Unit Autocompletes on TAB Unit Volume&quot;s] >> internal:attr=[title=&quot;Search: Unit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dd219cef-a581-4c47-84ee-36d7b34056ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7a5776c6-39b2-4260-9627-84c8c302cb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1o4</value>
      <webElementGuid>149e655e-a92a-49a7-b40d-d54fb66de81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:4:volumeUomCodeId::lovIconId</value>
      <webElementGuid>dff61126-f14b-42a2-ae72-c42f54b6200b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search: Unit</value>
      <webElementGuid>ee088019-2bac-472b-b3fc-7c61c261e9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:4:volumeUomCodeId::lovIconId&quot;)</value>
      <webElementGuid>38528593-a993-46ef-bfbd-9bf0f180d7b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:4:volumeUomCodeId::lovIconId']</value>
      <webElementGuid>545522fa-016d-4db1-8293-f02dad2406a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:4:volumeUomCodeId::cntnrSpan']/span/a</value>
      <webElementGuid>8092ae5e-8c31-4ce6-bc48-2a217170e691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[2]/td[2]/table/tbody/tr/td/span/span/span/span/a</value>
      <webElementGuid>48ea58f4-6ce5-4429-ae6d-54283973b705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:4:volumeUomCodeId::lovIconId' and @title = 'Search: Unit']</value>
      <webElementGuid>1bcc5b2c-e9e8-4efc-8d62-66bc2aae6d4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
