<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Product Type__FOpt1_FOr10_FONSr20MAt3_f8140b</name>
   <tag></tag>
   <elementGuidId>d867bd82-86dd-4dd0-84f3-095291420baa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'ATTRIBUTE_CHAR21')]&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Product Type&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0ca759a-2d57-458c-87a7-a54c230e8ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:r1:0:dynamicFormLeft_productTypeItemEffBaseEO6_ATTRIBUTE_CHAR21::content</value>
      <webElementGuid>cbbab599-dbee-4860-b001-0672cb025153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:r1:0:dynamicFormLeft_productTypeItemEffBaseEO6_ATTRIBUTE_CHAR21</value>
      <webElementGuid>8bb48b81-8bbe-4a78-a70f-ccd3f9007707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x25</value>
      <webElementGuid>3d581b2e-40bd-4c7b-8b8b-95eef1af499e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>f5632012-1ede-47cc-8d18-50a0dcdc8b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d8c48935-bc65-4975-a4be-ff6b51d68c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4000</value>
      <webElementGuid>6ff9d818-ba72-449a-8473-04163c3043ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0cfce90-ef4f-40f2-a81b-2d685f83e64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9f1d50bf-aafb-495d-92ec-d4f80f50777a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:r1:0:dynamicFormLeft_productTypeItemEffBaseEO6_ATTRIBUTE_CHAR21::content&quot;)</value>
      <webElementGuid>a1b7f8e7-e11b-444b-b036-88b632a900de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:r1:0:dynamicFormLeft_productTypeItemEffBaseEO6_ATTRIBUTE_CHAR21::content']</value>
      <webElementGuid>2215efdd-e213-4b3d-bf63-2b1dc0d0cf90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:r1:0:dynamicFormLeft_productTypeItemEffBaseEO6_ATTRIBUTE_CHAR21']/td[2]/input</value>
      <webElementGuid>ed462fe4-209b-44e2-8fb6-f14df41e4266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>106dee73-500f-4092-bdad-a54c6277d98a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:r1:0:dynamicFormLeft_productTypeItemEffBaseEO6_ATTRIBUTE_CHAR21::content' and @name = '_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:r1:0:dynamicFormLeft_productTypeItemEffBaseEO6_ATTRIBUTE_CHAR21' and @type = 'text']</value>
      <webElementGuid>6a77e155-6734-4a7b-bb75-3ce35d4cc16c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
