<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Based on modelBased on sourcingItems_2f20aa</name>
   <tag></tag>
   <elementGuidId>41bf0ff0-37d0-496a-8bc5-9abdfb7a328c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:0:ItemBOM:0:selectOneChoice3::content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Create Configured Item&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>530d1e19-0591-404b-96c3-37ef3cfabac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:0:ItemBOM:0:selectOneChoice3::content</value>
      <webElementGuid>672dac31-6ebb-48eb-81ee-2c0cabeaa557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:0:ItemBOM:0:selectOneChoice3</value>
      <webElementGuid>9fae7d30-8b2f-49c5-963d-64d866c752cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x2h</value>
      <webElementGuid>a73ee198-c8a1-4bc1-9529-4e534158e55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_afov</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>658c0b0d-58df-45e1-8865-99d27afbeccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Based on modelBased on sourcingItems based on model, structures based on sourcing</value>
      <webElementGuid>aa0e025f-bf32-461a-874e-cf02730d768e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:0:ItemBOM:0:selectOneChoice3::content&quot;)</value>
      <webElementGuid>bd6ccc08-6560-4d51-91fc-07dd20d63835</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:0:ItemBOM:0:selectOneChoice3::content']</value>
      <webElementGuid>1008ac10-a6cd-4913-9ffa-19f9116ba3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:0:ItemBOM:0:selectOneChoice3']/select</value>
      <webElementGuid>654ba7f7-dbc4-4026-873c-ec91ad429109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Configured Item'])[1]/following::select[1]</value>
      <webElementGuid>b0e19153-fa42-40d7-8d62-35b0548dcf88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Structure Item Type'])[1]/following::select[2]</value>
      <webElementGuid>4211de63-216c-4b7d-a0bc-a644ba995c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configurator Model Type'])[1]/preceding::select[1]</value>
      <webElementGuid>9db122cc-00cf-4dab-a7a7-85d802e0c6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Effectivity Control'])[1]/preceding::select[2]</value>
      <webElementGuid>d54dc441-4b82-4a11-9a35-946be8e9ab08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/table/tbody/tr/td/table/tbody/tr[3]/td[2]/table/tbody/tr/td/span/select</value>
      <webElementGuid>bab9a6d4-d449-435a-ad58-de35742ad07e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:0:ItemBOM:0:selectOneChoice3::content' and @name = '_FOpt1:_FOr1:0:_FONSr2:0:MAt3:0:pt1:ap1:sspecf:1:dynReg:0:ItemBOM:0:selectOneChoice3' and (text() = 'Based on modelBased on sourcingItems based on model, structures based on sourcing' or . = 'Based on modelBased on sourcingItems based on model, structures based on sourcing')]</value>
      <webElementGuid>55e83aa9-6a00-4459-95e3-75420ca8fd90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
