<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BXC.TESTSHP01234</name>
   <tag></tag>
   <elementGuidId>30940ef9-5f6d-405a-baeb-a1185d9c04c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='rgSGSec.2.1.1.4.k']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;BXC.TESTSHP01234&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>999cf6b9-d238-403f-869e-696cff958341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rgSGSec.2.1.1.4.k</value>
      <webElementGuid>58811cb5-1669-411a-9500-20bbca8bc602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0e3a8da9-6942-4950-a823-8e2b9c699aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>6a177023-aa8a-4930-8ce9-f8e91e30973d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OpenTarget('/GC3/ShipmentCustManagement?bcKey=MTc1MDM1Nzg4NDQ2NDox&amp;manager_layout_gid=SHIPMENT&amp;type=B&amp;pk=BXC.TESTSHP01234&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=edit'); return addToRecentlyViewed(finderSetGid,'BXC.TESTSHP01234', 'EDIT');</value>
      <webElementGuid>e87160ea-edcc-4ae6-a28c-86f4b9a4bcfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BXC.TESTSHP01234</value>
      <webElementGuid>e6e4d7d5-dbf6-4a90-b0c8-f2f1864b683f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rgSGSec.2.1.1.4.k&quot;)</value>
      <webElementGuid>2f6f6616-5116-4f69-8ba5-75924f986533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Buy Shipments Result/iframe_PRAJYOT.DABHADEBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>6750ce80-3b81-40dc-9e47-295457d29f9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='rgSGSec.2.1.1.4.k']</value>
      <webElementGuid>77910775-d22d-4a83-b7d1-67626b39100e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rgSGSec.2.1.1.4']/a</value>
      <webElementGuid>ca589830-8b7d-4ad9-873e-3d5b3bd1816d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BXC.TESTSHP01234')]</value>
      <webElementGuid>b0b3547e-ce5f-4172-9116-e13b2682df32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[2]/following::a[2]</value>
      <webElementGuid>9cced9db-69f2-4589-8401-dd25e7d0c07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Domain Name'])[1]/following::a[3]</value>
      <webElementGuid>74ad86c8-ae68-4e3a-924c-0dcc4231a0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TESTSHP01234'])[1]/preceding::a[1]</value>
      <webElementGuid>1328b2fb-972d-4407-8c09-bcffb7e34ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RAIL'])[1]/preceding::a[1]</value>
      <webElementGuid>54c83e2a-7292-4cca-b234-a20c4d6bd550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BXC.TESTSHP01234']/parent::*</value>
      <webElementGuid>dc9302f7-fbc7-477f-b254-c1776bd33a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[5]</value>
      <webElementGuid>05a15d0f-b693-44bf-b183-39407c58037a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>fbc9714c-6eb7-4472-86f9-30ef2b86c67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'rgSGSec.2.1.1.4.k' and @href = 'javascript:void(0);' and (text() = 'BXC.TESTSHP01234' or . = 'BXC.TESTSHP01234')]</value>
      <webElementGuid>40b0651f-77c6-4899-8f2a-f721b923d4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TESTSHP01234'])[2]/preceding::a[1]</value>
      <webElementGuid>f444e550-e613-475b-995e-5abbbef8ea52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
