<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Shipment Tracking Events</name>
   <tag></tag>
   <elementGuidId>1521c6f5-a221-4610-989b-920f0c52333f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='actionTree.1_8_5_7.k']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;View Shipment Tracking Events&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c176f492-d9b9-4217-a385-caaf9cf3adf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionTree.1_8_5_7.k</value>
      <webElementGuid>6932ec00-aa9b-4b5b-aae6-e4c60e828c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fae16858-3a02-41b0-8a5f-82a9ce2ed1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:executeAction('\x2FGC3\x2Fglog.webserver.util.QueryResponseServlet\x2F1750232726854\x3FbcKey\x3DMTc1MDIzMjcyNjg1NDox\x26action_name\x3Dview_events\x26finder_set_gid\x3DBUY_SHIPMENT')</value>
      <webElementGuid>5360c3fc-ff1e-4f61-8530-e2db7b35497a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Shipment Tracking Events</value>
      <webElementGuid>30b94b1c-afe2-441d-8f96-d6e3f4058507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionTree.1_8_5_7.k&quot;)</value>
      <webElementGuid>db846d08-cc83-4d98-9005-528ca9454c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Buy Shipments Result/iframe_concat(id(, , actionFrame, , ))_actionFrame</value>
      <webElementGuid>b4fa71f5-4b85-4bf2-99ae-53192d0c9420</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='actionTree.1_8_5_7.k']</value>
      <webElementGuid>d35ff77f-3c05-41da-88c6-1581c2730b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='actionTree.1_8_5_7.l']/a</value>
      <webElementGuid>5cb270a7-51a4-4d2c-8b98-aaa239363515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Shipment Tracking Events')]</value>
      <webElementGuid>78222554-fb25-424b-bd7a-65c3557d5161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Events by Tracking Number'])[1]/following::a[1]</value>
      <webElementGuid>3f6b3405-5b44-447a-ab06-cbe66fd2bcb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roll Back Sighting'])[1]/following::a[2]</value>
      <webElementGuid>1007e2bb-2859-4dc5-b7b6-339c428e27ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Groups and Charges'])[1]/preceding::a[1]</value>
      <webElementGuid>8859d1cb-844f-46c4-ba89-b2c019a34029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Partial Shipments to Group'])[1]/preceding::a[1]</value>
      <webElementGuid>f569b938-ca31-4656-9b34-e2ceaba40092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Shipment Tracking Events']/parent::*</value>
      <webElementGuid>3168a754-961c-4838-8996-4530cbb6cc1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:executeAction('\x2FGC3\x2Fglog.webserver.util.QueryResponseServlet\x2F1750232726854\x3FbcKey\x3DMTc1MDIzMjcyNjg1NDox\x26action_name\x3Dview_events\x26finder_set_gid\x3DBUY_SHIPMENT')&quot;)]</value>
      <webElementGuid>f306dca4-6a13-43b6-b495-31d1f7138eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/div/table/tbody/tr[7]/td/span[2]/a</value>
      <webElementGuid>a4f5fb4e-6bde-4e02-a79c-5a85cc2461de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'actionTree.1_8_5_7.k' and @href = concat(&quot;javascript:executeAction(&quot; , &quot;'&quot; , &quot;\x2FGC3\x2Fglog.webserver.util.QueryResponseServlet\x2F1750232726854\x3FbcKey\x3DMTc1MDIzMjcyNjg1NDox\x26action_name\x3Dview_events\x26finder_set_gid\x3DBUY_SHIPMENT&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'View Shipment Tracking Events' or . = 'View Shipment Tracking Events')]</value>
      <webElementGuid>7ce99307-ba4e-44f0-9eaf-0ef313bb2b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:executeAction('\x2FGC3\x2Fglog.webserver.util.QueryResponseServlet\x2F1749222715077\x3FbcKey\x3DMTc0OTIyMjcxNTA3Nzox\x26action_name\x3Dview_events\x26finder_set_gid\x3DBUY_SHIPMENT')&quot;)]</value>
      <webElementGuid>17372457-4c0b-4c12-a4ae-633daed07d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'actionTree.1_8_5_7.k' and @href = concat(&quot;javascript:executeAction(&quot; , &quot;'&quot; , &quot;\x2FGC3\x2Fglog.webserver.util.QueryResponseServlet\x2F1749222715077\x3FbcKey\x3DMTc0OTIyMjcxNTA3Nzox\x26action_name\x3Dview_events\x26finder_set_gid\x3DBUY_SHIPMENT&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'View Shipment Tracking Events' or . = 'View Shipment Tracking Events')]</value>
      <webElementGuid>dc462777-425d-4914-8cf1-c77f47d97a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:executeAction('\x2FGC3\x2Fglog.webserver.util.QueryResponseServlet\x2F1748261232310\x3FbcKey\x3DMTc0ODI2MTIzMjMxMTox\x26action_name\x3Dview_events\x26finder_set_gid\x3DBUY_SHIPMENT')&quot;)]</value>
      <webElementGuid>a1a3b2a9-5f63-492a-83f2-706574d573fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'actionTree.1_8_5_7.k' and @href = concat(&quot;javascript:executeAction(&quot; , &quot;'&quot; , &quot;\x2FGC3\x2Fglog.webserver.util.QueryResponseServlet\x2F1748261232310\x3FbcKey\x3DMTc0ODI2MTIzMjMxMTox\x26action_name\x3Dview_events\x26finder_set_gid\x3DBUY_SHIPMENT&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'View Shipment Tracking Events' or . = 'View Shipment Tracking Events')]</value>
      <webElementGuid>dd4ba70f-2e95-4dbd-be1b-f06b8ae264df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:executeAction('\x2FGC3\x2Fglog.webserver.util.QueryResponseServlet\x2F1748260973420\x3FbcKey\x3DMTc0ODI2MDk3MzQyMjox\x26action_name\x3Dview_events\x26finder_set_gid\x3DBUY_SHIPMENT')&quot;)]</value>
      <webElementGuid>0b5ad8fb-f543-455a-a4b1-33d57e07f3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'actionTree.1_8_5_7.k' and @href = concat(&quot;javascript:executeAction(&quot; , &quot;'&quot; , &quot;\x2FGC3\x2Fglog.webserver.util.QueryResponseServlet\x2F1748260973420\x3FbcKey\x3DMTc0ODI2MDk3MzQyMjox\x26action_name\x3Dview_events\x26finder_set_gid\x3DBUY_SHIPMENT&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'View Shipment Tracking Events' or . = 'View Shipment Tracking Events')]</value>
      <webElementGuid>500ad480-07b0-49f3-a71b-7a3b0d45d6dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
