<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View All Spot Bid Options</name>
   <tag></tag>
   <elementGuidId>291654fc-a19a-437f-98ac-51248f56bede</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='actionTree.1_8_8_7.k']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;View All Spot Bid Options&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b1d0a868-dd7e-4c02-b90c-413fc9909630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionTree.1_8_8_7.k</value>
      <webElementGuid>ab78861b-1ec5-465d-a25c-8a2c9a3de16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6a4af7ad-23c3-4c81-b564-ec1054f568c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:executeAction('\x2FGC3\x2Fglog.webserver.util.QueryResponseServlet\x2F1747214427624\x3FbcKey\x3DMTc0NzIxNDQyNzYyNDox\x26action_name\x3Dview_all_spot_bid_options\x26finder_set_gid\x3DBUY_SHIPMENT')</value>
      <webElementGuid>aeaa3db6-06f2-41d2-8484-49f92bd6664e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View All Spot Bid Options</value>
      <webElementGuid>bdb5c32a-cdb1-4397-8b3a-4f9f3fe5d01b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionTree.1_8_8_7.k&quot;)</value>
      <webElementGuid>4ae71645-61ac-45e6-b7ae-b454e5fa12e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Buy Shipments Result/iframe_concat(id(, , actionFrame, , ))_actionFrame</value>
      <webElementGuid>ddc53716-17db-4fd8-a38f-5392de8b1e11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='actionTree.1_8_8_7.k']</value>
      <webElementGuid>d8d35de1-bed2-4f30-a38f-265fb3fb7e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='actionTree.1_8_8_7.l']/a</value>
      <webElementGuid>05ffffe8-2964-49f3-bb8d-d86446c6a86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View All Spot Bid Options')]</value>
      <webElementGuid>a961d43a-a72e-4489-94f4-76ba9f606f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Open Tender'])[1]/following::a[1]</value>
      <webElementGuid>1c3d22be-ff7f-4676-9660-02ad3db30bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spot Bid Tender'])[1]/following::a[2]</value>
      <webElementGuid>f996eb82-5253-452a-ac8f-c6768407f5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Withdraw Broadcasted Tender'])[1]/preceding::a[1]</value>
      <webElementGuid>03edcac8-4815-48c1-a93f-65ae74316ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Withdraw Spot Bid Tender'])[1]/preceding::a[2]</value>
      <webElementGuid>f4abdc0f-f1ee-48bf-aea0-27d871e895d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View All Spot Bid Options']/parent::*</value>
      <webElementGuid>d36093dd-95b6-49e9-aa23-526373f5eaca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:executeAction('\x2FGC3\x2Fglog.webserver.util.QueryResponseServlet\x2F1747214427624\x3FbcKey\x3DMTc0NzIxNDQyNzYyNDox\x26action_name\x3Dview_all_spot_bid_options\x26finder_set_gid\x3DBUY_SHIPMENT')&quot;)]</value>
      <webElementGuid>440c80fe-5b3f-40cf-a649-3e8be7b394c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[16]/td/div/table/tbody/tr[7]/td/span[2]/a</value>
      <webElementGuid>75410df6-d1a3-473a-b275-0d50ccacef04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'actionTree.1_8_8_7.k' and @href = concat(&quot;javascript:executeAction(&quot; , &quot;'&quot; , &quot;\x2FGC3\x2Fglog.webserver.util.QueryResponseServlet\x2F1747214427624\x3FbcKey\x3DMTc0NzIxNDQyNzYyNDox\x26action_name\x3Dview_all_spot_bid_options\x26finder_set_gid\x3DBUY_SHIPMENT&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'View All Spot Bid Options' or . = 'View All Spot Bid Options')]</value>
      <webElementGuid>bf1db1e1-cbdc-4361-8f1d-f3dc0015414e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
