<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , actionFrame, , ))_actionFrame (2)</name>
   <tag></tag>
   <elementGuidId>0457bb2b-447a-46c6-bb02-96e7a28ee93e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='actionFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#actionFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;actionFrame&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>bf652d64-b8ff-40aa-86b4-4a43c40c05eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actionFrame</value>
      <webElementGuid>3595067e-20fd-4119-a24c-83a1d329317b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionFrame</value>
      <webElementGuid>5863f8d8-e9a9-4e56-b794-69b1b78bab1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iWinFrame</value>
      <webElementGuid>eaffda20-5d6c-4a9c-b89e-5d7fc6c555f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a03f9a0d-2530-4c2f-b21b-5ad0db2ff5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>e3d8da4a-d1a4-4d76-8618-ee13601989ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.finder.ActionServlet/1748958602462?bcKey=MTc0ODk1ODYwMjEwMzow&amp;query_name=glog.server.query.shipment.BuyShipmentQuery&amp;finder_set_gid=BUY_SHIPMENT</value>
      <webElementGuid>8c28e5d7-7022-477d-b8c4-1f241845cd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pageloaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>051c8eaa-b608-4da1-bd9c-4683fc6be797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>actionmenucallingwinname</name>
      <type>Main</type>
      <value>mainBody</value>
      <webElementGuid>fc193175-ce5d-45d8-ab7b-186eca906343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionFrame&quot;)</value>
      <webElementGuid>e2bb00b7-befb-46c2-af30-8c7c85a44674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Buy Shipments Result/iframe_mainBody_1</value>
      <webElementGuid>fe35b298-58b4-422a-9249-82de2174c272</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='actionFrame']</value>
      <webElementGuid>318efe7f-45e9-4671-b800-f807255c2c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/iframe</value>
      <webElementGuid>f10daebd-2ea0-474d-9e4c-fc20c2da1314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'actionFrame' and @id = 'actionFrame' and @src = '/GC3/glog.webserver.finder.ActionServlet/1748958602462?bcKey=MTc0ODk1ODYwMjEwMzow&amp;query_name=glog.server.query.shipment.BuyShipmentQuery&amp;finder_set_gid=BUY_SHIPMENT']</value>
      <webElementGuid>34a232e3-d05a-4a1b-a784-f0864d25f1a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
