<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__img_BXC.8000</name>
   <tag></tag>
   <elementGuidId>cd9ebde2-2ed0-447a-b7c0-b841a57abb7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_BXC.6007']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;BXC.6007 Favorites&quot;i >> internal:role=link[name=&quot;Add To Favorites&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>27db0091-dbf9-403a-94ea-e89b094e71cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Add To Favorites</value>
      <webElementGuid>435e087d-8616-475b-b92b-1e3254d128a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/themes/themesalta/func_starempty_16_ena.png</value>
      <webElementGuid>28f76c62-3137-4b04-a5e5-5afa8be5ae55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_BXC.6007</value>
      <webElementGuid>7ddb2cb8-85d5-4898-b72e-e03fa284d8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add To Favorites</value>
      <webElementGuid>d0e901ea-13ea-4a6c-a170-e4163dff3e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_BXC.6007&quot;)</value>
      <webElementGuid>1c1e879c-2b91-4ffc-b191-d70b3559748d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Buy Shipments Result/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>a19cb5b8-cb39-4a11-9cc4-38d9d9e3eca9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_BXC.6007']</value>
      <webElementGuid>9eb9bffa-b5a7-4165-b54e-e214892e7a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='BXC.6007']/img</value>
      <webElementGuid>337d1f65-8e72-4f6e-8c81-dba8664056f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Add To Favorites']</value>
      <webElementGuid>6d5d823b-ee10-42db-bd51-7f093f7e0375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/img</value>
      <webElementGuid>80b5ab0a-990f-4817-94b9-c656e4fd6b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Add To Favorites' and @src = '/images/themes/themesalta/func_starempty_16_ena.png' and @id = 'img_BXC.6007' and @title = 'Add To Favorites']</value>
      <webElementGuid>6862d30d-3d77-406f-8c31-1ac1ad07e145</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
