<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Domain Name_Selected (2)</name>
   <tag></tag>
   <elementGuidId>03e6c642-1199-4596-bb1d-066cf923ba01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Selected&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Selected']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;BXC.TESTSHP01234&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f6485cd-4edf-42aa-ae80-0299f2908b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>BXC.TESTSHP01234</value>
      <webElementGuid>5d6f2b3c-f40e-445d-9e77-7c6268e11659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e941f2b1-a0ed-4cd8-999c-041f9600166b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>resultGrid.selectRow(this);handleSelectionOnServer(finderSetGid, callerID,'BXC.TESTSHP01234', this)</value>
      <webElementGuid>48c02619-38f7-410c-96fe-fb911ab1f108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BXC.TESTSHP01234</value>
      <webElementGuid>06d3e970-1ff8-452d-808d-8b29c7ff1897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>00b62261-b0ed-4eef-b6e7-371b6743f5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Selected</value>
      <webElementGuid>02a4db1e-4c08-4a29-9b14-4a9234dd4654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sgBodyCheck</value>
      <webElementGuid>0880b8dd-e239-40a7-af60-6d4613b68549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rgSGSec.2.1.1.1&quot;)/input[@class=&quot;sgBodyCheck&quot;]</value>
      <webElementGuid>ae49bb33-84cc-43a5-a508-95e203eea272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Buy Shipments Result/iframe_PRAJYOT.DABHADEBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>5b6f5549-b330-4a98-8b44-9df05f8dc8b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Selected']</value>
      <webElementGuid>9e378bb7-1b5b-4dd0-b03f-eb1869c3cee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rgSGSec.2.1.1.1']/input</value>
      <webElementGuid>ccbfe32e-50ea-4b33-82c3-ce43d26038e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>5aa417c9-8758-4f2f-b287-ae3c2672d5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'Selected']</value>
      <webElementGuid>e0a6729f-0e5a-494c-a89f-a32a8c341368</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
