<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_WhiteGreenYellowRedBlueOrange</name>
   <tag></tag>
   <elementGuidId>e7bc1286-9693-47b1-9595-d7e13fec5ea9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='order_release/indicator']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;order_release/indicator&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Indicator&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>549320a5-8043-4b27-9ba1-3c31b7e5c1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Indicator</value>
      <webElementGuid>aac12930-b285-41ba-9e07-792b9afcbf92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>showimage(this.options[this.selectedIndex].value)</value>
      <webElementGuid>848093b4-4f32-4c74-a67c-efd935b726e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_release/indicator</value>
      <webElementGuid>e958f8fe-90a3-4d11-ab6e-faab5ba4b1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WhiteGreenYellowRedBlueOrange</value>
      <webElementGuid>82b65cf4-e787-440b-b796-470c43d8bb7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyDataDiv&quot;)/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;bodySectInCont w100&quot;]/tbody[1]/tr[4]/td[1]/div[@class=&quot;fieldCont&quot;]/span[@class=&quot;queryCtlCont&quot;]/select[1]</value>
      <webElementGuid>c1d00cff-8cc6-40e3-9d2a-d28260198b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Folder (1)/Page_Order Release Finder/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>c8004c4c-c74f-4f4b-8f67-bf8556926c33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='order_release/indicator']</value>
      <webElementGuid>1a943523-2949-4f2a-87c2-7ab4ead07ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyDataDiv']/table/tbody/tr/td/table/tbody/tr[4]/td/div/span/select</value>
      <webElementGuid>3c45e611-36bd-45f1-b8a1-2d80f52ab097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indicator'])[1]/following::select[1]</value>
      <webElementGuid>714ae498-b3cf-4368-a2e6-1e04fb1e5960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Release Reference Number Qualifier'])[1]/following::select[2]</value>
      <webElementGuid>b46d1f97-5f77-4551-bb28-abfdb172a758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Release Attribute'])[1]/preceding::select[1]</value>
      <webElementGuid>51465e97-4665-452e-b9e3-8e977f3c2b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Early Pickup Date'])[1]/preceding::select[2]</value>
      <webElementGuid>c9f73518-2d5b-4e7e-b0e0-1fb5b5f362b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div/span/select</value>
      <webElementGuid>2dbbbed2-85dd-4277-8a9f-7f52c0eea05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'order_release/indicator' and (text() = 'WhiteGreenYellowRedBlueOrange' or . = 'WhiteGreenYellowRedBlueOrange')]</value>
      <webElementGuid>436bf04e-1e9c-4ce3-88c4-79a422a996b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
