<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BXC.HOS_TRUCK_RULE_SET</name>
   <tag></tag>
   <elementGuidId>fa74ef7c-3b9e-41d9-8440-5890b9184f3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='rgSGSec.2.1.1.3.k']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;BXC.HOS_TRUCK_RULE_SET&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>30d34f5f-b634-49b1-96c6-cd44eeb6adf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rgSGSec.2.1.1.3.k</value>
      <webElementGuid>bd40aae9-dc09-487e-8feb-10e287e039fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4a8d4727-5cf6-4568-aa59-72e1c8e14e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>7fa5a03c-65d7-4370-9271-7d37abdd27a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OpenTarget('/GC3/glog.webserver.hosrule.HosRuleSetManagementServlet?bcKey=MTc0ODI3Mzg1NzA1OTox&amp;pk=BXC.HOS_TRUCK_RULE_SET&amp;finder_set_gid=HOS_RULE_SET&amp;management_action=edit'); return addToRecentlyViewed(finderSetGid,'BXC.HOS_TRUCK_RULE_SET', 'EDIT');</value>
      <webElementGuid>117a18d9-e515-48d0-b84a-807aa378cfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BXC.HOS_TRUCK_RULE_SET</value>
      <webElementGuid>3c0b5830-81c9-4a5d-9a63-53467c72f8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rgSGSec.2.1.1.3.k&quot;)</value>
      <webElementGuid>5ed518b5-ce54-40d9-9310-1c578aec9f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_HOS Rule Set Result/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>8b1a7b0c-d16a-4579-8ce0-cdf91bc38d87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='rgSGSec.2.1.1.3.k']</value>
      <webElementGuid>9b443842-a00a-4aa9-b999-c3656aa930dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rgSGSec.2.1.1.3']/a</value>
      <webElementGuid>f13beb2b-242f-4f91-aff6-b2a96c45e3dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BXC.HOS_TRUCK_RULE_SET')]</value>
      <webElementGuid>4e9fc808-53e4-49ea-9089-17caae2c47ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Domain Name'])[1]/following::a[2]</value>
      <webElementGuid>b882fae6-d173-4251-a724-d0f0b06561cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::a[2]</value>
      <webElementGuid>2e0640db-2a15-48d3-ac62-c0c532a260af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BXC.ALL_ACTIVITIES_SET'])[1]/preceding::a[2]</value>
      <webElementGuid>a6433d77-6908-4b29-a60f-a57b347e0672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOS_TRUCK_RULE_SET'])[1]/preceding::a[3]</value>
      <webElementGuid>fb2e6788-f9e0-4369-a361-979e2e9e2549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BXC.HOS_TRUCK_RULE_SET']/parent::*</value>
      <webElementGuid>643c1e16-af1a-4e6e-ba7c-0954a26b0ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[2]</value>
      <webElementGuid>3ff46175-7f6b-4d9b-b097-2f1194db9cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>f8b353bb-bdc1-4e74-bcdc-77966a233cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'rgSGSec.2.1.1.3.k' and @href = 'javascript:void(0);' and (text() = 'BXC.HOS_TRUCK_RULE_SET' or . = 'BXC.HOS_TRUCK_RULE_SET')]</value>
      <webElementGuid>ffffe14f-db50-4c06-b893-4590e7c462f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
