<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , mainBodyFrame, , ))_mainBody</name>
   <tag></tag>
   <elementGuidId>b40cbbe6-9e6f-45c4-a0f4-02162276a856</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainBodyFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainBodyFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;mainBody&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>882113e8-2941-4442-bd89-40080933ebd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframeBody</value>
      <webElementGuid>2c500b90-f411-4bb5-9a13-c424eb8c1683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>0e505d10-0b22-4b06-b26f-eb28adfb8765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mainBody</value>
      <webElementGuid>3c136cf0-c477-47a7-9974-91ea455f5755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainBodyFrame</value>
      <webElementGuid>955dd4f2-543b-4215-8f2a-c95ba0183870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.util.QueryResponseServlet/1750422271182?bcKey=new&amp;action_name=add_order_to_shipment&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.1000434</value>
      <webElementGuid>1a933c1a-d127-486d-868c-95ca16ecd899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainBodyFrame&quot;)</value>
      <webElementGuid>6f6299d2-2604-4dbf-81f1-07b04fb8c200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainBodyFrame']</value>
      <webElementGuid>15d75d6e-dbac-4afe-8c0b-f6bd64b3b4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>04c3a53f-7c5d-4fc7-be10-f560d60b8ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1750422271182?bcKey=new&amp;action_name=add_order_to_shipment&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.1000434']</value>
      <webElementGuid>fc96c662-c6e3-44df-a0bc-efc75f39ae21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1750413217478?bcKey=new&amp;action_name=add_order_to_shipment&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.1000412']</value>
      <webElementGuid>3b8e63d4-16bd-4345-86d4-f903035e7693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1750356383877?bcKey=new&amp;action_name=add_order_to_shipment&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.1000384']</value>
      <webElementGuid>04af30b3-de82-4618-8de2-1937ffe44f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1750258781581?bcKey=new&amp;action_name=add_order_to_shipment&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.TESTSHP01234']</value>
      <webElementGuid>71a40164-d9d3-4d5d-be37-6124484d1fed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
