<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_mainBody</name>
   <tag></tag>
   <elementGuidId>e14cb163-0d38-4205-8ee4-2d7bb51d6ffd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainBodyFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainBodyFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;mainBody&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f5aa7db0-370e-4537-b217-14f869f1534e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframeBody</value>
      <webElementGuid>5ce21288-3dfd-4f3a-839e-6a17d2464e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>62207f6d-9932-405b-8ccc-22ab7a0a1f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mainBody</value>
      <webElementGuid>19e87f4e-80a5-40a4-944e-95746c7898ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainBodyFrame</value>
      <webElementGuid>8e90c40e-5ccc-46d5-8df7-6c5900e31380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.util.QueryResponseServlet/1751452915479?bcKey=new&amp;action_name=add_order_to_shipment&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.TESTSHP1111</value>
      <webElementGuid>b6294f45-8b51-4b70-8a5d-c4ce7f6e6c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainBodyFrame&quot;)</value>
      <webElementGuid>f27502b0-d97b-4325-8e4d-d1c1a41d4aef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainBodyFrame']</value>
      <webElementGuid>6dedc813-9850-4902-98fc-65738eeb07b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>d14f4046-3d1d-4bcf-9952-7101c7836702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1751452915479?bcKey=new&amp;action_name=add_order_to_shipment&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.TESTSHP1111']</value>
      <webElementGuid>6424d48c-84d2-4b0f-8b08-875b2994e181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1750329408007?bcKey=new&amp;action_name=add_order_to_shipment&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.1000280']</value>
      <webElementGuid>7b7594ec-ddab-4836-b2c7-61f2aa55e3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1748958602462?bcKey=new&amp;action_name=add_order_to_shipment&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.51031']</value>
      <webElementGuid>feaed939-7504-4f62-9014-fe88ba356449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1747299652310?bcKey=new&amp;action_name=add_order_to_shipment&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.6007']</value>
      <webElementGuid>07fc09a3-c78b-4047-bfe5-7a7db2136114</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
