<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__order_release</name>
   <tag></tag>
   <elementGuidId>f1e32f0e-4d7f-4de7-8add-949c18281911</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='order_release']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#order_release</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Order Release ID&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>679fb358-f89b-4f20-a63e-48e0913e651e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>d1d92087-afbc-401e-9e7f-6f84a9dd3687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>54dea039-b337-4ca3-a4d8-880d9bb9fb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Order Release ID</value>
      <webElementGuid>bfaa1e0d-2d16-426c-ab80-9c5e385e1fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>99999</value>
      <webElementGuid>f0baa1c1-7115-4afe-9396-e2fa8e9590b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_release</value>
      <webElementGuid>89fab3be-764a-4e68-a69b-b203a53cff54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_release</value>
      <webElementGuid>088bda95-1f7b-4496-9eb9-d90589fca51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9e89865c-1c59-477c-a686-9e63cc8d6ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>autoCompleteKeyEventListener(event, 'order_release'); return pickListHandler('glog.server.query.order.OrderReleaseQuery', 'management_main', 'order_release', 'Order\x20Release\x20ID', 'false', 'false', 'false', 'true', '', '', '', '', '', '', '', event, 'multiple', '', 'false', null, '', '');</value>
      <webElementGuid>49e8b5d5-40f3-4fd9-a6c3-eca0fad3c1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>autoCompleteKeyEventListener(event, 'order_release');</value>
      <webElementGuid>877199ca-7bb1-46dc-8886-2844c3aeccf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>autoCompleteHandler('glog.server.query.order.OrderReleaseQuery', 'management_main', 'order_release', '', '', '', '', event, '', 'false', 3, null, '', '');</value>
      <webElementGuid>e24c5676-0c48-4188-9502-40cab133b82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>return onPickBlur(this,false);</value>
      <webElementGuid>1a90dc1a-d8d2-42b1-9922-0de6ed45192b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7160ffcd-8aac-4d0c-974f-6c4d0d7e9041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_release&quot;)</value>
      <webElementGuid>25d37ad3-7a39-4f17-b73b-98b4896dfee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Move Order To Shipment/iframe_mainBody</value>
      <webElementGuid>1f995afe-c5af-4a48-a938-130773065c94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='order_release']</value>
      <webElementGuid>f4b9d70c-59c0-485f-a18e-7ad37f1eb0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyDataDiv']/div/table/tbody/tr/td/div/table/tbody/tr/td/input</value>
      <webElementGuid>a4ce282f-f92e-41c0-903d-7783a3cd08e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>efad70ff-4217-4157-be8f-ba279b621a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'order_release' and @id = 'order_release']</value>
      <webElementGuid>0a36a824-63d1-4672-9c72-41dfa7d4424b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
