<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__order_release (1)</name>
   <tag></tag>
   <elementGuidId>f008c9c5-81d0-4840-8307-f8d0e16e7ee9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='order_release']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#order_release</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Order Release ID&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e033e32-74d6-48d9-bfb8-93e06b252651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>b140bfac-04be-4be3-acdf-60b64cd549d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>45bb44c0-5d3f-4753-b3f8-5e82317f89fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Order Release ID</value>
      <webElementGuid>024fadad-f51c-48b2-aeb0-4146fa44e5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>99999</value>
      <webElementGuid>7481c043-fc4b-4ad0-8e25-49c1f02b9601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_release</value>
      <webElementGuid>2563e819-d116-4124-bb7e-28a0276e9eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_release</value>
      <webElementGuid>69b4e828-6569-4496-98a6-fb485dbf0b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>87e51759-37ac-4b1b-9aba-0f37040b99b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>autoCompleteKeyEventListener(event, 'order_release'); return pickListHandler('glog.server.query.order.OrderReleaseQuery', 'management_main', 'order_release', 'Order\x20Release\x20ID', 'false', 'false', 'false', 'true', '', '', '', '', '', '', '', event, 'multiple', '', 'false', null, '', '');</value>
      <webElementGuid>f05995a5-af9c-499d-ae1e-6b0a17e43695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>autoCompleteKeyEventListener(event, 'order_release');</value>
      <webElementGuid>a456422b-1162-4721-9820-b0cc2ab6ae97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>autoCompleteHandler('glog.server.query.order.OrderReleaseQuery', 'management_main', 'order_release', '', '', '', '', event, '', 'false', 3, null, '', '');</value>
      <webElementGuid>5e24649c-835b-487f-bc72-62ad1af00238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>return onPickBlur(this,false);</value>
      <webElementGuid>354a1771-8d8e-48ca-a729-51f04bc42958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>469dcc57-329f-4f87-a7a0-3575bba82555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_release&quot;)</value>
      <webElementGuid>46eff653-72f3-4e30-baee-fcbfbf54feba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Move Order To Shipment/iframe_Capture object_mainBody</value>
      <webElementGuid>a4de5293-3f12-47ab-aa0c-b65185beeedc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='order_release']</value>
      <webElementGuid>4e8dcc63-9665-40bd-ba3d-897504bdf7d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyDataDiv']/div/table/tbody/tr/td/div/table/tbody/tr/td/input</value>
      <webElementGuid>db1cffe6-7d9c-4068-83d6-582f1f3ffcea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>0350285f-0578-4708-8123-6411f61871c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'order_release' and @id = 'order_release']</value>
      <webElementGuid>9bcd3eec-84d4-4db6-86ba-33ead67fb874</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
