<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Estimated Departure Time_shipment_stopest_75127e</name>
   <tag></tag>
   <elementGuidId>e0dc2cb7-cbe2-4163-bdae-d6c93418e1e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='shipment_stop/estimated_departure::glyph']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Estimated Departure Time Calendar&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4a4add2a-f3d0-4193-af91-2c5783fcae35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Estimated Departure Time Calendar</value>
      <webElementGuid>60392697-c026-47c5-a017-813b77c3457e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8b7c00a2-82b8-409a-932a-9d73eb73450e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shipment_stop/estimated_departure::glyph</value>
      <webElementGuid>bb42dc73-a027-4bbc-bff2-31e8d11ff618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calendarIcon</value>
      <webElementGuid>467b28ba-e5f0-4669-9324-2569e9e4641c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shipment_stop/estimated_departure::glyph&quot;)</value>
      <webElementGuid>390ea957-3655-4c65-ac69-9103c6cbff1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Buy Shipment - Shipment Stop/iframe_PRAJYOT.DABHADEBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>89a658ca-ee4d-4d9c-986f-2183551a2804</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='shipment_stop/estimated_departure::glyph']</value>
      <webElementGuid>5a50240b-fd32-4c97-b60b-9a19b09d9ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipment_stop/estimated_departure']/span/a</value>
      <webElementGuid>8c992a79-210c-41e6-9c18-93f45a8578e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>80e8c752-3390-4b65-8e9b-b3d045bd3700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/div/span/a</value>
      <webElementGuid>6ab98fe9-0360-4ef6-95bd-9f964e4799b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'shipment_stop/estimated_departure::glyph']</value>
      <webElementGuid>45fc8752-f2c0-4b4d-9d23-6181a7ff5997</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
