<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_CUS-6704-19924</name>
   <tag></tag>
   <elementGuidId>7ba069c9-e28b-493a-ad8c-488a45a365a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shipment_stop/location/xid::dropdownPopup::content::db']/table/tbody/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.acSelItem > td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;CUS-6704-19924&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>fc695533-00bf-4376-8e52-8f669323fb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>549848ba-137e-4dfe-8f3f-cc16d711ca64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CUS-6704-19924</value>
      <webElementGuid>f385fee3-dcc8-489d-87e3-b816c3524bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shipment_stop/location/xid::dropdownPopup::content::db&quot;)/table[@class=&quot;acTable&quot;]/tbody[1]/tr[@class=&quot;acSelItem&quot;]/td[1]</value>
      <webElementGuid>72a40459-1b72-4173-b1b1-f3bed3d80dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Buy Shipment - Shipment Stop/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>0bd3d6e7-1512-4238-a005-b3b7bf2e69f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipment_stop/location/xid::dropdownPopup::content::db']/table/tbody/tr/td</value>
      <webElementGuid>724413b0-66e0-429c-9f7d-eb22a135223d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Ship Unit'])[1]/following::td[2]</value>
      <webElementGuid>547c95c9-eb45-4f2f-a7bc-264b5a142db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[4]/following::td[4]</value>
      <webElementGuid>7518ea7e-2e9b-4202-a37e-30204078afc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top'])[1]/preceding::td[1]</value>
      <webElementGuid>7d89ba6c-b300-46ed-8de8-98b834d6315c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[5]/preceding::td[2]</value>
      <webElementGuid>06ac41c5-af07-49ef-96d8-f012957da7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CUS-6704-19924']/parent::*</value>
      <webElementGuid>6d388ef5-7d3a-4bb0-914a-2b24c0d81ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/table/tbody/tr/td</value>
      <webElementGuid>baf42227-8784-4a91-adc0-091a4a4de0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'CUS-6704-19924' or . = 'CUS-6704-19924')]</value>
      <webElementGuid>0d17694f-4d40-46f0-a5c5-ba074139b3d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
