<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_DRIVER_ID_gridBodyCell</name>
   <tag></tag>
   <elementGuidId>2bbc8f65-997b-4202-a89a-845c55529447</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='BXC.PAUL_ARBUTINA_10026088 BXC.DRIVER_ID 10026088']/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;10026088&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>cdc5d5be-d3ad-4bab-bab3-b4bcee45a5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gridBodyCell</value>
      <webElementGuid>2902f02e-c0f8-4bb8-a061-73bdd2b386e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10026088</value>
      <webElementGuid>91e99636-a229-4dcf-bc33-bbafc6586bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BXC.PAUL_ARBUTINA_10026088 BXC.DRIVER_ID 10026088&quot;)/td[@class=&quot;gridBodyCell&quot;]</value>
      <webElementGuid>e1a225b3-52c2-40fc-a751-aae4cd4e2439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/driver objects/Page_Driver - Driver/iframe_concat(id(, , mainBodyFrame, , ))_ma_a290fd</value>
      <webElementGuid>e8574de5-2d89-4831-99b1-5bee739e9ec7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='BXC.PAUL_ARBUTINA_10026088 BXC.DRIVER_ID 10026088']/td[2]</value>
      <webElementGuid>43ba18fa-cac3-480e-a695-c57d19070313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DRIVER_ID'])[2]/following::td[1]</value>
      <webElementGuid>fdca252f-1cd9-4741-9f73-31fe1473a8f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[3]/following::td[2]</value>
      <webElementGuid>d08f7579-5b43-4a2c-9221-8292dc7816f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top'])[1]/preceding::td[4]</value>
      <webElementGuid>d7def663-e02b-41a7-a270-541d4d031f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Licenses'])[2]/preceding::td[5]</value>
      <webElementGuid>4064115b-3d2d-4992-8eb0-2bf828d9ff85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>4c0e232b-44c7-4218-ac7b-03a9bd39e862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '10026088' or . = '10026088')]</value>
      <webElementGuid>386b15d9-2df8-4581-a2a2-186f443295c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
