<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bill To__FOpt1_FOr10_FONSr20MAnt21r10AP3r_a87ff0</name>
   <tag></tag>
   <elementGuidId>5c86da83-b44c-4945-9195-141dfec50364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r12:0:AT1:_ATp:table1:0:soc2::drop']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Expand Work Email Email m/d/yy Press down arrow to access Calendar From Date Select Date m/d/yy Press down arrow to access Calendar To Date Select Date&quot;i] >> a >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cfe48f1b-60f2-4362-98fb-1dd1d171cbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>08e77750-8d94-4ad0-82f4-b669f01eec9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1kv</value>
      <webElementGuid>f2ad9785-8704-407f-bdd0-72c0ac62fb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r12:0:AT1:_ATp:table1:0:soc2::drop</value>
      <webElementGuid>ddc0103a-057e-4dfe-8fca-e1750c052035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r12:0:AT1:_ATp:table1:0:soc2::drop&quot;)</value>
      <webElementGuid>3393e142-bb4e-4a44-982a-c78dd6ecadde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r12:0:AT1:_ATp:table1:0:soc2::drop']</value>
      <webElementGuid>188ecbe9-669e-4eeb-a61e-86898b91baa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r12:0:AT1:_ATp:table1:0:soc2::cntrl']/a</value>
      <webElementGuid>5a6e7175-cc06-4800-a55d-c237d3201f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/div/div/div/div[2]/div/div[2]/table/tbody/tr/td[6]/span/span/span/a</value>
      <webElementGuid>b229576a-367a-4a08-9f0c-4d76c1c16e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r12:0:AT1:_ATp:table1:0:soc2::drop']</value>
      <webElementGuid>dd0218f8-a0a9-497d-8258-95998c66514a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
