<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Carrier Type__FOpt1_FOr10_FONSr20MAnt21r1_c6fa49</name>
   <tag></tag>
   <elementGuidId>9b9fbf3d-8aee-4421-b967-46e815cacd89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r2:0:ExtGen_attr_CarrierType_c_Organization1::drop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr >> internal:has-text=/^Carrier Type$/ >> a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cf3dfbff-341a-4437-ab8a-2c57ed79e626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>76dc4bd3-83c0-4304-9474-8cfe3f9efef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1kv</value>
      <webElementGuid>60afabd7-6c0c-49eb-8ad5-bebd98894847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r2:0:ExtGen_attr_CarrierType_c_Organization1::drop</value>
      <webElementGuid>098eb530-0461-4079-be7e-2cd488f4fc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r2:0:ExtGen_attr_CarrierType_c_Organization1::drop&quot;)</value>
      <webElementGuid>3e5928cb-4415-4d64-9a05-203e2b9505f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r2:0:ExtGen_attr_CarrierType_c_Organization1::drop']</value>
      <webElementGuid>a067f20b-87da-4e7a-8d67-418c9dfa5a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r2:0:ExtGen_attr_CarrierType_c_Organization1::cntrl']/a</value>
      <webElementGuid>11215ac7-15fc-4367-ad24-7f01dd6e40bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td[2]/span/a</value>
      <webElementGuid>033d2d79-8354-4974-967e-6ba84cf1c9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r2:0:ExtGen_attr_CarrierType_c_Organization1::drop']</value>
      <webElementGuid>5c9ddf3f-9137-4232-81aa-e2c8ec4c2fb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
