<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Detached Table__FOpt1_FOr10_FONSr20MAnt21_9709ff</name>
   <tag></tag>
   <elementGuidId>0dacc540-8371-463a-802c-0693556fbdcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:sdh1::_afrDscl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Expand Additional Identifiers&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>337a60c7-513a-4688-8f36-6077b00f316e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>24ee6c84-6528-4691-8443-51ef3336a1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0a8fc69c-da84-411b-ae16-f1ffbced728e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:sdh1::content</value>
      <webElementGuid>9e18155c-589d-498a-8984-208ba719f66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Expand Additional Identifiers</value>
      <webElementGuid>8bd10c14-f6c4-4c60-a878-edc6c878ff0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2b3fe4e3-33c4-4332-a87e-e3eb0a683991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.focus();return false</value>
      <webElementGuid>ebc5d7f1-f053-48d5-b1e5-87d547d4279d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1b1 x1tp</value>
      <webElementGuid>616a95de-43b5-470e-a9a3-6cf4a2641051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:sdh1::_afrDscl</value>
      <webElementGuid>20c46b22-d5a1-4599-9802-2bab272082c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Expand Additional Identifiers</value>
      <webElementGuid>c8563785-ca28-48e5-bbe5-6d561256fc1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:sdh1::_afrDscl&quot;)</value>
      <webElementGuid>7660bd51-3cd9-421d-ad0e-5358b6833255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:sdh1::_afrDscl']</value>
      <webElementGuid>99a59d84-46e3-4794-9bc8-93ad47192cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:sdh1']/div/table/tbody/tr/td/a</value>
      <webElementGuid>68dabacb-2171-4d82-b186-3df436f63c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[40]</value>
      <webElementGuid>803da354-1d60-433e-b6ef-74bc3a1361e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/table/tbody/tr/td/a</value>
      <webElementGuid>45590f92-068d-4aad-93f8-0a2c44f7ca7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = '_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:sdh1::_afrDscl' and @title = 'Expand Additional Identifiers']</value>
      <webElementGuid>3bb2b373-c336-4ebf-b7f9-0a5c4bdc279d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
