<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DQ Identifier_pt1_FOr11_FONSr20MAnt21r10A_abb236</name>
   <tag></tag>
   <elementGuidId>c66a8798-eee1-450d-883b-b81a13c4993c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:sdh6::_afrDscl&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Expand Additional Names&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>83e36253-0a25-4a3a-9492-ec16392e27c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2fb02161-8eda-4ec2-bc9e-c08776b7e989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cc254db9-8b38-4398-9f5e-f3d6b68573d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:MAnt2:1:r1:0:AP3:sdh6::content</value>
      <webElementGuid>977fa442-5121-4345-a2f5-b0c870efe105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Expand Additional Names</value>
      <webElementGuid>ebf17999-f963-45e5-b6c7-db50f9dafa58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2f493204-6c3b-4ccc-9d69-a75fab647bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.focus();return false</value>
      <webElementGuid>38ef982a-34db-42a2-a543-ba20814789c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1b1 x1tp</value>
      <webElementGuid>aeb51dca-399e-4a43-bbf2-d99ddf7918dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:MAnt2:1:r1:0:AP3:sdh6::_afrDscl</value>
      <webElementGuid>e838e58f-bbbc-424e-931c-4c977793e464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Expand Additional Names</value>
      <webElementGuid>69e8a68c-b06e-4a07-9d4e-4e4ff6632e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:MAnt2:1:r1:0:AP3:sdh6::_afrDscl&quot;)</value>
      <webElementGuid>29ec61aa-0591-4e4a-95fa-502d9197e995</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pt1:_FOr1:1:_FONSr2:0:MAnt2:1:r1:0:AP3:sdh6::_afrDscl']</value>
      <webElementGuid>c48d6563-ee20-4de3-a979-390c08bf8087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pt1:_FOr1:1:_FONSr2:0:MAnt2:1:r1:0:AP3:sdh6']/div/table/tbody/tr/td/a</value>
      <webElementGuid>12d334b4-a030-40c6-ab45-5669137b8555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[33]</value>
      <webElementGuid>12b7764f-5458-483a-93b6-7c01ba5ba25d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr/td/a</value>
      <webElementGuid>e853836d-ced3-48b6-af9f-d98ee872e0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'pt1:_FOr1:1:_FONSr2:0:MAnt2:1:r1:0:AP3:sdh6::_afrDscl' and @title = 'Expand Additional Names']</value>
      <webElementGuid>33682f66-ac54-4417-893e-a7bf50b1a941</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
