<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ORGANIZATION__FOpt1_FOr10_FONSr20MAnt21r3_f515fe</name>
   <tag></tag>
   <elementGuidId>5e598bea-c455-4da0-9e83-89e2ef24de22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/span/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Current m/d/yy Press down arrow to access Calendar From Date Select Date To Date Press down arrow to access Calendar Select Date Delete&quot;i] >> a >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc1f63d8-5aa7-4a90-88aa-1ff24482e386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e5d0f0bd-ce68-40d1-8f71-e382ee04b8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1kv</value>
      <webElementGuid>e35317cb-71e2-45c3-8085-c3af8c9c734a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r3:0:UsageAssignment:UsageAssignments:_ATp:Table:3:InitialUsageSelection::drop</value>
      <webElementGuid>fa90a91c-b9e7-4a24-bef6-aa8a8e34b8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r3:0:UsageAssignment:UsageAssignments:_ATp:Table:3:InitialUsageSelection::drop&quot;)</value>
      <webElementGuid>904fb0e0-8519-48c9-bd8a-870dfe7a3d0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r3:0:UsageAssignment:UsageAssignments:_ATp:Table:3:InitialUsageSelection::drop']</value>
      <webElementGuid>9e968117-ac95-47ee-9c37-5dc915ecb02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r3:0:UsageAssignment:UsageAssignments:_ATp:Table:3:InitialUsageSelection::cntrl']/a</value>
      <webElementGuid>a615a60b-75f3-45f9-81fb-f3a39b300e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/a</value>
      <webElementGuid>e618eaf2-1bf2-493f-b382-a9e7f1d9ba95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r3:0:UsageAssignment:UsageAssignments:_ATp:Table:3:InitialUsageSelection::drop']</value>
      <webElementGuid>5d355f2a-5834-40a1-aed8-f500de3a4168</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
