<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Remove Link__FOpt1_FOr10_FONSr20MAnt_d1517b</name>
   <tag></tag>
   <elementGuidId>cca827a9-647c-4af0-9d04-63c1c2794525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r10:0:ap1:r3:0:AT1:r1:1:richText1::cont']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Create Note Close *Type Private Private Note Choose a Font Font Size increment disabled decrement disabled Undo Undo Redo Redo Clear Styling Clear Styling Rich Text Editing Mode Rich Text Editing Mode Source Code Editing Mode Source Code Editing Mode Foreground Color Foreground Color 000000 Click to launch popup selector Background Color Background Color No Color Click to launch popup selector Bold Bold Italic Italic Underline Underline Subscript Subscript Superscript Superscript Strikethrough Strikethrough Justify Left Justify Left Justify Center Justify Center Justify Right Justify Right Justify Full Justify Full Bulleted List Bulleted List Numbered List Numbered List Outdent Outdent Indent Indent Add Link Add Link Remove Link Remove Link Save and Close Cancel&quot;i] >> iframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ad412e4f-eda2-4b3a-9559-c1ad0289242d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c1c2c2d1-5a7e-4902-92ee-21a4cfd465d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xr1</value>
      <webElementGuid>fc57b6ae-e833-405c-b53e-5f0882623594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r10:0:ap1:r3:0:AT1:r1:1:richText1::cont</value>
      <webElementGuid>80331504-8f07-4450-94e2-e737cf6d5cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/crmUI/afr/blank.html</value>
      <webElementGuid>d3a0eb15-a800-4fcb-b830-53065b8d5cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-afr-rte-loaded</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>eb4c97a6-3576-4524-96ac-2b445b3dc6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r10:0:ap1:r3:0:AT1:r1:1:richText1::cont&quot;)</value>
      <webElementGuid>b97f3e0d-56b5-485d-97ef-6a37decdc271</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r10:0:ap1:r3:0:AT1:r1:1:richText1::cont']</value>
      <webElementGuid>1d5383eb-4405-4b56-bfff-13b242cf6e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r10:0:ap1:r3:0:AT1:r1:1:richText1::_cic']/iframe</value>
      <webElementGuid>84fa6e61-3736-40a3-b731-bae0c5f4b925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>e980eac7-666c-48a0-a078-e085936655c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = '_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r10:0:ap1:r3:0:AT1:r1:1:richText1::cont' and @src = '/crmUI/afr/blank.html']</value>
      <webElementGuid>f1bf4db5-d769-4960-b2ed-584916c6b51b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
