<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Default Color_x11o</name>
   <tag></tag>
   <elementGuidId>4e95b7ce-0815-496c-97a8-dd4f8aa986db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r10:0:ap1:r3:0:AT1:r1:1:richText1_afrBgColor::icPop::stdTbl']/tbody/tr[6]/td[7]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Black (000000 / 0,0,0)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bb05f508-ae68-4546-9793-17bfb68184a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/crmUI/afr/t.gif</value>
      <webElementGuid>99f19225-9254-4233-9a6a-35432a3ab2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x11o</value>
      <webElementGuid>691c6dd2-8a14-488a-ad2d-b64d2a5ecb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_adfsw</name>
      <type>Main</type>
      <value>#000000</value>
      <webElementGuid>feb118dc-f820-4f81-a775-e52ad43bdea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Black (000000 / 0,0,0)</value>
      <webElementGuid>e94c9b12-b48e-4fa8-9eac-dfd77a8968df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Black (000000 / 0,0,0)</value>
      <webElementGuid>6a845ad8-0dea-42d7-ab93-c83caf3586af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r10:0:ap1:r3:0:AT1:r1:1:richText1_afrBgColor::icPop::stdTbl&quot;)/tbody[1]/tr[6]/td[@class=&quot;x11p&quot;]/img[@class=&quot;x11o&quot;]</value>
      <webElementGuid>4f3d95be-54ea-4d1c-8516-d8b277abecee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r10:0:ap1:r3:0:AT1:r1:1:richText1_afrBgColor::icPop::stdTbl']/tbody/tr[6]/td[7]/img</value>
      <webElementGuid>b6a60984-797e-4951-bfdc-28d118d2b71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Black (000000 / 0,0,0)'])[2]</value>
      <webElementGuid>dc082c6f-b384-414b-af75-f2370585d8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/table/tbody/tr[5]/td/table/tbody/tr[6]/td[7]/img</value>
      <webElementGuid>745273a1-6562-4253-a0c4-fb18fca72295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/crmUI/afr/t.gif' and @title = 'Black (000000 / 0,0,0)' and @alt = 'Black (000000 / 0,0,0)']</value>
      <webElementGuid>be0cc62d-39c1-4789-88a5-8c8a003a2a3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
