<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Default Color_x11o_1</name>
   <tag></tag>
   <elementGuidId>30cc824d-9095-4a15-a2f4-43347389df66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r10:0:ap1:r3:0:AT1:r1:1:richText1_afrFgColor::icPop::stdTbl']/tbody/tr/td[7]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;White (FFFFFF / 255,255,255)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b20d4189-a261-44a1-94dc-5a7664e3d70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/crmUI/afr/t.gif</value>
      <webElementGuid>bc907da5-1e00-4a81-bcb7-48e9df895680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x11o</value>
      <webElementGuid>15f6a5cb-5649-45d5-8a1a-d793f516ee53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_adfsw</name>
      <type>Main</type>
      <value>#FFFFFF</value>
      <webElementGuid>ca81518f-76f1-4977-a798-f747d5e46ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>White (FFFFFF / 255,255,255)</value>
      <webElementGuid>d68d54c3-e6c5-4aee-bfba-af2af27085e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>White (FFFFFF / 255,255,255)</value>
      <webElementGuid>1347a6b8-80ff-44e7-a34b-a96c6d7bc943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r10:0:ap1:r3:0:AT1:r1:1:richText1_afrFgColor::icPop::stdTbl&quot;)/tbody[1]/tr[1]/td[@class=&quot;x11p&quot;]/img[@class=&quot;x11o&quot;]</value>
      <webElementGuid>b22738f1-18dd-4d45-8144-06a94e17f553</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r10:0:ap1:r3:0:AT1:r1:1:richText1_afrFgColor::icPop::stdTbl']/tbody/tr/td[7]/img</value>
      <webElementGuid>3c77bc5b-9dae-4dcc-9dd8-89b5dd9f8ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='White (FFFFFF / 255,255,255)'])[2]</value>
      <webElementGuid>3e0c912d-2193-48bc-ac09-6758f60033b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/table/tbody/tr[5]/td/table/tbody/tr/td[7]/img</value>
      <webElementGuid>56161698-81fa-426e-aa1e-8ebd1759cae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/crmUI/afr/t.gif' and @title = 'White (FFFFFF / 255,255,255)' and @alt = 'White (FFFFFF / 255,255,255)']</value>
      <webElementGuid>18c39b3f-6fef-419f-b663-6147c7336c6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
