<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_pt1_FOr11_FONSr20MAnt21AP1r10inputText2</name>
   <tag></tag>
   <elementGuidId>4a9b8d66-349f-4757-a542-7860311d0bc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[4]/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Name&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d966416-0de5-4623-b3ca-d513a0afff69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:MAnt2:1:AP1:r1:0:inputText2::content</value>
      <webElementGuid>4d527db4-60b2-4545-9d81-0cad2555892a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:MAnt2:1:AP1:r1:0:inputText2</value>
      <webElementGuid>6241276c-ce5f-478b-901c-b35c6587b3ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x25</value>
      <webElementGuid>9ee9adc6-908f-498c-9ba8-807171685149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>77490a27-daf4-4247-a268-8cf5170ead7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>360</value>
      <webElementGuid>2c9b93e0-4911-4a1f-b74a-5f5e7227fc5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a3a7b921-38b3-4e2f-86ec-3690ff9a37ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3d648f4e-297e-4332-b529-66113996e93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:MAnt2:1:AP1:r1:0:inputText2::content&quot;)</value>
      <webElementGuid>ae1d8d8e-75e5-431c-88c1-973d8c4d2294</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pt1:_FOr1:1:_FONSr2:0:MAnt2:1:AP1:r1:0:inputText2::content']</value>
      <webElementGuid>fe926241-ca16-4b72-816a-c93feb383841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='pt1:_FOr1:1:_FONSr2:0:MAnt2:1:AP1:r1:0:inputText2']/td[2]/input</value>
      <webElementGuid>dbb7da38-4561-4ef9-9be9-09bf2feb7852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>890ce3e3-162c-4934-bdcb-be161211e46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pt1:_FOr1:1:_FONSr2:0:MAnt2:1:AP1:r1:0:inputText2::content' and @name = 'pt1:_FOr1:1:_FONSr2:0:MAnt2:1:AP1:r1:0:inputText2' and @type = 'text']</value>
      <webElementGuid>d5b8afc0-9709-4bdd-980b-7e5f5295d341</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
