<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_American Samoa</name>
   <tag></tag>
   <elementGuidId>aa2efd7e-e4cf-4634-bb4f-335bc638ad92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r3:0:AT2:_ATp:table2:0:soc2::pop']/li[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;American Samoa&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b3570d7b-64fb-498b-a0cc-2c3332dd48ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1l7</value>
      <webElementGuid>5b200835-1326-477e-9bc5-1a873ac08897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_adfiv</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c145dd0c-e25f-468e-8d58-c988c2451b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>American Samoa</value>
      <webElementGuid>20c05582-6706-4498-a464-92d84e038548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r3:0:AT2:_ATp:table2:0:soc2::pop&quot;)/li[@class=&quot;x1l7&quot;]</value>
      <webElementGuid>01d6f56f-2f26-481c-b91c-170f03d4934a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r3:0:AT2:_ATp:table2:0:soc2::pop']/li[7]</value>
      <webElementGuid>73e30cb0-75c2-4b79-ac4c-c19bafa84ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Algeria'])[1]/following::li[1]</value>
      <webElementGuid>a0d4fb5b-38ca-4758-8e5e-810be2800ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Albania'])[1]/following::li[2]</value>
      <webElementGuid>b82e057c-6188-47f1-be10-746966e3ab5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Andorra'])[1]/preceding::li[1]</value>
      <webElementGuid>82474667-d59a-4616-a655-7df894f362e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Angola'])[1]/preceding::li[2]</value>
      <webElementGuid>d9809155-6fe7-4f87-bdc0-3f3d56f761f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='American Samoa']/parent::*</value>
      <webElementGuid>7387635a-1ca7-4841-8d0b-72d4ba3b5176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/ul/li[7]</value>
      <webElementGuid>429137d5-2af0-41e2-bac7-e8a501054ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'American Samoa' or . = 'American Samoa')]</value>
      <webElementGuid>129a114d-e03f-4963-8f46-a6ba2d6bcccf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
