<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_External Legal Entity</name>
   <tag></tag>
   <elementGuidId>1dca0d4e-b273-4683-ad51-512d02bde4ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:AP1:r1:0:selectOneChoice5::pop']/li[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;External Legal Entity&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0cf959b1-a45e-4053-94e5-a3f391c62907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1l7</value>
      <webElementGuid>4585f049-22c8-4f2d-9864-5c32d00dbda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_adfiv</name>
      <type>Main</type>
      <value>EXTERNAL_LEGAL_ENTITY</value>
      <webElementGuid>403d9a45-c3bf-43d4-a56b-dbcda561db6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>External Legal Entity</value>
      <webElementGuid>39808754-48e3-4db6-8540-903de750e61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:AP1:r1:0:selectOneChoice5::pop&quot;)/li[@class=&quot;x1l7&quot;]</value>
      <webElementGuid>e6c49718-0ac4-41ef-95bf-66bf95ecd95c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:AP1:r1:0:selectOneChoice5::pop']/li[6]</value>
      <webElementGuid>067cc6e6-3c88-4b18-9998-f0932d8f6f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expense Attendee'])[1]/following::li[1]</value>
      <webElementGuid>2c38876c-3420-4bb2-b386-4c89f666b02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disability Organization'])[1]/following::li[2]</value>
      <webElementGuid>0a103b2b-ead8-4c3e-b072-4e3b7402e961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='External Payee'])[1]/preceding::li[1]</value>
      <webElementGuid>2d083378-c346-40cd-ad52-0216a2b9a06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive Partner'])[1]/preceding::li[2]</value>
      <webElementGuid>b5cc3ed0-31ac-4fc9-8c9d-72e719b9937b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='External Legal Entity']/parent::*</value>
      <webElementGuid>65033fe5-3679-4707-8521-9eb44e28ac13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/ul/li[6]</value>
      <webElementGuid>a9ee426b-85b6-4294-b4f6-9737e2fc930b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'External Legal Entity' or . = 'External Legal Entity')]</value>
      <webElementGuid>73f6877a-c75d-4b37-b09c-30eaf9348b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pt1:_FOr1:1:_FONSr2:0:MAnt2:1:AP1:r1:0:selectOneChoice5::pop']/li[6]</value>
      <webElementGuid>15dc515a-050c-4d06-85ec-3b8ef13bfcbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
