<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>4030c3a5-f5a2-471e-b34c-cd373c0e0671</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pt1:_FOr1:1:_FONSr2:0:MAt2:0:ip1:Popup1:0:Advan1:0:efqrp::search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Search&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c8bb41e0-4432-4271-aadd-f26b559dc635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:MAt2:0:ip1:Popup1:0:Advan1:0:efqrp::search</value>
      <webElementGuid>42fb5b3f-b2f2-45ab-86dc-5c241ac9f8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xhv p_AFTextOnly</value>
      <webElementGuid>cdc9436a-3630-4282-87fb-ae4f717eeb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.focus();return false;</value>
      <webElementGuid>b521ef6f-5583-4a6b-b46c-51c5fb1280de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>b57f1746-ea70-48df-8e92-55b47649a857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:MAt2:0:ip1:Popup1:0:Advan1:0:efqrp::search&quot;)</value>
      <webElementGuid>26ec0a3c-5b09-4134-8742-e95a664fe5b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pt1:_FOr1:1:_FONSr2:0:MAt2:0:ip1:Popup1:0:Advan1:0:efqrp::search']</value>
      <webElementGuid>c7f23832-767b-4af5-ab69-06106d98e2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pt1:_FOr1:1:_FONSr2:0:MAt2:0:ip1:Popup1:0:Advan1:0:efqrp']/div[2]/div/table/tbody/tr/td/table/tbody/tr/td[3]/button</value>
      <webElementGuid>a7f927b1-4b81-44e2-bb7a-3a0aea85836d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyword'])[2]/following::button[1]</value>
      <webElementGuid>0f64ee6b-b05c-44b0-bf24-29237163aff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyword'])[1]/following::button[1]</value>
      <webElementGuid>b61f5843-eb9d-42bd-b340-7e3b808502e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/preceding::button[1]</value>
      <webElementGuid>d60cdb28-b6a9-46a5-9618-8f4989490786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Results'])[1]/preceding::button[2]</value>
      <webElementGuid>6a67d97a-9748-4fd7-b3c6-c677a0b58995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/table/tbody/tr/td[3]/button</value>
      <webElementGuid>6c36bc67-7bea-4f22-ab57-ba41bc7896a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pt1:_FOr1:1:_FONSr2:0:MAt2:0:ip1:Popup1:0:Advan1:0:efqrp::search' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>426fff07-a2c5-400a-a12e-25ad76b35e00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
