<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BXC.SO_17558076_20250812_07-01-2025_T_45b749</name>
   <tag></tag>
   <elementGuidId>c1718aa9-f7c0-43b1-83ca-a1fb7dcb8842</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='Selected'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;BXC.SO_17564908_20250812_07-01-2025_TPA_V1H&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcd6f432-6ee6-4538-b890-fdb55e49adb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>BXC.SO_17564908_20250812_07-01-2025_TPA_V1H</value>
      <webElementGuid>cd6dc08c-41d9-47f4-9453-b62dbd286238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>898038dd-d369-40a3-a3a8-10b26bc8abce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>resultGrid.selectRow(this);handleSelectionOnServer(finderSetGid, callerID,'BXC.SO_17564908_20250812_07\x2D01\x2D2025_TPA_V1H', this)</value>
      <webElementGuid>92bf31bd-8e1f-4209-b0c3-bca1c64618ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BXC.SO_17564908_20250812_07-01-2025_TPA_V1H</value>
      <webElementGuid>8d7c54d1-d1ae-4c93-ad0f-ab24b618244b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bb62d666-7893-407f-b280-cd98223ef327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Selected</value>
      <webElementGuid>4bd4db7e-c591-4292-957b-b490de4a2817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sgBodyCheck</value>
      <webElementGuid>593b8722-5d84-42fc-a440-83763df0cafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rgSGSec.2.1.2.1&quot;)/input[@class=&quot;sgBodyCheck&quot;]</value>
      <webElementGuid>b7006944-94fe-463f-9728-516b87193d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Samsara/Page_Order Release Result/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>9731cf7c-4953-4c40-919b-683cac1efb8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='Selected'])[2]</value>
      <webElementGuid>b1fe698f-d4cc-4129-906e-5faa4673fe30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rgSGSec.2.1.2.1']/input</value>
      <webElementGuid>5981c668-d8da-4b2e-8f46-13d49b67dad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>1daca456-8327-4e77-b361-959d0acfbea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'Selected']</value>
      <webElementGuid>0f7231eb-1f55-4376-8329-017321f2c285</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
