<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tr_1000020</name>
   <tag></tag>
   <elementGuidId>ff021aa5-6b4b-4916-b806-29f6c736e1f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='P_SHIPMENT_GID::dropdownPopup::content::db']/table/tbody/tr</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.acSelItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;P_SHIPMENT_GID\:\:dropdownPopup\:\:content\:\:db&quot;] >> internal:role=row[name=&quot;1000020&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tr</value>
      <webElementGuid>e54806bf-3284-41b2-96e8-3eb9c7de13c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gid</name>
      <type>Main</type>
      <value>BXC.1000020</value>
      <webElementGuid>75bbc978-d131-4897-8735-94f3a41dc0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xid</name>
      <type>Main</type>
      <value>1000020</value>
      <webElementGuid>cef4f3db-26fd-4617-b27b-1117e89f13ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldid</name>
      <type>Main</type>
      <value>P_SHIPMENT_GID</value>
      <webElementGuid>f9bb0d0f-358c-4ac3-ab46-20312f673dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b524148a-1044-4dda-99ca-ab896f557187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>acSelItem</value>
      <webElementGuid>d5d41f3b-ef22-48b8-b97e-562a6c956eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ea9735f2-940e-4e5a-9b8c-7ea00b626948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1000020</value>
      <webElementGuid>8f302f7a-dee3-4e47-8306-a88ffe9bdf84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P_SHIPMENT_GID::dropdownPopup::content::db&quot;)/table[@class=&quot;acTable&quot;]/tbody[1]/tr[@class=&quot;acSelItem&quot;]</value>
      <webElementGuid>ab8b7536-5fa6-4fdc-b2cf-49042a498b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_BILL_OF_LADING Report/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>15abf201-6cb3-4c5f-a614-f23609568265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P_SHIPMENT_GID::dropdownPopup::content::db']/table/tbody/tr</value>
      <webElementGuid>b369c34e-2c04-4527-99f4-f60c6d38ca9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::tr[2]</value>
      <webElementGuid>baa6100a-dca6-41c3-8337-2dd53309fc99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::tr[2]</value>
      <webElementGuid>2a636262-ee19-447c-b7c6-2d0487bbbee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/table/tbody/tr</value>
      <webElementGuid>87019219-f3ae-4495-afc4-4ce0fca4fcb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tr[@selected = 'true' and (text() = '1000020' or . = '1000020')]</value>
      <webElementGuid>4880a734-6642-4b99-ad0c-66b046b9c519</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
