<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tr_Cancel_acSelItem</name>
   <tag></tag>
   <elementGuidId>3b3432fd-54f4-4453-83fd-7c06a414f96d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='driver/home_location_xid::dropdownPopup::content::db']/table/tbody/tr</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.acSelItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;driver\/home_location_xid\:\:dropdownPopup\:\:content\:\:db&quot;] >> internal:role=row[name=&quot;ORG-TPA&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tr</value>
      <webElementGuid>deed772f-f294-405c-8dca-216bfc58f6e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gid</name>
      <type>Main</type>
      <value>BXC.ORG-TPA</value>
      <webElementGuid>54f8c691-cdfb-4ad4-9ad2-bd1cf508f864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xid</name>
      <type>Main</type>
      <value>ORG-TPA</value>
      <webElementGuid>cdf0b0ed-4af6-4c6e-b6de-9e4da7ef9684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldid</name>
      <type>Main</type>
      <value>driver/home_location_xid</value>
      <webElementGuid>15902f38-1a0f-49a9-afaf-d9a068acc46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ba0e1802-edeb-4de7-96a6-9476a6594abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>acSelItem</value>
      <webElementGuid>384ec108-71d3-4c32-a751-fc8f8d294a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d8f09d76-670e-4590-9de5-330960a2b697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ORG-TPA</value>
      <webElementGuid>b9691823-0b08-431e-931e-9e930fcf3860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;driver/home_location_xid::dropdownPopup::content::db&quot;)/table[@class=&quot;acTable&quot;]/tbody[1]/tr[@class=&quot;acSelItem&quot;]</value>
      <webElementGuid>f89dfd3b-23a2-4991-90ec-e2abffd9abfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/driver3/Page_DRIVER Finder/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>e7664e75-3e6e-4fc4-9045-b1ad7c294981</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='driver/home_location_xid::dropdownPopup::content::db']/table/tbody/tr</value>
      <webElementGuid>d9fc184a-fa46-4b30-99e7-a37226dabe2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[4]/following::tr[2]</value>
      <webElementGuid>dcb22537-4427-4ecf-956c-49a9ab4d0b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[4]/following::tr[2]</value>
      <webElementGuid>1e7de360-7be4-4edd-b0d2-c2fe53f06a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/table/tbody/tr</value>
      <webElementGuid>c0435e8e-7dfa-455c-b119-cdd74bbcf84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tr[@selected = 'true' and (text() = 'ORG-TPA' or . = 'ORG-TPA')]</value>
      <webElementGuid>684caad0-4527-486f-882d-2a288c4396b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
