<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , actionFrame, , ))_actionFrame_1</name>
   <tag></tag>
   <elementGuidId>75682f3e-f4d6-4eb2-bb3f-047565e8c148</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='actionFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#actionFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;actionFrame&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2f248c7e-33a5-4e02-ae91-360580a864aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actionFrame</value>
      <webElementGuid>895a392e-44ea-455b-a23c-23527386bb13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionFrame</value>
      <webElementGuid>4911657e-b9b8-4c0f-b2b9-e3a1aeb2f754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iWinFrame</value>
      <webElementGuid>39d7a1a6-5e6a-4fcb-aeae-765bf1f7c22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>61c3be63-c178-4c2e-8208-34a5edaffc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>5c71d1e0-f6cd-47ce-8a2e-d92b20806162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.finder.ActionServlet/1748958554112?bcKey=MTc0ODk1ODU1NDExMzow&amp;query_name=glog.server.query.order.OrderReleaseQuery&amp;finder_set_gid=ORDER_RELEASE_WO_STOP</value>
      <webElementGuid>8751ee81-2391-4f55-8a86-4c0a2de34592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pageloaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ffb81543-6dda-4fa4-9f9d-425db2b8d52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionFrame&quot;)</value>
      <webElementGuid>de4e568e-6ce0-4d2f-8691-195615ff41ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Order Releases Result/iframe_PRAJYOT.DABHADEBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>c722a526-9d0c-4495-ae87-7b16332bdcab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='actionFrame']</value>
      <webElementGuid>88ab5fa4-76ce-441f-bd4c-734502425802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/iframe</value>
      <webElementGuid>1755611e-4237-4dc8-8bb1-348d67c10de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'actionFrame' and @id = 'actionFrame' and @src = '/GC3/glog.webserver.finder.ActionServlet/1748958554112?bcKey=MTc0ODk1ODU1NDExMzow&amp;query_name=glog.server.query.order.OrderReleaseQuery&amp;finder_set_gid=ORDER_RELEASE_WO_STOP']</value>
      <webElementGuid>f221ab82-1827-4bcb-85c6-be6d27b23d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'actionFrame' and @id = 'actionFrame' and @src = '/GC3/glog.webserver.finder.ActionServlet/1747289087042?bcKey=MTc0NzI4OTA4NzA0Mzow&amp;query_name=glog.server.query.order.OrderReleaseQuery&amp;finder_set_gid=ORDER_RELEASE_WO_STOP']</value>
      <webElementGuid>f908738f-bb68-4d76-8897-7ba6fe6196cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
