<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create Sell Shipment</name>
   <tag></tag>
   <elementGuidId>a0ea1d34-c391-4405-a9be-ea4a3a060270</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='actionTree.1_6_2.l']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Create Sell Shipment&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bce794ff-092e-4b6e-b227-705eb088d5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionTree.1_6_2.l</value>
      <webElementGuid>413267fe-6c3d-44fd-a480-c2d77de5c943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>oc</value>
      <webElementGuid>7dab6372-5c18-4940-aec6-e545a1a37f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>l</value>
      <webElementGuid>8a88ee73-6a19-4592-9116-6b5d8d7a8292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>7f4b0dc6-29fb-47f3-9d9f-abb2ac3f44df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Sell Shipment</value>
      <webElementGuid>2d632b3c-6320-4659-90f3-a3da73e609a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionTree.1_6_2.l&quot;)</value>
      <webElementGuid>2b6bd9ff-744d-4085-bfdb-2fb888ab92bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Order Releases Result/iframe_concat(id(, , actionFrame, , ))_actionFrame</value>
      <webElementGuid>ef480eca-e8cb-4315-b06c-2f2c2a2acfda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='actionTree.1_6_2.l']</value>
      <webElementGuid>c4bb797e-e2e9-48d0-b954-778a75c9ce38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='actionTree.1_6_2']/td/span[2]</value>
      <webElementGuid>88936f2f-cad3-45bd-b244-7329df3f481a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Routing Options'])[1]/following::span[2]</value>
      <webElementGuid>2622dfdf-355e-4a4e-97f0-d72594402d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Network Routing Options - Ocean'])[1]/following::span[4]</value>
      <webElementGuid>6de60902-6dba-4470-887a-d3761ef87f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build Sell Shipment On Primary Leg'])[1]/preceding::span[2]</value>
      <webElementGuid>36ac9cbd-af8b-47b1-ad72-1b688b51b8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build Sell Shipment On Primary Leg Show Consol Options'])[1]/preceding::span[4]</value>
      <webElementGuid>60b280b9-c305-42cf-b768-2bad7346ff06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Sell Shipment']/parent::*</value>
      <webElementGuid>9ba6bb16-74dc-4e61-8c1e-73fa51b88347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td/div/table/tbody/tr[3]/td/span[2]</value>
      <webElementGuid>4e79662a-b0e0-4fc7-a32d-b03412a282ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'actionTree.1_6_2.l' and @type = 'oc' and (text() = 'Create Sell Shipment' or . = 'Create Sell Shipment')]</value>
      <webElementGuid>abc78a72-4128-496b-829c-83c7b79bbd6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
