<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_To Item_pt1_FOr11_FONSr20MAt30pt1ap1sRelFl1RelatedItemResultsip21searchIcoIdicon</name>
   <tag></tag>
   <elementGuidId>375ffc8c-f2fe-4cd4-8f89-efd2967572ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sRelFl:1:RelatedItemResults:ip21:searchIcoId::icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Search: To Item&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ceb4264d-478b-459d-961f-1a75e0ed23a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sRelFl:1:RelatedItemResults:ip21:searchIcoId::icon</value>
      <webElementGuid>e7ebc44f-2972-4d99-bac5-33b15d97761b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/fscmUI/images/func_search_16_hov.png</value>
      <webElementGuid>f26c8944-81f5-4678-adb0-411c26edcfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search: To Item</value>
      <webElementGuid>316c6de4-306f-418a-930e-cbf14fc8c875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Search: To Item</value>
      <webElementGuid>16274a66-e6d9-4ad9-9c30-0485d96164d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xi6</value>
      <webElementGuid>2b306eaf-493f-4a9f-b258-dd65cb0cd387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sRelFl:1:RelatedItemResults:ip21:searchIcoId::icon&quot;)</value>
      <webElementGuid>2852ddcb-4261-486d-9721-bc162b63e439</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sRelFl:1:RelatedItemResults:ip21:searchIcoId::icon']</value>
      <webElementGuid>150d3183-b0b5-411d-a4c8-0451b04aa7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sRelFl:1:RelatedItemResults:ip21:searchIcoId']/img</value>
      <webElementGuid>b5767e0f-53b3-4056-a794-950c9d7c88f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Search: To Item']</value>
      <webElementGuid>232d2186-e40d-4bc7-b617-8ae45bb72df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/table/tbody/tr/td/a/img</value>
      <webElementGuid>10fda7fc-9c86-46c6-ba4f-83b0bc3ca8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sRelFl:1:RelatedItemResults:ip21:searchIcoId::icon' and @src = '/fscmUI/images/func_search_16_hov.png' and @title = 'Search: To Item' and @alt = 'Search: To Item']</value>
      <webElementGuid>12cc57d9-e392-4668-913a-a07f152d3f78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
