<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item_pt1_FOr11_FONSr20MAt30pt1ap1sRelFl1RelatedItemResultsip21Popup10Advan10efqrpvalue00</name>
   <tag></tag>
   <elementGuidId>366c677a-37fd-4484-ae46-2a8b1496a89b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sRelFl:1:RelatedItemResults:ip21:Popup1:0:Advan1:0:efqrp:value00::content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;**Item Item Item **Description Description Description&quot;i] >> internal:label=&quot;Item&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fd22f87-2efe-43b5-83bf-bac2cf385945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sRelFl:1:RelatedItemResults:ip21:Popup1:0:Advan1:0:efqrp:value00::content</value>
      <webElementGuid>8cb0d7df-66a3-4768-a35f-6aecf41989df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sRelFl:1:RelatedItemResults:ip21:Popup1:0:Advan1:0:efqrp:value00</value>
      <webElementGuid>26c7ab78-ae4d-4b4e-a46a-2d9b67ad6876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x25</value>
      <webElementGuid>aaf779cc-1cf8-421b-8977-58c71a960a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>5e9342f6-21e3-4bf9-a9ed-d56f46efbcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>acac728d-abdf-443c-9b1f-9b4a2faa457e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>357ef052-21d0-40e7-9418-30ae8853e585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dde02516-dbdb-4976-a260-925d9649b1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ab4a108f-b94d-415d-9ae3-d1d010e8a983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value> Item</value>
      <webElementGuid>60261a41-6a0e-4491-9714-4bcc60962ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sRelFl:1:RelatedItemResults:ip21:Popup1:0:Advan1:0:efqrp:value00::content&quot;)</value>
      <webElementGuid>05be7727-e832-44e1-8d96-b81ccc956c69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sRelFl:1:RelatedItemResults:ip21:Popup1:0:Advan1:0:efqrp:value00::content']</value>
      <webElementGuid>bb8938f4-f14e-4074-ab63-037172a37ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sRelFl:1:RelatedItemResults:ip21:Popup1:0:Advan1:0:efqrp:value00']/input</value>
      <webElementGuid>c0e1a794-cb95-44c7-835f-d32eb7290084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[2]/table/tbody/tr/td[2]/table/tbody/tr/td/span/input</value>
      <webElementGuid>f3acd048-e4ca-4d8e-b475-73f0356bd296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sRelFl:1:RelatedItemResults:ip21:Popup1:0:Advan1:0:efqrp:value00::content' and @name = 'pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:sRelFl:1:RelatedItemResults:ip21:Popup1:0:Advan1:0:efqrp:value00' and @type = 'text']</value>
      <webElementGuid>1283ec7d-0972-42ff-bbf6-e01a0ae87443</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
