<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shipment</name>
   <tag></tag>
   <elementGuidId>9f2e90fd-5fa6-4a99-b9f8-45bf8377042d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tabDim.tabLabelCont > div > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='finder_tab.shipment']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Shipment&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e70824ea-fb8b-4054-898a-7fea878ee917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ead3d29b-2d3f-4df1-949d-8f357a57365f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>2e7316df-63ad-47d7-9bcd-8e2ac3a376e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>21f4bf01-b78a-4aa0-8579-51ddbc66f842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>47cd153a-b9fc-49b6-a81e-b0095e0d05fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>df8df828-87fe-4ae1-8c34-9b6fa8a7e07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:showFrame('finder_tab.shipment')</value>
      <webElementGuid>8930c82a-0ad1-46ce-8559-db9c9d409432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shipment</value>
      <webElementGuid>629ea70b-cd3b-48c2-bbb9-18a9b8c95633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;finder_tab.shipment&quot;)/div[@class=&quot;tabDim tabLabelCont&quot;]/div[1]/a[1]</value>
      <webElementGuid>0889f1d1-04c5-4a79-a05a-90269ba568b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Buy Shipments Finder/iframe_PRAJYOT.DABHADEBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>b8026680-ca85-4d1b-8c3c-234b3f712826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='finder_tab.shipment']/div/div/a</value>
      <webElementGuid>6bae7ea4-ddaf-4069-91c9-012b6b018b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Shipment')]</value>
      <webElementGuid>b509b46c-3626-4f64-9f47-fc30721aae55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Shipments Finder'])[2]/following::a[2]</value>
      <webElementGuid>dfaeac87-6302-427e-9794-2d1863e482f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transport'])[1]/preceding::a[1]</value>
      <webElementGuid>4c08a6c8-1592-4522-8665-6a15293ea3c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[1]/preceding::a[2]</value>
      <webElementGuid>2eaa5e9c-c6ef-46dc-bc95-a90947c3eaa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shipment']/parent::*</value>
      <webElementGuid>b9b30002-80ac-428c-af86-16eac3e8c513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:showFrame('finder_tab.shipment')&quot;)]</value>
      <webElementGuid>38ff67fc-169a-4e37-8832-a107e807e6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>cd9c26ac-964c-4dbb-be14-de940acca9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:showFrame(&quot; , &quot;'&quot; , &quot;finder_tab.shipment&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Shipment' or . = 'Shipment')]</value>
      <webElementGuid>8baed390-3328-44f2-aaab-9c96607ec307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
