<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_PRAJYOT.DABHADEBLUELINXCO.COM_mainIFrame</name>
   <tag></tag>
   <elementGuidId>9c93f0f0-a74c-4b41-9ff7-f6c4af293f1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainIFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainIFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mainIFrame</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>70eed7ab-58db-49e0-be66-53cc32ac3f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainIFrame</value>
      <webElementGuid>690ade2d-f6b7-441f-93e3-eea093a5e6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oj-web-applayout-content-nopad</value>
      <webElementGuid>bc878760-4ebd-4e50-9ee6-1d235e98f429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>mainIFrameOnLoad()</value>
      <webElementGuid>dfe1c64b-a7f9-4f67-a4d5-e74afb7ed9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr : {src: IFRAME_URL}</value>
      <webElementGuid>89e64899-0598-4f1d-ae04-f7334e7c1a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.finder.FinderServlet?bcKey=new&amp;query_name=glog.server.query.shipment.BuyShipmentQuery&amp;finder_set_gid=BUY_SHIPMENT</value>
      <webElementGuid>37f80bb5-9ddf-4eb7-abf3-8e5f4141e732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainIFrame&quot;)</value>
      <webElementGuid>45d9d694-25da-4ef4-a4d9-13d4d0b5ef41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainIFrame']</value>
      <webElementGuid>0d583663-b0a4-48cc-bc0e-8521ccd563c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//oj-module[@id='mainModule']/iframe</value>
      <webElementGuid>485ceb1c-341b-4e9c-9ac1-b912c94afd11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7fc39d33-eca3-4337-8e07-91069839b2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'mainIFrame' and @src = '/GC3/glog.webserver.finder.FinderServlet?bcKey=new&amp;query_name=glog.server.query.shipment.BuyShipmentQuery&amp;finder_set_gid=BUY_SHIPMENT']</value>
      <webElementGuid>7be4347d-62f3-4aba-99a4-d3322814d194</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
