<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Fleet Unassign</name>
   <tag></tag>
   <elementGuidId>1a21a1ad-f880-40e7-814e-1185a30ca24b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='actionTree.1_17_4.l']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Fleet Unassign&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>81ba5116-d0c9-42fd-b5c3-19de94ea6742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionTree.1_17_4.l</value>
      <webElementGuid>f453ed7a-07c0-4c68-821b-c244c39ea391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>oc</value>
      <webElementGuid>065f5cb1-6600-4e4b-8dda-d4229174bf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>l</value>
      <webElementGuid>47fc2359-744b-4990-b685-73ca124a89f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>48b75d2f-6550-4638-8405-ffe7e3a7ac5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fleet Unassign</value>
      <webElementGuid>056589d4-8dc1-4c98-a22f-02d9626aca51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionTree.1_17_4.l&quot;)</value>
      <webElementGuid>7c062b6e-6d78-4e6d-a8de-7f60875f20c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Folder (1)/Page_Buy Shipment Result/iframe_concat(id(, , actionFrame, , ))_actionFrame_1</value>
      <webElementGuid>6686d250-a223-4715-bda8-77c60b3622ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='actionTree.1_17_4.l']</value>
      <webElementGuid>85cc9fe5-451a-4a50-82c9-b9e959563dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='actionTree.1_17_4']/td/span[2]</value>
      <webElementGuid>4f066683-781b-4397-b249-60d4ff6793eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Dispatch'])[1]/following::span[2]</value>
      <webElementGuid>0bafb4f8-ed5e-46ac-a4dd-58ba4b24d2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Withdraw Dispatch'])[1]/following::span[4]</value>
      <webElementGuid>a1d68f93-1c33-4a2f-b602-da02066a5ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Driver'])[3]/preceding::span[2]</value>
      <webElementGuid>7d9e778c-f962-4675-b281-33edb8c19fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Power Unit'])[3]/preceding::span[4]</value>
      <webElementGuid>f4d99f73-b316-4584-b7bc-cdc6ed4b9244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fleet Unassign']/parent::*</value>
      <webElementGuid>40f4b274-b889-47da-95fa-9b207c3f6feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[21]/td/div/table/tbody/tr[7]/td/span[2]</value>
      <webElementGuid>f5575b04-56ec-4c91-a0f8-fa4e4cd6c654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'actionTree.1_17_4.l' and @type = 'oc' and (text() = 'Fleet Unassign' or . = 'Fleet Unassign')]</value>
      <webElementGuid>874190ae-0188-44e3-ba6d-8a94f419522a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
