<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Shipment_finder</name>
   <tag></tag>
   <elementGuidId>4b0fedd2-5cc2-47f9-b0d2-56bc545ccb20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;RootPane_1_1_region_0_moduleRegion_addReplaceRowsPopup&quot;]/div[1]/div[2]/div/div/iframe</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
