<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>9d8e58d3-a7f6-49a2-96cb-0d5a8c9d01d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='search_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad58e72a-51c4-4fe1-9ece-dd3438da3160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4434b81a-b55c-4bea-8e42-54c3d11c2c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_button</value>
      <webElementGuid>d062348f-bd2f-4d03-8c9e-96bca9f9c569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enButton</value>
      <webElementGuid>dd6bbf2f-aeb1-4dc0-b4b4-38648d557d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>function t() { this.focus(); return performMainSearch('Search'); return true; } if(t.call(this) !== false) { javascript:void(1); } else { return false; }</value>
      <webElementGuid>f51d7642-5a5c-41aa-bb81-bbdf10f4df1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_button</value>
      <webElementGuid>9a5f973a-ad72-40c9-8959-dbbe365797c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>mainBody</value>
      <webElementGuid>6c7d1e8f-a39b-42a3-90c9-84c7f4e45e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>77f5b75b-d781-4d13-a442-0e3aef532db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_button&quot;)</value>
      <webElementGuid>2e747b05-3023-4f97-8c07-ad4da0f4977e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Itinerary Finder/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>a009d67c-bc9b-4565-9ef0-ae61732f594e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='search_button']</value>
      <webElementGuid>4994fa8e-46a3-4de8-9c20-23533caf4e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyDataFooterContDiv']/table/tbody/tr/td/div/button</value>
      <webElementGuid>86e89683-f9ea-490a-8673-ee1eb79f549c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Both'])[1]/following::button[1]</value>
      <webElementGuid>026c5257-a68b-4b21-a84c-b2ba4ba54da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::button[1]</value>
      <webElementGuid>dbdf17be-e45d-4587-9443-175e72bb401c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[1]/preceding::button[1]</value>
      <webElementGuid>4dad7160-a2fc-4837-826b-f5b89a9c5e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort Order'])[1]/preceding::button[2]</value>
      <webElementGuid>b9a83bc2-7ced-4b03-a84c-77233f6a5d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>1321b9dd-1e40-427d-a97b-4f8673e8b7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2a822248-84ca-4967-9a66-6e92fdfc6be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'search_button' and @id = 'search_button' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>98d5d3f8-48c5-43d8-abab-8619d36d3699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COFC/TOFC'])[1]/following::button[1]</value>
      <webElementGuid>d14ffd0a-5214-42ad-974e-c9101ca3b097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer or Shipper Rate'])[1]/following::button[1]</value>
      <webElementGuid>49bf0e20-c77a-4aa9-b29c-8e11698628a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
