<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Contact Preferences__FOpt1_FOr10_FONSr20M_fd8c0f</name>
   <tag></tag>
   <elementGuidId>008169af-600f-4962-9a9b-81b607e3304f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[11]/div[2]/div/div/div/div[2]/div/div[2]/table/tbody/tr/td[4]/span/span/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Expand Email Email&quot;i] >> a >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ecf424d7-b655-419f-8e23-4babf6cc3981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bd5e4b3e-de3e-4000-aed0-c0a9e8705556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1kv</value>
      <webElementGuid>a826c2ba-2288-4227-ac51-11d0a0baf090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r12:0:AT1:_ATp:table1:1:soc1::drop</value>
      <webElementGuid>11d29881-f203-4b66-aa69-d4893f37f2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r12:0:AT1:_ATp:table1:1:soc1::drop&quot;)</value>
      <webElementGuid>faa52aaa-aa37-41d2-8cad-c58e62876bbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r12:0:AT1:_ATp:table1:1:soc1::drop']</value>
      <webElementGuid>dcbf61cf-d9bb-4980-8a66-c99cfc9575f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r12:0:AT1:_ATp:table1:1:soc1::cntrl']/a</value>
      <webElementGuid>03af0300-31cf-4ace-9e90-9c6837ff9c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/div/div/div/div[2]/div/div[2]/table/tbody/tr/td[4]/span/span/span/a</value>
      <webElementGuid>4ec8c6de-44a2-4329-9722-97e24817253d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r12:0:AT1:_ATp:table1:1:soc1::drop']</value>
      <webElementGuid>aee04691-72a1-422b-a53b-527413df6886</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
