<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fax__FOpt1_FOr10_FONSr20MAnt21r10AP3r110A_cbb84e</name>
   <tag></tag>
   <elementGuidId>81031d8c-f48d-4eb9-8254-b82abf9738ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r11:0:AT1:_ATp:table1:0:soc1::drop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Expand Land Phone Country Code Phone Country Code Search: Phone Country Code Autocompletes on TAB Area Code Area Code Phone Phone Extension Extension&quot;i] >> a >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>547d9e1d-d765-4d03-9c4b-69ea9d59ccd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9f0890ca-bcdf-4507-a9a3-1e4e5f4f1b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1kv</value>
      <webElementGuid>4057527f-30d9-42b2-b190-7d4d04c23818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r11:0:AT1:_ATp:table1:0:soc1::drop</value>
      <webElementGuid>3f23c0e0-0b39-4555-96be-2bca68d7031b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r11:0:AT1:_ATp:table1:0:soc1::drop&quot;)</value>
      <webElementGuid>a02f44c0-d4c7-47c4-a5e1-8d4143e5758e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r11:0:AT1:_ATp:table1:0:soc1::drop']</value>
      <webElementGuid>d3c7b486-633e-49a3-a79a-041cabe27c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r11:0:AT1:_ATp:table1:0:soc1::cntrl']/a</value>
      <webElementGuid>53ef9f93-a108-4f59-8b6f-4677f5a8e060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div/div/div[2]/div/div[2]/table/tbody/tr/td[5]/span/span/span/a</value>
      <webElementGuid>d97455d3-4941-4098-96c3-20872d1fb215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r1:0:AP3:r11:0:AT1:_ATp:table1:0:soc1::drop']</value>
      <webElementGuid>12a48f8f-463d-4ea2-ab93-f7adfae91526</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
