<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Primary Phone_pt1_FOr11_FONSr20MAnt21r100_b55e81</name>
   <tag></tag>
   <elementGuidId>56b9f65b-8e29-41f6-b4bf-636a69260812</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:r10:0:ap1:sdh1::_afrDscl&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Expand Notes&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4618b729-d3e3-4262-bf5e-d7e5b1f0d0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42bb00fb-9db4-4e02-b84d-4c6a630caa0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7172310f-f936-4be9-8064-e6ed1b28314f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:MAnt2:1:r10:0:ap1:sdh1::content</value>
      <webElementGuid>6b585de4-095e-4670-914a-848e07a4e2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Expand Notes</value>
      <webElementGuid>53b2c170-a406-4f18-bb25-28f0861bfce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>71bc4f2f-10f4-4d5f-8555-c89dcefbde8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.focus();return false</value>
      <webElementGuid>c35dc882-a51d-4020-9cef-2589aa295e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1b1 x1tp</value>
      <webElementGuid>535bbef1-fcad-4471-86c9-289bf8b168d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:MAnt2:1:r10:0:ap1:sdh1::_afrDscl</value>
      <webElementGuid>125e73a0-5b39-4773-8427-f39cffcadc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Expand Notes</value>
      <webElementGuid>62c42e64-a814-456b-86dc-5e8bc3c517e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:MAnt2:1:r10:0:ap1:sdh1::_afrDscl&quot;)</value>
      <webElementGuid>0f158cce-0c5c-400b-a856-7a083fc4323c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pt1:_FOr1:1:_FONSr2:0:MAnt2:1:r10:0:ap1:sdh1::_afrDscl']</value>
      <webElementGuid>a80e5a7e-24a9-4c04-8549-6365e5678fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pt1:_FOr1:1:_FONSr2:0:MAnt2:1:r10:0:ap1:sdh1']/div/table/tbody/tr/td/a</value>
      <webElementGuid>1978c40d-7d23-4a84-8f30-ffa9b9938c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[30]</value>
      <webElementGuid>191239a5-dc65-4f83-9c9b-417b18783cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/div/div/table/tbody/tr/td/a</value>
      <webElementGuid>47345fd8-0d66-4cf4-ab3c-969261c716d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'pt1:_FOr1:1:_FONSr2:0:MAnt2:1:r10:0:ap1:sdh1::_afrDscl' and @title = 'Expand Notes']</value>
      <webElementGuid>af0fe1a6-9504-4013-b4b7-0b728341da4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
