<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Arial</name>
   <tag></tag>
   <elementGuidId>0ea87de9-99e1-48b1-8a29-067e842e152e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[1]/following::li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Arial&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0a040b6e-e808-4274-bf6e-dffc208bdcd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1l7</value>
      <webElementGuid>9f749d70-ccbe-4c9d-ac45-98c93f41f043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_adfiv</name>
      <type>Main</type>
      <value>Arial,Helvetica,sans-serif</value>
      <webElementGuid>f680bcb0-934d-469b-b2d5-f50759bccb53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Arial</value>
      <webElementGuid>aabc0353-da6c-4fc7-bad1-0cef11be383b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:MAnt2:1:r10:0:ap1:r3:0:AT1:r1:1:richText1_afrFontFace::pop&quot;)/li[@class=&quot;x1l7&quot;]</value>
      <webElementGuid>a40b3acb-8e1f-4a01-b6a3-952e9a4f1b30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pt1:_FOr1:1:_FONSr2:0:MAnt2:1:r10:0:ap1:r3:0:AT1:r1:1:richText1_afrFontFace::pop']/li[2]</value>
      <webElementGuid>b11d0765-7042-4173-8f96-2ed87a970e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a Font'])[2]/following::li[2]</value>
      <webElementGuid>ec220a73-6a11-44d2-b97e-ca6b7b459834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[1]/following::li[2]</value>
      <webElementGuid>a4c7baff-2de0-4425-866f-69c5ed795506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Courier New'])[1]/preceding::li[1]</value>
      <webElementGuid>a212ab23-001f-4dca-93e6-f66aed9b5ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comic Sans'])[1]/preceding::li[2]</value>
      <webElementGuid>80ae2775-239e-4eda-a02f-c608d2a1421a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Arial']/parent::*</value>
      <webElementGuid>aa7f687b-f018-4f90-b5b7-9e1c9b86c207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/ul/li[2]</value>
      <webElementGuid>ece4ec43-7634-470e-92f0-0d31710482a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Arial' or . = 'Arial')]</value>
      <webElementGuid>aa1070a8-bf14-41e1-b1a9-c3f43f059453</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
