<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Move_pt1_FOr11_FONSr20MAt40pt1ap1r21AT1Ap_f53be1</name>
   <tag></tag>
   <elementGuidId>5951f69f-c0e2-43ae-b400-aa180d8b091b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pt1:_FOr1:1:_FONSr2:0:MAt4:0:pt1:ap1:r2:1:AT1:AppTe:0:selectManyShuttle1::moveall']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Move all items to: Selected List&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f41b1778-4d33-4733-9721-8843eada1b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ac35bf16-30b8-4319-ae4b-394a98df9f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>23025397-a8b5-4abc-a477-d2b14d301bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.focus();return false</value>
      <webElementGuid>edbc26f3-5043-494c-a4a2-fb43697aaf05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1ff</value>
      <webElementGuid>6724b8e2-d3ca-40d3-9f77-4c79074b4e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:MAt4:0:pt1:ap1:r2:1:AT1:AppTe:0:selectManyShuttle1::moveall</value>
      <webElementGuid>df2bc8d6-14d9-403b-b32d-a4d4cb86ac82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Move all items to: Selected List</value>
      <webElementGuid>044b0ded-5949-431e-910b-3374ae14f217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:MAt4:0:pt1:ap1:r2:1:AT1:AppTe:0:selectManyShuttle1::moveall&quot;)</value>
      <webElementGuid>b8357cfa-5e94-48b5-a60a-6ff7fd454135</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pt1:_FOr1:1:_FONSr2:0:MAt4:0:pt1:ap1:r2:1:AT1:AppTe:0:selectManyShuttle1::moveall']</value>
      <webElementGuid>3824c4b6-5a6e-434a-b8b5-ee4b60c0f021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pt1:_FOr1:1:_FONSr2:0:MAt4:0:pt1:ap1:r2:1:AT1:AppTe:0:selectManyShuttle1::moveDiv']/table[2]/tbody/tr/td/div/a</value>
      <webElementGuid>6958eccf-685b-4e8e-822b-704aa7d88193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[92]</value>
      <webElementGuid>62ef8b43-d79f-4379-9839-6994c142363e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/table[2]/tbody/tr/td/div/a</value>
      <webElementGuid>bdb7fcb4-d11b-49d4-91dd-75aef99b371c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'pt1:_FOr1:1:_FONSr2:0:MAt4:0:pt1:ap1:r2:1:AT1:AppTe:0:selectManyShuttle1::moveall' and @title = 'Move all items to: Selected List']</value>
      <webElementGuid>8651c70e-0644-4169-befd-1608f5d06270</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
