<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select Hours_pt1_FOr11_FONSr20MAt30pt1ap1_486e51</name>
   <tag></tag>
   <elementGuidId>fdafd0d9-3938-400d-8ddc-2925cf8f60fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:SelCh:0:r1:1:t1:0:id2::pop::dlg::cd::hs::increment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Select Hours increment decrement&quot;s] >> internal:attr=[title=&quot;increment&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d769adc1-fce0-4a72-b972-0eeeeac17569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cc26dec9-4a15-412a-ae90-0689e3536f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>25633cca-24cf-4119-baa9-97f110b4e325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x130</value>
      <webElementGuid>4dd5d968-bc05-469f-a5f1-690d9fc9cbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:SelCh:0:r1:1:t1:0:id2::pop::dlg::cd::hs::increment</value>
      <webElementGuid>4068b025-aeeb-4a3a-bf89-d68ce9476c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>increment</value>
      <webElementGuid>7a642ff8-fc05-4e89-89d5-6a447623a288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:SelCh:0:r1:1:t1:0:id2::pop::dlg::cd::hs::increment&quot;)</value>
      <webElementGuid>b9521415-51f1-4803-a8c3-2f61113653b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:SelCh:0:r1:1:t1:0:id2::pop::dlg::cd::hs::increment']</value>
      <webElementGuid>995987c4-5b09-4922-9ca3-73c5577d683a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:SelCh:0:r1:1:t1:0:id2::pop::dlg::cd::hs']/table/tbody/tr/td[2]/div/a</value>
      <webElementGuid>cd8b42aa-23a4-42e6-aa62-51b692afe3ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr/td/div/table/tbody/tr/td[2]/div/a</value>
      <webElementGuid>16b45b0a-44c0-4c10-8190-31390bfa76ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pt1:_FOr1:1:_FONSr2:0:MAt3:0:pt1:ap1:SelCh:0:r1:1:t1:0:id2::pop::dlg::cd::hs::increment' and @title = 'increment']</value>
      <webElementGuid>29d09553-7759-4b30-b8dd-0f6f350e6bb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
