<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Created By</name>
   <tag></tag>
   <elementGuidId>4d1b30de-bef5-46a5-818f-87401d66fcfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.p_AFSelected.p_AFFocused.xem > td:nth-of-type(2) > div > table > tbody > tr > td.xen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic'])[1]/following::td[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Created By&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e9f450f8-1fb8-46ea-92f1-c1bdb618350b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xen</value>
      <webElementGuid>b051b403-dea0-4885-a4b7-fd678cd42e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_afrndcol</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>00289538-571e-41f3-94ec-1daf43171537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9e3004e6-3d11-4db0-80e2-e089fb8d78ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Created By</value>
      <webElementGuid>993bce71-42f5-488d-8bec-e2e233babb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:MAt2:0:pt1:ItemC1:0:simplePanel1:region2:0:shuttleRnIdAddFields:0:ATR4:_ATTp:ATRr4::db&quot;)/table[@class=&quot;x1hi x1i6&quot;]/tbody[1]/tr[@class=&quot;p_AFSelected p_AFFocused xem&quot;]/td[2]/div[1]/table[1]/tbody[1]/tr[1]/td[@class=&quot;xen&quot;]</value>
      <webElementGuid>ca678469-8987-42b4-b766-992393d3266c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pt1:_FOr1:1:_FONSr2:0:MAt2:0:pt1:ItemC1:0:simplePanel1:region2:0:shuttleRnIdAddFields:0:ATR4:_ATTp:ATRr4::db']/table[2]/tbody/tr[2]/td[2]/div/table/tbody/tr/td</value>
      <webElementGuid>6b51d3d9-88ad-4a2e-bce7-02dc9255adf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval Status'])[2]/following::td[3]</value>
      <webElementGuid>1269ba3e-1db9-4073-a6f0-ba866663cfc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic'])[1]/following::td[7]</value>
      <webElementGuid>b68548b1-d095-4f58-ba2c-83cf807f741a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creation Date'])[1]/preceding::td[3]</value>
      <webElementGuid>7136e971-9ab0-4f8b-b2a6-c44d5aae44a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[2]/td[2]/div/table/tbody/tr/td</value>
      <webElementGuid>ad45d2e5-024c-4e86-89ca-9ff08a0fb542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Created By' or . = 'Created By')]</value>
      <webElementGuid>cc5a2bbe-8e7f-426a-bbef-34278da75182</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
