<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_DEV2 TESTING ENVIRONMENT_svg-outline</name>
   <tag></tag>
   <elementGuidId>68d037fc-8a0c-4531-89a7-26faa1398d86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Home&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>d8301ab6-8cdc-4d20-a7ef-14e48a3e93cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-outline</value>
      <webElementGuid>c23964b8-a166-4b36-9914-2955996e8bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M25 25V10L14 3L3 10V25H25Z</value>
      <webElementGuid>b0da8695-6145-441a-954d-3e4daf36d84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_UIShome::icon&quot;)/g[4]/path[@class=&quot;svg-outline&quot;]</value>
      <webElementGuid>8551279d-3c1e-4bef-9934-856093aa856a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
