<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shipment_s_equipment_joins_equipmentxid</name>
   <tag></tag>
   <elementGuidId>48b0a635-a82f-4589-a7ea-efec912f049c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shipment_s_equipment_join/s_equipment/xid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Shipment Equipment&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fb4e462-9a84-445a-abca-a3c44b6725a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Shipment Equipment</value>
      <webElementGuid>3a3614da-70d3-4c4f-b4ce-d0be9f4dc9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4c464d2d-f3c9-410e-a1d3-80fe16e167f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb886262-ac9d-4599-9e29-078918a073b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>bdfac1e8-016a-45f4-83de-24a2158f9650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>325ede9a-05d7-4b93-99e0-9ebcd7b4b396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipment_s_equipment_join/s_equipment/xid</value>
      <webElementGuid>44263bbd-c633-41eb-80b1-09c7cc6b235a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shipment_s_equipment_join/s_equipment/xid</value>
      <webElementGuid>da2f1534-2f5c-411f-a2da-dd905f02cd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b22ce97d-f698-4110-84a3-1d60f692412e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>autoCompleteKeyEventListener(event, 'shipment_s_equipment_join/s_equipment/xid');pickListHandler('glog.server.query.shipment.SEquipmentQuery','management_main','shipment_s_equipment_join\x2Fs_equipment\x2Fxid','Shipment\x20Equipment','false','false','false','false','','','','','','Please\x20pass\x20in\x20a\x20valid\x20argument','BXC',event,'single','','false','');</value>
      <webElementGuid>0bfdf94f-fe26-4e6e-8393-22497c035543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>autoCompleteKeyEventListener(event, 'shipment_s_equipment_join/s_equipment/xid');</value>
      <webElementGuid>962bb399-eeaf-446d-8df9-05b2cb864088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>autoCompleteHandler('glog.server.query.shipment.SEquipmentQuery','management_main','shipment_s_equipment_join\x2Fs_equipment\x2Fxid','','','','Please\x20pass\x20in\x20a\x20valid\x20argument',event,'','false','3');</value>
      <webElementGuid>7f82d059-6ef3-49d0-b232-e8a15d200d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>return onPickBlur(this,false);</value>
      <webElementGuid>9b547ed5-a70d-43be-8730-9f37368dafa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shipment_s_equipment_join/s_equipment/xid&quot;)</value>
      <webElementGuid>d52fb7ea-1056-46a7-ab9f-35abadd837a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Buy Shipment - Equipment/iframe_PRAJYOT.DABHADEBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>518c35f1-69c7-4256-aca7-e1ba8927d216</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shipment_s_equipment_join/s_equipment/xid']</value>
      <webElementGuid>8765a65d-f8f7-4c4b-b420-0176675994a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_shipment_s_equipment_join_grid']/tbody/tr/th/div/table/tbody/tr/td/input</value>
      <webElementGuid>8a80cfe9-6a1b-441d-ac29-1be6c6275fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>09dac740-02be-4111-8a9c-29932305a318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'shipment_s_equipment_join/s_equipment/xid' and @id = 'shipment_s_equipment_join/s_equipment/xid']</value>
      <webElementGuid>240986aa-a029-4453-9920-4b5853091480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
