<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Domain Name_Selected</name>
   <tag></tag>
   <elementGuidId>a2e86731-d5ee-46ce-8c18-c5abd2ec1320</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Selected&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Selected']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;BXC.1000&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2cbeaebd-94a5-4f9e-bd9a-ee60eec5e42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>BXC.1000</value>
      <webElementGuid>8e34ae7f-f4b3-4ab4-98ad-7ce629c47196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d89fcab0-e0dc-4d1d-9b31-5f8ba905d944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>resultGrid.selectRow(this);handleSelectionOnServer(finderSetGid, callerID,'BXC.1000', this)</value>
      <webElementGuid>e8cb4efb-87da-42e8-b2c1-477bbf9a9341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BXC.1000</value>
      <webElementGuid>782ff8be-62b4-4131-b51e-b1b4b77829db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b8922c32-6d2e-4b16-bea2-6870aed1edf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Selected</value>
      <webElementGuid>182934a0-72f5-4154-a98f-134466dc3f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sgBodyCheck</value>
      <webElementGuid>94337229-b116-425a-83ed-3437d47c6019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rgSGSec.2.1.1.1&quot;)/input[@class=&quot;sgBodyCheck&quot;]</value>
      <webElementGuid>600d9fc0-e94f-4f7d-a842-d2e6f4be0dde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Selected']</value>
      <webElementGuid>fd1cb3f4-3695-4bed-9d67-5a32dfe0082d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rgSGSec.2.1.1.1']/input</value>
      <webElementGuid>fba38d95-fe74-4be0-8ea0-50cffaf41a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>232d7bf7-a3df-44d3-aa7a-ddcce026e849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'Selected']</value>
      <webElementGuid>e02fbe1a-cbee-48dd-b491-f41db1a2aea1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
