<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Execute Query</name>
   <tag></tag>
   <elementGuidId>c2e5d856-58cf-4412-8e63-5a09c84b43ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@name=''])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>table.box > tbody > tr > td:nth-of-type(3) > div.buttonCont > button.enButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Execute Query&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>740d82fd-401a-425b-b997-f56cec01579a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a9310c5b-1ab9-403d-8db0-11530d90583c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enButton</value>
      <webElementGuid>25225102-871b-494b-86fa-3e1c7fbf529a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>function t() { return performMainSearch('Execute'); return true; } if(t.call(this) !== false) { javascript:void(1); } else { return false; }</value>
      <webElementGuid>3e7354c4-f7fb-4db3-a031-932f5006ee14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Execute Query</value>
      <webElementGuid>5d4723d9-910c-4464-983d-c97b690d3f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyDataFooterContDiv&quot;)/table[@class=&quot;buttonsCont&quot;]/tbody[1]/tr[1]/td[5]/table[@class=&quot;box&quot;]/tbody[1]/tr[1]/td[3]/div[@class=&quot;buttonCont&quot;]/button[@class=&quot;enButton&quot;]</value>
      <webElementGuid>33d98761-77ad-4702-914c-d2c63f97f81b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name=''])[4]</value>
      <webElementGuid>08162da7-c551-44c5-a9fd-05ace492bb3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyDataFooterContDiv']/table/tbody/tr/td[5]/table/tbody/tr/td[3]/div/button</value>
      <webElementGuid>d2c5eb7c-b8c4-4327-ba36-ba7faf057c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saved Query:'])[1]/following::button[1]</value>
      <webElementGuid>880fd177-b883-47e6-8b26-7bd35ab2cfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/following::button[1]</value>
      <webElementGuid>06cc3edd-e5f7-4e9b-a1b3-24377d0f0459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[2]/preceding::button[1]</value>
      <webElementGuid>b827aaf7-d613-4562-b836-bc108213772a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::button[2]</value>
      <webElementGuid>201d869c-8ac5-4a82-87e6-3255f3b74a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Execute Query']/parent::*</value>
      <webElementGuid>5a53f4ed-20a2-4b7b-ade0-3ea5f82ed264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/table/tbody/tr/td[3]/div/button</value>
      <webElementGuid>b16c34f0-3544-411c-8b72-2a3f39b4670e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Execute Query' or . = 'Execute Query')]</value>
      <webElementGuid>52ffd534-f7a1-4480-b935-e057c3ca95e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
