<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Order Management</name>
   <tag></tag>
   <elementGuidId>1a1ea77d-44cf-455a-ae21-f4847c753c79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='label2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#label2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Menu&quot;s >> internal:text=&quot;Order Management&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ee7f10dc-372f-4dc8-9b05-59f0afc13060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:id</name>
      <type>Main</type>
      <value>[[getLabelId(menu.index)]]</value>
      <webElementGuid>714b959b-0130-4510-a997-13da930c640f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tm-text-align-center tm-sb-tile-label</value>
      <webElementGuid>70fece08-8db8-47a7-a312-ba0521da7c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:style</name>
      <type>Main</type>
      <value>[[{'color':theme_main_font_color}]]</value>
      <webElementGuid>9d755091-8be9-47fe-a534-4f49f58b6d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>label2</value>
      <webElementGuid>b38e799b-c9c0-4671-8728-f4383a0308a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Order Management
                </value>
      <webElementGuid>90376f5e-bc78-4c23-b965-1d9dd13a7676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;label2&quot;)</value>
      <webElementGuid>ac84f579-2da5-4b7c-8329-b48e6f6557b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='label2']</value>
      <webElementGuid>164c3a2d-206a-4186-831d-5cb91601bf6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sb_1']/div/div/div[2]</value>
      <webElementGuid>1cbb8c57-c74a-4520-b7a9-6163d0c0ed17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open in New Window'])[5]/following::div[5]</value>
      <webElementGuid>bf9d4e45-1467-4b8a-bcec-333f51c5aa75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open in New Window'])[6]/preceding::div[1]</value>
      <webElementGuid>0bfc5d93-f330-415e-93f0-785568227ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]</value>
      <webElementGuid>8d610c38-b095-4d58-a14d-0d9fca9b8316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'label2' and (text() = '
                  Order Management
                ' or . = '
                  Order Management
                ')]</value>
      <webElementGuid>dc5febbb-77c4-4c4a-a1ad-27c8d7fb09d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
