<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_COLLAZO_GIL_20060548</name>
   <tag></tag>
   <elementGuidId>32f08f3d-2704-4c8c-adfa-de8780b2e6b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='rgSGSec.2.2.1.17.k']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;COLLAZO_GIL_20060548&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>39038c42-f66e-431c-9f97-ee61b1830ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rgSGSec.2.2.1.17.k</value>
      <webElementGuid>1e79f680-e5b5-41fc-a8af-56138460f50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c9f0c802-b926-4632-a4e8-c54c7fffe664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>eb7e9015-2d5f-441b-afe5-f7ead6348334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:OpenViewForFinderResult('glog.server.query.driver.DriverQuery', 'resultsPage:result', 'input_2_1_17', 'Driver\x20ID','','COLLAZO_GIL_20060548','BXC.COLLAZO_GIL_20060548');</value>
      <webElementGuid>3914add4-ac48-4ff9-893f-13556887d2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COLLAZO_GIL_20060548</value>
      <webElementGuid>cf6340e4-349e-4e39-a81c-e4ad79e7103d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rgSGSec.2.2.1.17.k&quot;)</value>
      <webElementGuid>255eb172-d839-4c3e-a274-ab38efc6645f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Buy Shipment Result/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame (1)</value>
      <webElementGuid>7008800b-0427-4a6a-90eb-28a2a7d0cc53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='rgSGSec.2.2.1.17.k']</value>
      <webElementGuid>cc19f6f4-c79e-4c12-9684-5e49b780d084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rgSGSec.2.2.1.17']/a</value>
      <webElementGuid>f40e0c78-815b-42e9-9624-d490fa7f00e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'COLLAZO_GIL_20060548')]</value>
      <webElementGuid>de3193c0-0aab-4c50-bc14-3020747f6d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FLEET'])[1]/following::a[1]</value>
      <webElementGuid>8ab46ec4-9c5c-4d6c-9d55-f32ffcf87623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NWK'])[1]/following::a[2]</value>
      <webElementGuid>2ba450e3-4ff9-4295-8f76-3894c88494b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENROUTE_NOT STARTED'])[1]/preceding::a[2]</value>
      <webElementGuid>97c6aebd-397f-464a-bfc9-808319c057aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BXC'])[1]/preceding::a[2]</value>
      <webElementGuid>8d4e3575-aa26-4bda-bf4f-0bd6a194e57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COLLAZO_GIL_20060548']/parent::*</value>
      <webElementGuid>34f02435-f7e9-47e4-aebc-6a7c8024e9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[8]</value>
      <webElementGuid>55440577-a9e4-4fb6-adee-01d2444ca28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/a</value>
      <webElementGuid>62990650-0c31-448e-8eaa-ece44317b4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'rgSGSec.2.2.1.17.k' and @href = 'javascript:void(0);' and (text() = 'COLLAZO_GIL_20060548' or . = 'COLLAZO_GIL_20060548')]</value>
      <webElementGuid>21995be1-51b3-4067-9ef6-9016e58964b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
