<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , actionFrame, , ))_actionFrame</name>
   <tag></tag>
   <elementGuidId>93c1d0e2-9c32-471e-ba6a-ddb510b1495d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='actionFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#actionFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;actionFrame&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>38e82c81-3739-4e4e-a56e-446c89a04e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actionFrame</value>
      <webElementGuid>afe955d9-3ad6-457c-928f-8a486c92412e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionFrame</value>
      <webElementGuid>3ee71476-dab7-4651-bc15-f634fb213de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iWinFrame</value>
      <webElementGuid>dab6e495-9624-47cc-ae4a-215c791c4c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>90ff0883-e9b3-4f7c-8efb-f2af1e983f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d162fa11-9e89-4a5f-9e8c-b75882a75ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.finder.ActionServlet/1747652938907?bcKey=MTc0NzY1MjkzODkwODow&amp;query_name=glog.server.query.shipment.BuyShipmentQuery&amp;finder_set_gid=BXC.BXC_BUY_SHIPMENT_UPDATE</value>
      <webElementGuid>3ce072a8-85c0-43ac-bf59-51e2c9054abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pageloaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f50871dc-6431-4240-bffb-0312ac2a64e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionFrame&quot;)</value>
      <webElementGuid>52022c01-000e-430d-9e49-3f543cae23ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Buy Shipment Result/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>26d56341-6aa9-451d-baf9-68c5f401dc7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='actionFrame']</value>
      <webElementGuid>76bcee72-f626-4472-a915-471ce7a2cbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/iframe</value>
      <webElementGuid>b27a326d-df0c-4d65-970e-d7c07b7d3341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'actionFrame' and @id = 'actionFrame' and @src = '/GC3/glog.webserver.finder.ActionServlet/1747652938907?bcKey=MTc0NzY1MjkzODkwODow&amp;query_name=glog.server.query.shipment.BuyShipmentQuery&amp;finder_set_gid=BXC.BXC_BUY_SHIPMENT_UPDATE']</value>
      <webElementGuid>01e3d880-9529-42e8-ade9-c44a72e52d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'actionFrame' and @id = 'actionFrame' and @src = '/GC3/glog.webserver.finder.ActionServlet/1747652029240?bcKey=MTc0NzY1MjAyOTI0MTow&amp;query_name=glog.server.query.shipment.BuyShipmentQuery&amp;finder_set_gid=BXC.BXC_BUY_SHIPMENT_UPDATE']</value>
      <webElementGuid>22a6f7a7-9e2f-413b-899e-285d9f4a28f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
