<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , mainBodyFrame, , ))_mainBody</name>
   <tag></tag>
   <elementGuidId>1610344c-c21d-4a78-a8e3-37f920b3cd0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainBodyFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainBodyFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;mainBody&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>db569dbf-d318-4423-8895-9a676da216ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframeBody</value>
      <webElementGuid>ce34a359-14d8-4916-9a40-764ef915299f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>057bec44-df41-42b8-b934-06980d13a130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mainBody</value>
      <webElementGuid>26c46ea0-1617-4f35-aa8c-f78d3d2686aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainBodyFrame</value>
      <webElementGuid>a3aece5e-c8e7-49b3-b827-c04f38c696c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.util.QueryResponseServlet/1751456823215?bcKey=new&amp;action_name=assign_driver_to_shipment&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.TESTSHP768</value>
      <webElementGuid>6346013f-5a9f-47b3-8f7d-0f19baaf9ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainBodyFrame&quot;)</value>
      <webElementGuid>917f1491-ff12-40c4-8820-b0d744e6af8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainBodyFrame']</value>
      <webElementGuid>c12fee08-9021-4036-98a6-1f5a01120dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>1fbe40bf-cea9-479c-af3f-329267f6f10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1751456823215?bcKey=new&amp;action_name=assign_driver_to_shipment&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.TESTSHP768']</value>
      <webElementGuid>ef4206e5-995a-48c6-bd3d-d30c6dc3fa8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1747755423644?bcKey=new&amp;action_name=assign_driver_to_shipment&amp;finder_set_gid=BXC.BXC_BUY_SHIPMENT&amp;pk=BXC.8000']</value>
      <webElementGuid>2227eedd-01ae-4c74-b230-2c06ff083551</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
