<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Relationships</name>
   <tag></tag>
   <elementGuidId>6c2eed7c-3379-42d5-8d13-62e7442b5086</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:realtionship::text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Relationships&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bb362e3f-7a8e-452c-82ff-4412c705b6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:realtionship::text</value>
      <webElementGuid>a9d75d02-45bf-4b54-81f2-a7d06db55afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xod</value>
      <webElementGuid>b6f9a665-49d0-4585-bcc3-bc681190e8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Relationships</value>
      <webElementGuid>50602d9f-18b5-489d-9793-d12547c309ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:realtionship::text&quot;)</value>
      <webElementGuid>bcd67872-3dcb-4145-9f32-53e6a7641596</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:realtionship::text']</value>
      <webElementGuid>05dd1d88-59cd-48cf-9953-4cc0c8da0ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:realtionship::disAcr']/div</value>
      <webElementGuid>b36faab9-553c-479b-a5dd-dadf00010e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usage Assignments'])[1]/following::div[3]</value>
      <webElementGuid>79d54a32-5190-45f9-8a24-c33e38f11939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile History'])[1]/following::div[6]</value>
      <webElementGuid>1be546b6-30c2-452e-a40a-23a86ace9a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source System References'])[1]/preceding::div[1]</value>
      <webElementGuid>f8b9e1b3-1a42-4088-a1e7-975113fa6f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hierarchy Memberships'])[1]/preceding::div[4]</value>
      <webElementGuid>4ba23aaf-35a2-42fd-9342-5bde790866d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Relationships']/parent::*</value>
      <webElementGuid>40af656e-9e3c-4076-a4cc-b6094855909b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a/div</value>
      <webElementGuid>9cb8e09d-e233-4eff-875d-184bf47b94ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:1:realtionship::text' and (text() = 'Relationships' or . = 'Relationships')]</value>
      <webElementGuid>12a9b687-83a8-4d29-a65b-15fefaad86b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
