<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create Buy Shipment</name>
   <tag></tag>
   <elementGuidId>5e77ba75-f771-4243-8259-6fb274940a8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='actionTree.1_3_1.l']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Create Buy Shipment&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2a861943-a523-4176-8e6d-4d0c5a650cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionTree.1_3_1.l</value>
      <webElementGuid>93067a40-9ef6-48b1-a624-a6ced036ecbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>oc</value>
      <webElementGuid>adf539a1-b9f6-452a-815e-587cd1ee733b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>l</value>
      <webElementGuid>f122d0b4-e851-4dd8-8e09-7fa29d6aa152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>c236c39f-b8f0-4523-9f9a-a7b7fda7f378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Buy Shipment</value>
      <webElementGuid>4fc43736-5238-4592-a4fb-8f9da4b55e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionTree.1_3_1.l&quot;)</value>
      <webElementGuid>51953ac1-1c15-452e-869f-3d5b97401106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Order Release Result/iframe_concat(id(, , actionFrame, , ))_actionFrame</value>
      <webElementGuid>17edd15f-c3b6-47ed-9786-3d50c59de9b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='actionTree.1_3_1.l']</value>
      <webElementGuid>4db5159c-e8ff-4b89-bdd8-1e1d443a80f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='actionTree.1_3_1']/td/span[2]</value>
      <webElementGuid>2dda9815-d16f-4722-8b8d-55a6e65c7456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operational Planning'])[1]/following::span[2]</value>
      <webElementGuid>51b6732a-c47f-4661-8e32-4bfa547748ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign General Ledger Codes - Buy'])[1]/following::span[4]</value>
      <webElementGuid>252dc2aa-4dbd-4638-9066-6b2135e4b11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulk Plan - Buy'])[1]/preceding::span[2]</value>
      <webElementGuid>e51a7d4f-33a0-4e0d-b0b7-0e94f53b8f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manually Assign to Existing Shipment'])[1]/preceding::span[4]</value>
      <webElementGuid>7e213246-ef29-44bd-9e86-f3955a22ff8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Buy Shipment']/parent::*</value>
      <webElementGuid>a1230b36-f23b-4998-9e57-2c6ec761276a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/div/table/tbody/tr/td/span[2]</value>
      <webElementGuid>4cd87003-9295-4875-98a7-179a41a17600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'actionTree.1_3_1.l' and @type = 'oc' and (text() = 'Create Buy Shipment' or . = 'Create Buy Shipment')]</value>
      <webElementGuid>6af54bb1-f617-4b96-b422-ab14f1968be3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
