<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , bodyDataDiv, , ))_actionFrame</name>
   <tag></tag>
   <elementGuidId>97ffc62d-e810-428e-b8a0-5ffde4ab8975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='actionFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#actionFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;actionFrame&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>cff1666c-ece9-48a2-899f-00b0b15408ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actionFrame</value>
      <webElementGuid>7d4a01e6-f581-4b90-bc75-0062fbc6549c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionFrame</value>
      <webElementGuid>c4865f49-b480-43fa-9fba-1ed8d0343a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iWinFrame</value>
      <webElementGuid>d99a5d1f-2162-43a6-b374-c6bd13ff7d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1b0923a0-eff8-4e95-b2ff-b587bbf4bcee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c78ca9c1-b9a5-4085-9e40-06e981201ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.finder.ActionServlet/1750343709238?bcKey=MTc1MDM0MzcwODg5OTow&amp;query_name=glog.server.query.shipmentstatus.IeShipmentstatusQuery&amp;finder_set_gid=IE_SHIPMENTSTATUS</value>
      <webElementGuid>b0347595-f208-4bf3-b87e-421943a1e148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pageloaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>69c550ab-2368-4174-9f0d-26f4d423a3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>actionmenucallingwinname</name>
      <type>Main</type>
      <value>mainBody</value>
      <webElementGuid>cf1d0ab2-6a54-4b0c-baa1-1a92ceb7b463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionFrame&quot;)</value>
      <webElementGuid>ab75fee2-859c-4ed1-a10b-8ab01eb9ce50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tracking Event/iframe_concat(id(, , mainBodyFrame, , ))_mainBody</value>
      <webElementGuid>1798c0bf-d6b8-481c-8f79-1abefea2d777</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='actionFrame']</value>
      <webElementGuid>f72ac64a-b7eb-47ec-bfe5-73b30e5c2b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>14465a83-505b-48d7-ae67-db3be559f651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'actionFrame' and @id = 'actionFrame' and @src = '/GC3/glog.webserver.finder.ActionServlet/1750343709238?bcKey=MTc1MDM0MzcwODg5OTow&amp;query_name=glog.server.query.shipmentstatus.IeShipmentstatusQuery&amp;finder_set_gid=IE_SHIPMENTSTATUS']</value>
      <webElementGuid>b35e4498-4ab0-42d7-9d41-3b4fac4cb97a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
