<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Driver IDEarliest Start TimeLatest End TimeNo data to display.Select Row</name>
   <tag></tag>
   <elementGuidId>ed34341e-b118-42ed-a2ae-100cd95b95ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RootPane_2_2_region_0_moduleRegion_tableWrapperId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RootPane_2_2_region_0_moduleRegion_tableWrapperId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#RootPane_2_2_region_0_moduleRegion_tableWrapperId</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>143e362a-7d5e-4000-97c4-54a6e11c9295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:id</name>
      <type>Main</type>
      <value>[[getContainerId() + '_tableWrapperId']]</value>
      <webElementGuid>607359cc-610f-4479-a594-a2cf54b3cbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableWrapperClass</value>
      <webElementGuid>2a97b7bb-e052-4849-a5be-ae833e970504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RootPane_2_2_region_0_moduleRegion_tableWrapperId</value>
      <webElementGuid>e2993b9b-dc28-4e26-aa8e-239dedb59e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Driver IDEarliest Start TimeLatest End TimeNo data to display.Select Row
        </value>
      <webElementGuid>6874ce42-a24f-4d58-8ff2-fd3b00b2ba9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RootPane_2_2_region_0_moduleRegion_tableWrapperId&quot;)</value>
      <webElementGuid>820d5f45-036d-4307-8db0-161f7d19a8b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='RootPane_2_2_region_0_moduleRegion_tableWrapperId']</value>
      <webElementGuid>abc72d01-aa14-4f58-a0e9-c58e0272cb17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//oj-module[@id='RootPane_2_2']/div[3]/div/div</value>
      <webElementGuid>ff5bcb31-be1e-4767-8c8f-3210f1e70756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[8]/following::div[3]</value>
      <webElementGuid>e847b68c-5675-4382-bd95-2505acd02e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[8]/following::div[4]</value>
      <webElementGuid>123dd19c-4e31-4c80-b012-07cec2443540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//oj-module/div[3]/div/div</value>
      <webElementGuid>bea40aa1-d010-4646-a433-2f872a29aa39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'RootPane_2_2_region_0_moduleRegion_tableWrapperId' and (text() = '
            Driver IDEarliest Start TimeLatest End TimeNo data to display.Select Row
        ' or . = '
            Driver IDEarliest Start TimeLatest End TimeNo data to display.Select Row
        ')]</value>
      <webElementGuid>ccc18e38-370c-45f2-a2d8-4cb093d350d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
