<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_html1frameset1frame1_W287</name>
   <tag></tag>
   <elementGuidId>6b40f00c-b79c-44e8-9381-6cca7fb152dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;W287&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>frame[name=&quot;W287&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>10058779-e019-4f66-ac36-acb01ee43663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>388cff3d-8175-4f78-974c-d2cde2fd17a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>noresize</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1f790afb-f316-4a3c-8728-0136a6f228d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W287</value>
      <webElementGuid>ceed9396-ff05-4686-a958-8bb1a10fd7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/jetshell?bcKey=MTc0Nzc1NDYxMTA5Njox&amp;ojr=workbench&amp;layout=BXC.BXC_VIEW_SHIPMENTS&amp;fromMenu=true</value>
      <webElementGuid>601e168c-d7bf-4ae7-9760-a799960d7dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>f81dce4d-c045-49a6-8851-5b415c65d9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Transportation Workbench/iframe_concat(id(, , mainBodyFrame, , ))_mainBody</value>
      <webElementGuid>e950d170-4980-43c6-a0e4-9c8906ad5f35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='W287']</value>
      <webElementGuid>69b52bb4-6766-407a-9c55-d192998352b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>c217af5f-5b58-4b49-8caf-0e369a554501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'W287' and @src = '/GC3/jetshell?bcKey=MTc0Nzc1NDYxMTA5Njox&amp;ojr=workbench&amp;layout=BXC.BXC_VIEW_SHIPMENTS&amp;fromMenu=true']</value>
      <webElementGuid>6f4e333d-01df-44bf-833d-05370d769893</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
