<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_html1frameset1frame1_W290</name>
   <tag></tag>
   <elementGuidId>ff8c97c1-a602-4e7a-b544-fffe5f7dae8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;W290&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>frame[name=&quot;W290&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>b3dee9d4-87b5-458b-b38e-5ed10761b55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a613faea-be50-4908-b5d7-65a29d2d2eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>noresize</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ea735d62-e2e8-4e81-8f96-8dea4651e0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W290</value>
      <webElementGuid>dd4da905-ac17-42ae-9ae4-7de06d47633f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/jetshell?bcKey=MTc0Nzc1NzkzNTYzNDox&amp;ojr=workbench&amp;layout=BXC.BXC_VIEW_SHIPMENTS&amp;fromMenu=true</value>
      <webElementGuid>6ca630ca-2179-49da-b1ef-3affc99d3b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>9c7e12eb-edac-4c12-84fc-96293a9b82a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Transportation Workbench/iframe_concat(id(, , mainBodyFrame, , ))_mainBody_1</value>
      <webElementGuid>5735cb69-f7c1-4f50-8db8-6a77bd812206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='W290']</value>
      <webElementGuid>76c4c357-894a-4ae4-96e7-b703b4f82845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>393cfa76-f3e9-4f06-b7ab-73cc85ad76d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'W290' and @src = '/GC3/jetshell?bcKey=MTc0Nzc1NzkzNTYzNDox&amp;ojr=workbench&amp;layout=BXC.BXC_VIEW_SHIPMENTS&amp;fromMenu=true']</value>
      <webElementGuid>369bded5-cdeb-4bc9-bdbd-6304b1d5956e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
