<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , mainBodyFrame, , ))_mainBody</name>
   <tag></tag>
   <elementGuidId>0a2fc0b0-2b2a-43dc-a800-0127b91308b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainBodyFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainBodyFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;mainBody&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>aec5329f-615b-4369-8360-dba1902c4932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframeBody</value>
      <webElementGuid>a0805822-cc36-4652-b42f-8e9152fa1143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>cd947625-adcb-468a-b191-578812c8f6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mainBody</value>
      <webElementGuid>75c60807-bad6-4eec-a3ee-0664a75b9f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainBodyFrame</value>
      <webElementGuid>66fb30b3-a327-4623-9b12-86f8678393e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.util.QueryResponseServlet/1750246402654?bcKey=new&amp;action_name=map_related_shipments&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.TESTSHP01234</value>
      <webElementGuid>b0bcf03c-1fa8-4734-bdf4-0abeabd83f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainBodyFrame&quot;)</value>
      <webElementGuid>9f46bbac-f2e3-48c7-b76e-461101ef709d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainBodyFrame']</value>
      <webElementGuid>2df7861d-ec8d-4378-a8ab-e4786bba30e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>5c92bd7c-868d-46b1-bab4-8dc4e51735c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1750246402654?bcKey=new&amp;action_name=map_related_shipments&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.TESTSHP01234']</value>
      <webElementGuid>f7287654-47c1-411e-9e0e-a048dde7d4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1748351350589?bcKey=new&amp;action_name=map_related_shipments&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.49011']</value>
      <webElementGuid>a8010e45-7a1e-44b9-ab31-939534834ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1747754588548?bcKey=new&amp;action_name=map_related_shipments&amp;finder_set_gid=BUY_SHIPMENT&amp;management_action=go&amp;finder_set_gid=BUY_SHIPMENT&amp;pk=BXC.8000']</value>
      <webElementGuid>ceac9d9c-1c14-4823-8f79-d7db13bc9e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1747289087042?bcKey=new&amp;action_name=map_order_release&amp;finder_set_gid=ORDER_RELEASE_WO_STOP&amp;management_action=go&amp;finder_set_gid=ORDER_RELEASE_WO_STOP&amp;pk=BXC.SO_329_3856']</value>
      <webElementGuid>2ebaafe7-566e-4571-8b8f-0945d9424793</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
