<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Rate Costs</name>
   <tag></tag>
   <elementGuidId>218e749d-40cc-40f1-93af-7dead4ad0e3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@name=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Rate Costs&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>33c91368-9c8d-42bf-b34e-169cac3388bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>29b658f3-92be-4cc0-93aa-be55cdcedc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>5f01b733-c59f-4bfa-b660-fa49a75963fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>c5dbc803-8521-49c8-8786-2c51e1c67e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>97dcc824-db1d-4aae-ae61-c47acda3c5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1a3b6df8-26ba-4b6e-bdf7-156f98cd13bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript: if(checkData('management_main')){document.forms['management_main'].action='/GC3/glog.webserver.util.DocumentUpdateServlet/1747206173000?bcKey=MTc0NzIwNjE1OTcwNjox'; document.forms['management_main'].redirect.value='/GC3/glog.webserver.rate.RateGeoManagementServlet/1747206173000?bcKey=MTc0NzIwNjE1OTcwNjox&amp;rate_geo_stylesheet=rate/RateGeoCost.xsl';document.forms['management_main'].submit();}</value>
      <webElementGuid>3341df2e-d1ff-4cd3-a417-c6135ff59964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rate Costs</value>
      <webElementGuid>102c167c-cd20-4ee7-a651-0a944581ae27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rate/RateGeoCost.xsl&quot;)/div[@class=&quot;tabLabelCont tabDim&quot;]/span[1]/a[1]</value>
      <webElementGuid>bd5a2dfa-22e2-4a92-a0db-9a3e09c3bfb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Rate Record - Attributes/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>b445ee3a-b122-4ac1-ae82-8ebbf3a13f56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@name=''])[2]</value>
      <webElementGuid>373199b8-5e5c-42e5-963d-119f0cc7479d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rate/RateGeoCost.xsl']/div/span/a</value>
      <webElementGuid>e218345b-8efd-476a-bfb2-8beb57aee45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Rate Costs')]</value>
      <webElementGuid>76145a59-b49e-4048-ae32-509fd89017ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attributes'])[1]/following::a[1]</value>
      <webElementGuid>8563bac2-d11f-4fb0-8435-687babdc2f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lane Info'])[1]/following::a[1]</value>
      <webElementGuid>58e69c0f-538a-4e6c-90d5-18aaf4b006c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessorials'])[1]/preceding::a[1]</value>
      <webElementGuid>a96fbd99-f039-451c-8996-24fb9d0675b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Services'])[1]/preceding::a[2]</value>
      <webElementGuid>4a43ae8a-dade-4b07-b1d3-4a3c9ca86edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rate Costs']/parent::*</value>
      <webElementGuid>149d4544-e6c2-49a2-bf6f-d692a38727c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript: if(checkData('management_main')){document.forms['management_main'].action='/GC3/glog.webserver.util.DocumentUpdateServlet/1747206173000?bcKey=MTc0NzIwNjE1OTcwNjox'; document.forms['management_main'].redirect.value='/GC3/glog.webserver.rate.RateGeoManagementServlet/1747206173000?bcKey=MTc0NzIwNjE1OTcwNjox&amp;rate_geo_stylesheet=rate/RateGeoCost.xsl';document.forms['management_main'].submit();}&quot;)]</value>
      <webElementGuid>10e85a89-c2b5-4c3b-a8b2-9cadb634e15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/a</value>
      <webElementGuid>3663b034-d951-428b-ae7b-052736268fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript: if(checkData(&quot; , &quot;'&quot; , &quot;management_main&quot; , &quot;'&quot; , &quot;)){document.forms[&quot; , &quot;'&quot; , &quot;management_main&quot; , &quot;'&quot; , &quot;].action=&quot; , &quot;'&quot; , &quot;/GC3/glog.webserver.util.DocumentUpdateServlet/1747206173000?bcKey=MTc0NzIwNjE1OTcwNjox&quot; , &quot;'&quot; , &quot;; document.forms[&quot; , &quot;'&quot; , &quot;management_main&quot; , &quot;'&quot; , &quot;].redirect.value=&quot; , &quot;'&quot; , &quot;/GC3/glog.webserver.rate.RateGeoManagementServlet/1747206173000?bcKey=MTc0NzIwNjE1OTcwNjox&amp;rate_geo_stylesheet=rate/RateGeoCost.xsl&quot; , &quot;'&quot; , &quot;;document.forms[&quot; , &quot;'&quot; , &quot;management_main&quot; , &quot;'&quot; , &quot;].submit();}&quot;) and (text() = 'Rate Costs' or . = 'Rate Costs')]</value>
      <webElementGuid>d06b60c5-bb5a-401f-af20-1447f9f2b2ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
