<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Folders_pt1_FOr11_FONSr20_FOTRaTj_id_3_3cd855</name>
   <tag></tag>
   <elementGuidId>fb77df60-a154-4a58-b5d8-fd83a69c19bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pt1:_FOr1:1:_FONSr2:0:_FOTRaTj_id_3:1:tree:1::di']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Expand FolderShared Reports and Analytics&quot;i] >> internal:attr=[title=&quot;Expand&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bebaf613-1e1a-4a72-b034-fa0450cfff50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>49dcbd56-9eb6-4b85-a886-3dc340677ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.focus();return false</value>
      <webElementGuid>53812649-1172-4ea4-b5fa-27965ff91cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x19y</value>
      <webElementGuid>b1bfb663-1e3d-4349-bdbe-84a1952b6bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:_FOTRaTj_id_3:1:tree:1::di</value>
      <webElementGuid>b2f26b50-3c0a-41a9-90eb-d52f786d8815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Expand</value>
      <webElementGuid>2cb63b24-98e7-435c-9d2e-b50c24da7ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:_FOTRaTj_id_3:1:tree:1::di&quot;)</value>
      <webElementGuid>9ba1a420-ba56-42c9-ad27-3f308731e12a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pt1:_FOr1:1:_FONSr2:0:_FOTRaTj_id_3:1:tree:1::di']</value>
      <webElementGuid>b8207f40-a782-415a-8812-b0ef99d2d96a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pt1:_FOr1:1:_FONSr2:0:_FOTRaTj_id_3:1:tree::db']/table/tbody/tr[2]/td/div/span/a</value>
      <webElementGuid>0c542c2c-9004-460a-b530-0941a28e090d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[58]</value>
      <webElementGuid>d0967464-b5f0-4495-8d7d-dac84f2bcccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/span/a</value>
      <webElementGuid>7a8dced7-7bad-45f1-b48b-ec9f83c3f6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'pt1:_FOr1:1:_FONSr2:0:_FOTRaTj_id_3:1:tree:1::di' and @title = 'Expand']</value>
      <webElementGuid>73fbabeb-f6cd-4c5f-8df4-2e21e9d6d896</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
