<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_PrintMe__FOpt1_FOr10_FONSr20_FOTsdiItem_3ddbb3</name>
   <tag></tag>
   <elementGuidId>0fe0f5e2-06b6-4f73-af7a-1b7a24de6e55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Tasks']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Tasks&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2f512870-ed6d-4172-bae4-22febfba4e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:_FOTsdiItemRegionalArea::icon</value>
      <webElementGuid>d5dab128-8879-430e-ad51-f64cae6f60ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/fscmUI/images/func_panellist_32_ena.png</value>
      <webElementGuid>32768948-0f19-4947-8111-246a3005037b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tasks</value>
      <webElementGuid>02b403b1-e48c-4baf-a587-37507ecbd538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Tasks</value>
      <webElementGuid>2f7141c3-f081-48d5-8b84-b9d50541d5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x1gh</value>
      <webElementGuid>e124ef47-3b96-465a-9fc9-1f07159b52a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:_FOTsdiItemRegionalArea::icon&quot;)</value>
      <webElementGuid>aa360f77-43f2-4609-b2fe-291d715a1841</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='_FOpt1:_FOr1:0:_FONSr2:0:_FOTsdiItemRegionalArea::icon']</value>
      <webElementGuid>0f842251-8f0d-42f2-a95b-edfe4cea6dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:_FOTsdiItemRegionalArea::disAcr']/img</value>
      <webElementGuid>3aa09656-d22b-418f-aac9-ba7d3651e62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Tasks']</value>
      <webElementGuid>98dcc9bc-aadf-4d65-8d96-0bbadfe1d2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a/img</value>
      <webElementGuid>ff06e036-ed20-4b64-b39e-2fd618ba466b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '_FOpt1:_FOr1:0:_FONSr2:0:_FOTsdiItemRegionalArea::icon' and @src = '/fscmUI/images/func_panellist_32_ena.png' and @title = 'Tasks' and @alt = 'Tasks']</value>
      <webElementGuid>48efe9ce-a888-4327-b9a7-71c38da1fc56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
