<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Driver ID_driver_xid_find</name>
   <tag></tag>
   <elementGuidId>bceb3036-da19-40ca-9a88-568c65d75db7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='driver_xid_find']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;driver_xid_find&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Driver ID Search&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d880424-b9ce-4225-9ea7-32b1a2d5dc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>ba3955e2-4e94-47f6-8960-b31f5c71f74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>67d4e6aa-ea5a-4b91-8216-cc34ae3d289c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>211a9467-0b42-43cc-a7a3-eb93539fea57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Driver ID Search</value>
      <webElementGuid>7c048882-e964-45a6-8a06-eca794aedcb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(1);</value>
      <webElementGuid>40807070-86b4-4581-b7a1-1acbc60b25e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pickListFinderLink</value>
      <webElementGuid>8650913c-8976-4616-9244-9b42c06c3d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OpenPickList('glog.server.query.driver.DriverQuery', 'management_main', 'driver_xid', 'false', 'single', '', '', '', '', '','','','');</value>
      <webElementGuid>1c17969a-3b6e-4145-937f-c925ef69ae17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>driver_xid_find</value>
      <webElementGuid>c999903a-0635-4dc7-8807-7c13d66fc802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manualshipmentdriver&quot;)/div[@class=&quot;fieldCont&quot;]/table[@class=&quot;noTbSp&quot;]/tbody[1]/tr[1]/td[2]/table[@class=&quot;noTbSp&quot;]/tbody[1]/tr[1]/td[1]/a[@class=&quot;pickListFinderLink&quot;]</value>
      <webElementGuid>ce7b0a20-8e0b-41eb-b5c1-dba4f837d34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Folder (1)/Page_Assign Driver to Shipment - Override Criteria/iframe_mainBody</value>
      <webElementGuid>ac10c92a-4486-4142-9ac2-30586f9930a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='driver_xid_find']</value>
      <webElementGuid>e72ce023-1936-4346-bb0f-ea759734cbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='manualshipmentdriver']/div/table/tbody/tr/td[2]/table/tbody/tr/td/a</value>
      <webElementGuid>2392b5a1-ddb6-4ec3-beca-fb04c5d52644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(1);')])[21]</value>
      <webElementGuid>302a07b1-369b-4f34-b376-725af2a1fdff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[2]/div/table/tbody/tr/td[2]/table/tbody/tr/td/a</value>
      <webElementGuid>91f2476a-7580-488c-95bc-c7e018f2d711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Search' and @alt = 'Search' and @href = 'javascript:void(1);' and @name = 'driver_xid_find']</value>
      <webElementGuid>e7c15f8b-dfd2-43b1-8a93-69adffc6f735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
