<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_mainBody</name>
   <tag></tag>
   <elementGuidId>68cfa405-5ebd-403e-bdd6-0d8378607411</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainBodyFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainBodyFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;mainBody&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>49330398-763f-462b-9cb7-3cbc86d862cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframeBody</value>
      <webElementGuid>f25c8ce2-cd44-41e4-ae50-cdf3bfdef976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>032d6dee-7875-449f-9761-c2f1780fcdf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mainBody</value>
      <webElementGuid>26dead05-59b4-413e-81a4-6a3f49946f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainBodyFrame</value>
      <webElementGuid>4129c793-f186-472d-80f6-d4308456862d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.util.QueryResponseServlet/1756978765763?bcKey=new&amp;action_name=assign_driver_to_shipment&amp;finder_set_gid=BXC.BXC_BUY_SHIPMENT_UPDATE&amp;management_action=go&amp;finder_set_gid=BXC.BXC_BUY_SHIPMENT_UPDATE&amp;pk=BXC.1006686</value>
      <webElementGuid>8ae40d0c-a3f3-4727-aaa2-db34b1f1a5ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainBodyFrame&quot;)</value>
      <webElementGuid>badb5698-830a-45f4-a21d-196151c28c02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainBodyFrame']</value>
      <webElementGuid>1cecc1c4-0a90-432d-b3d6-29d4477c4c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>931f6008-45ba-4e89-bb64-2f92d7517862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1756978765763?bcKey=new&amp;action_name=assign_driver_to_shipment&amp;finder_set_gid=BXC.BXC_BUY_SHIPMENT_UPDATE&amp;management_action=go&amp;finder_set_gid=BXC.BXC_BUY_SHIPMENT_UPDATE&amp;pk=BXC.1006686']</value>
      <webElementGuid>45a55d42-6fc2-47e8-aa74-36cd782473b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
