<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Indicator_order_releaseindicator</name>
   <tag></tag>
   <elementGuidId>0ce0ae86-a16b-49df-9750-5b81a7d31418</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;order_release/indicator&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='order_release/indicator']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Indicator&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>72f332dc-cd8e-4091-b8c2-740fc2884b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Indicator</value>
      <webElementGuid>759ce431-8b00-45d8-9979-37f241d2b5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>showimage(this.options[this.selectedIndex].value)</value>
      <webElementGuid>0873d163-78bb-40b1-bddb-3154cdc66eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_release/indicator</value>
      <webElementGuid>a6953bf4-9cfc-4dba-99f1-3ddad453e729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WhiteGreenYellowRedBlueOrange</value>
      <webElementGuid>946c6dda-81f3-43f5-af7a-ca204d07c933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyDataDiv&quot;)/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;bodySectInCont w100&quot;]/tbody[1]/tr[4]/td[1]/div[@class=&quot;fieldCont&quot;]/span[@class=&quot;queryCtlCont&quot;]/select[1]</value>
      <webElementGuid>da5c17ff-60e6-407b-af83-95c762bf126c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New1/Page_Order Releases Finder/iframe_PRAJYOT.DABHADEBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>a7785c23-3492-41bd-b74f-56c1c49618d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='order_release/indicator']</value>
      <webElementGuid>0b52448b-24e5-4df8-9e27-9c26a5cd1c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyDataDiv']/table/tbody/tr/td/table/tbody/tr[4]/td/div/span/select</value>
      <webElementGuid>d318c3d9-0575-4503-bb9a-13291a79f60a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indicator'])[1]/following::select[1]</value>
      <webElementGuid>095b4c43-e3ce-4203-84a3-92e905975b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Domain Name'])[1]/following::select[2]</value>
      <webElementGuid>8dfc6e39-b91d-4d52-995c-add3249a2612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Release Attribute'])[1]/preceding::select[1]</value>
      <webElementGuid>d6de0532-dd79-4b2b-8f21-c4233e81cc00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insert Time'])[1]/preceding::select[2]</value>
      <webElementGuid>5009d772-1ddd-4170-aef6-aa4936dc6833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div/span/select</value>
      <webElementGuid>bb17d815-581c-46c2-9e99-477f70afd284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'order_release/indicator' and (text() = 'WhiteGreenYellowRedBlueOrange' or . = 'WhiteGreenYellowRedBlueOrange')]</value>
      <webElementGuid>1505482a-aa78-4870-b58d-f4ef34db0821</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
