<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Attributes</name>
   <tag></tag>
   <elementGuidId>98344435-2c6c-4655-ad03-06e55dcbda61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Attributes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1f0c8bff-53f5-469e-a4a9-310723ef2985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>954ba6b9-155e-4a45-bfe7-6049ed3b8799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ffa9bc5e-b195-404a-919a-c76cb0e2f09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>e2cba11e-4060-43c2-9009-9ac745b14d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>9ef636a0-0c3a-4b9d-8e94-7d958c3cddfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9001792e-3549-48b9-8c58-ab85be69052f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript: if(checkData('management_main')) {document.forms['management_main'].action='/GC3/glog.webserver.rate.RateOfferingUpdateServlet/1747204735842?bcKey=MTc0NzIwNDcxNjgyMTox';document.forms['management_main'].redirect.value='/GC3/glog.webserver.rate.RateOfferingManagementServlet/1747204735842?bcKey=MTc0NzIwNDcxNjgyMTox&amp;rate_offering_stylesheet=rate/RateAttributes.xsl';document.forms['management_main'].submit();}</value>
      <webElementGuid>531244ca-e59b-455c-91a5-5e8a3c942dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attributes</value>
      <webElementGuid>dbef54cf-f447-4a90-bd56-572cb6299add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rate/RateAttributes.xsl&quot;)/div[@class=&quot;tabLabelCont tabDim&quot;]/span[1]/a[1]</value>
      <webElementGuid>b6b0caec-116e-4341-be16-8eba9c15704f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Rate Offering - Rate Header/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>f47df8e1-ea3c-4708-a5d2-e2b0818ccdf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='']</value>
      <webElementGuid>cc898889-400e-4911-a69c-49d48bb0159c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rate/RateAttributes.xsl']/div/span/a</value>
      <webElementGuid>a097b813-f38e-4215-8f92-fd015f35000e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Attributes')]</value>
      <webElementGuid>3275853d-5883-43cd-9652-c2e7f60b9a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate Header'])[1]/following::a[1]</value>
      <webElementGuid>3e24c523-7812-4458-abbb-d97b032274ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Profile'])[1]/following::a[3]</value>
      <webElementGuid>d0a66504-87ce-4816-ba01-df2e4ff7ecc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessorials'])[1]/preceding::a[1]</value>
      <webElementGuid>af368a95-3ba5-4048-a509-1824371be0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Services'])[1]/preceding::a[2]</value>
      <webElementGuid>36ecfa65-a16a-4c95-b9c2-ab8e443d6b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Attributes']/parent::*</value>
      <webElementGuid>c1432082-9c39-4d59-841f-165d7ccabe69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript: if(checkData('management_main')) {document.forms['management_main'].action='/GC3/glog.webserver.rate.RateOfferingUpdateServlet/1747204735842?bcKey=MTc0NzIwNDcxNjgyMTox';document.forms['management_main'].redirect.value='/GC3/glog.webserver.rate.RateOfferingManagementServlet/1747204735842?bcKey=MTc0NzIwNDcxNjgyMTox&amp;rate_offering_stylesheet=rate/RateAttributes.xsl';document.forms['management_main'].submit();}&quot;)]</value>
      <webElementGuid>9fe7fae2-e409-492b-becb-c2f32aa71ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>25b109d6-7766-4861-910f-71fc6434f388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript: if(checkData(&quot; , &quot;'&quot; , &quot;management_main&quot; , &quot;'&quot; , &quot;)) {document.forms[&quot; , &quot;'&quot; , &quot;management_main&quot; , &quot;'&quot; , &quot;].action=&quot; , &quot;'&quot; , &quot;/GC3/glog.webserver.rate.RateOfferingUpdateServlet/1747204735842?bcKey=MTc0NzIwNDcxNjgyMTox&quot; , &quot;'&quot; , &quot;;document.forms[&quot; , &quot;'&quot; , &quot;management_main&quot; , &quot;'&quot; , &quot;].redirect.value=&quot; , &quot;'&quot; , &quot;/GC3/glog.webserver.rate.RateOfferingManagementServlet/1747204735842?bcKey=MTc0NzIwNDcxNjgyMTox&amp;rate_offering_stylesheet=rate/RateAttributes.xsl&quot; , &quot;'&quot; , &quot;;document.forms[&quot; , &quot;'&quot; , &quot;management_main&quot; , &quot;'&quot; , &quot;].submit();}&quot;) and (text() = 'Attributes' or . = 'Attributes')]</value>
      <webElementGuid>67ffb076-5b0b-415a-8123-58bc7241ed50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
