<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Finished</name>
   <tag></tag>
   <elementGuidId>992bc32a-9771-43b9-ad21-4ff8fb1abfbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;finished_button&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='finished_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Finished&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c9643d8-8773-4f64-a75b-1492821e6cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2fdfd932-aa85-460f-9f9a-75c567206514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>finished_button</value>
      <webElementGuid>65de8a81-a9a5-4be9-a19c-e39bc9710dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enButton</value>
      <webElementGuid>07079ebd-e477-462a-a19f-de1e7a5a050b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>function t() { javascript:setLogProfile('dataQueryType', 'data', 'logProfile@ID'); return true; } if(t.call(this) !== false) { javascript:createFinishedURL('/GC3/glog.webserver.rate.RateOfferingSaveServlet/1747145548531?bcKey=MTc0NzE0NTQ0NDAxNjox'); } else { return false; }</value>
      <webElementGuid>aa358fa8-ea53-4394-bd29-7f947398d996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Finished</value>
      <webElementGuid>bf1e4dac-a71f-4d11-83f7-29670856ea23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;body1&quot;]/div[@class=&quot;bodyHeaderCont&quot;]/table[@class=&quot;hdLine&quot;]/tbody[1]/tr[1]/td[2]/table[@class=&quot;buttonsCont&quot;]/tbody[1]/tr[1]/td[3]/div[@class=&quot;buttonCont&quot;]/button[@class=&quot;enButton&quot;]</value>
      <webElementGuid>c503d618-14a4-4fbe-ae19-9e04a8c606b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Rate Offering - Rate Header/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>54276009-f50b-4fe6-9ef1-04a077eea0e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='finished_button']</value>
      <webElementGuid>69b5f4df-b8de-459d-8c91-b46b2e680b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[1]/following::button[1]</value>
      <webElementGuid>58e11d3e-9b91-4a74-84f2-9dea18414f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate Offering'])[2]/following::button[2]</value>
      <webElementGuid>9ab874f4-a812-46f2-95b8-ce873063d846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/preceding::button[1]</value>
      <webElementGuid>4642bfae-3508-43fc-ba38-ea9dd38864b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Profile'])[1]/preceding::button[2]</value>
      <webElementGuid>6b596b53-e960-4b7b-af38-46393d43f5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Finished']/parent::*</value>
      <webElementGuid>27f2de87-bbff-4b87-82f5-73665546a237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/button</value>
      <webElementGuid>496315e4-3ca1-40d0-9822-9df69d5821b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'finished_button' and (text() = 'Finished' or . = 'Finished')]</value>
      <webElementGuid>a924bfbe-e289-4a91-b584-05e6a9dcf13c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
