<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</name>
   <tag></tag>
   <elementGuidId>8241c025-7ae8-483d-b80b-c83a781644c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainIFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainIFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mainIFrame</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6aef4b0d-a4e8-4ed8-a1b6-1178f1f13849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainIFrame</value>
      <webElementGuid>96d033f6-a01c-4887-a7a1-ac032584f7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oj-web-applayout-content-nopad</value>
      <webElementGuid>8d1582dc-592d-4576-a129-26818c831a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>mainIFrameOnLoad()</value>
      <webElementGuid>379fb09e-bbd6-49da-b56f-ce9c257a6f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr : {src: IFRAME_URL}</value>
      <webElementGuid>90eb2f23-55e5-4c80-907f-919553c1e921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.finder.FinderServlet?bcKey=new&amp;query_name=glog.server.query.item.ItemQuery&amp;finder_set_gid=ITEM</value>
      <webElementGuid>30d0bf5c-9dfd-4c10-a62d-a5deee69a345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainIFrame&quot;)</value>
      <webElementGuid>91f816f3-3eed-4f29-82f1-ae50c003a85a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainIFrame']</value>
      <webElementGuid>7c6fae5c-cdd1-44f7-a2c9-e88d1a864fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//oj-module[@id='mainModule']/iframe</value>
      <webElementGuid>c2f4c120-d410-4d99-91b6-ef24999f5ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a7bfee1a-a520-4da8-9252-4cf1a1327048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'mainIFrame' and @src = '/GC3/glog.webserver.finder.FinderServlet?bcKey=new&amp;query_name=glog.server.query.item.ItemQuery&amp;finder_set_gid=ITEM']</value>
      <webElementGuid>fd269c93-2511-454b-b496-19f9bf5704f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
