<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BXC.CN_RAIL_CHGO_IL_SCH_WI_LUMBER_53FT_LC_25</name>
   <tag></tag>
   <elementGuidId>0fce7c2a-7f5d-4b51-be3e-689c1b92bb69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='rgSGSec.2.1.1.3.k']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;BXC.CN_RAIL_CHGO_IL_SCH_WI_LUMBER_53FT_LC_25&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4860d32c-47b3-4785-ab1e-b2a8a3160a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rgSGSec.2.1.1.3.k</value>
      <webElementGuid>28fb759b-768d-4d6f-9e64-2ba5639f55c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>78b6881a-b7ae-4221-ad0a-77c38875b4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>81e436b9-86c6-4e96-b338-fbce040df273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OpenTarget('/GC3/glog.webserver.rate.RateGeoManagementServlet?bcKey=MTc0NzIwNjE1OTcwNjox&amp;pk=BXC.CN_RAIL_CHGO_IL_SCH_WI_LUMBER_53FT_LC_25&amp;finder_set_gid=RATE_GEO&amp;management_action=edit'); return addToRecentlyViewed(finderSetGid,'BXC.CN_RAIL_CHGO_IL_SCH_WI_LUMBER_53FT_LC_25', 'EDIT');</value>
      <webElementGuid>1f275158-299e-453b-90fc-3d91e1820247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BXC.CN_RAIL_CHGO_IL_SCH_WI_LUMBER_53FT_LC_25</value>
      <webElementGuid>e46ee532-ddfc-426a-ba13-56773d14c63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rgSGSec.2.1.1.3.k&quot;)</value>
      <webElementGuid>27da873a-3c6a-4276-b4f3-9a6bdb830e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Rate Records Result/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>7f558e4e-e92a-42ad-a004-b6a8d9ec9411</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='rgSGSec.2.1.1.3.k']</value>
      <webElementGuid>3a96488f-a06f-490d-9119-f553b29c1892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rgSGSec.2.1.1.3']/a</value>
      <webElementGuid>92747042-1a68-417e-a1fd-897b028d22ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BXC.CN_RAIL_CHGO_IL_SCH_WI_LUMBER_53FT_LC_25')]</value>
      <webElementGuid>4d76cdb0-0890-4781-9239-921d7554e4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Domain Name'])[1]/following::a[2]</value>
      <webElementGuid>9f9effa1-f2c2-4316-b7dc-9aede790bdb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::a[2]</value>
      <webElementGuid>3c23aed5-6d9c-48f8-8a6c-8c85cdcd9396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BXC.CN_RAIL_CHGO_IL_SCH_WI_LUMBER_73FT_FBC_25'])[1]/preceding::a[2]</value>
      <webElementGuid>1cf9fe2c-9ac4-4194-9931-3f04ab8f59e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BXC.CN_RAIL_CHGO_IL_SCH_WI_PLYWOOD_61FT_LC_25'])[1]/preceding::a[4]</value>
      <webElementGuid>c22d7cd8-c639-446d-838d-90b65e191931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BXC.CN_RAIL_CHGO_IL_SCH_WI_LUMBER_53FT_LC_25']/parent::*</value>
      <webElementGuid>17c89c1a-1ae0-4b8d-87f8-3fad1f4f8794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[3]</value>
      <webElementGuid>59d0425e-8b29-409a-9398-fb74d0aa1dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>47864b9a-3d96-43eb-96b2-92f99099c448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'rgSGSec.2.1.1.3.k' and @href = 'javascript:void(0);' and (text() = 'BXC.CN_RAIL_CHGO_IL_SCH_WI_LUMBER_53FT_LC_25' or . = 'BXC.CN_RAIL_CHGO_IL_SCH_WI_LUMBER_53FT_LC_25')]</value>
      <webElementGuid>f0e183e2-a03d-4b71-a59b-a49032a8afe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
