<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>978cb043-0423-46aa-96bf-2619f0d8633a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pt1:_FOr1:1:_FONSr2:0:_FOTsr1:0:pt1:DSRes1:0:AP1:q1::search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Search&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>72d4062c-baf5-44e8-91b3-a81e18016b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_FOr1:1:_FONSr2:0:_FOTsr1:0:pt1:DSRes1:0:AP1:q1::search</value>
      <webElementGuid>d88a6707-fb7f-4840-b90d-e98772112c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xhv p_AFTextOnly</value>
      <webElementGuid>dfa7350d-2016-4602-9c43-df9ec40e46a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.focus();return false;</value>
      <webElementGuid>6fca7e3e-5967-4e6b-8aad-9d482346303b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>b013d54e-1f20-4071-ad9e-124289868630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_FOr1:1:_FONSr2:0:_FOTsr1:0:pt1:DSRes1:0:AP1:q1::search&quot;)</value>
      <webElementGuid>2fa7e331-266f-4278-85ad-05de6dfe1a4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pt1:_FOr1:1:_FONSr2:0:_FOTsr1:0:pt1:DSRes1:0:AP1:q1::search']</value>
      <webElementGuid>08135f69-d4c8-4602-b6b0-02664fe2c523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pt1:_FOr1:1:_FONSr2:0:_FOTsr1:0:pt1:DSRes1:0:AP1:q1']/div[2]/div/table/tbody/tr/td/table/tbody/tr/td[3]/button</value>
      <webElementGuid>1481a968-fd9f-42a0-92d3-5bb62a1b76bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creation Date'])[2]/following::button[1]</value>
      <webElementGuid>57766ffc-fe64-4f2b-9341-70d53a0b924b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Press down arrow to access Calendar'])[1]/following::button[1]</value>
      <webElementGuid>27745e8f-437e-4234-a2a4-e5d8ffa10173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/preceding::button[1]</value>
      <webElementGuid>27aba0c1-9a64-4e7f-a8d1-3f11257271e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save...'])[1]/preceding::button[2]</value>
      <webElementGuid>f962bd64-f5d8-4f8b-9e51-46f97ee37e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/button</value>
      <webElementGuid>c3620117-a675-4900-9366-1561b9e89cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pt1:_FOr1:1:_FONSr2:0:_FOTsr1:0:pt1:DSRes1:0:AP1:q1::search' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>211c2dbc-aeff-4511-8b3a-ba25460641ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
