<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OKOK</name>
   <tag></tag>
   <elementGuidId>94790bc7-75a9-4717-8caf-41c3f5439f01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAt2:0:AP1:TPIF1:1:TPItemXrefResults1:saveACBtn1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;OKOK&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>781ef5e3-e67f-47c8-a64e-5ac619142d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAt2:0:AP1:TPIF1:1:TPItemXrefResults1:saveACBtn1</value>
      <webElementGuid>d501ea8c-c8ae-44b6-b881-dd18489f0410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>7abd9b7d-39c2-4053-804a-f70a1175f0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p_AFHoverTarget xeq p_AFTextOnly</value>
      <webElementGuid>46c4fbc9-cd3d-4c65-b844-b1182416fd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_afrgrp</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2cba3edc-9682-48d0-8fe9-c2c8fe25138a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>4c4b3034-5681-4206-8084-e04419e4b2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OKOK</value>
      <webElementGuid>933b1117-a7b5-4540-bf47-58fcc6de6a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAt2:0:AP1:TPIF1:1:TPItemXrefResults1:saveACBtn1&quot;)</value>
      <webElementGuid>f56158b4-0feb-4c43-9b4b-159d0b480d8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAt2:0:AP1:TPIF1:1:TPItemXrefResults1:saveACBtn1']</value>
      <webElementGuid>aeea9c03-66b8-4fd1-8d4b-0195c3eb6474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAt2:0:AP1:TPIF1:1:TPItemXrefResults1:panelGroupLayout2']/tbody/tr/td[2]/div</value>
      <webElementGuid>9122029f-c812-4bd9-80fc-fc1c4c25b536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Context'])[1]/following::div[2]</value>
      <webElementGuid>1e9aabca-bf0b-4fab-9c70-69415a54fb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::div[2]</value>
      <webElementGuid>229bfffa-9145-494f-b3a3-8ca3a1bfcebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/table/tbody/tr/td[2]/div</value>
      <webElementGuid>8b33c657-9b8d-4fb5-ba83-34a1e11eb01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '_FOpt1:_FOr1:0:_FONSr2:0:MAt2:0:AP1:TPIF1:1:TPItemXrefResults1:saveACBtn1' and @title = 'OK' and (text() = 'OKOK' or . = 'OKOK')]</value>
      <webElementGuid>3af83eed-a06e-433b-b6f5-cb6ae6732675</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
