<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AOBRANCH_CODEBUYER_NUMBERCANCEL_DATE_e95d8c</name>
   <tag></tag>
   <elementGuidId>9441a8a2-07f4-40f9-a69f-5d10046c7b68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='order_release/order_release_refnum_qual_xid@ID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;order_release/order_release_refnum_qual_xid@ID&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Order Release Reference Number Qualifier&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>30a41c7e-917f-48e2-a061-f30ef76a5535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_release/order_release_refnum_qual_xid@ID</value>
      <webElementGuid>30b56c4d-9a84-4e03-afbd-1902d9671736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Order Release Reference Number Qualifier</value>
      <webElementGuid>0ae64dd3-8708-465b-850d-d64c840c720d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>onChangeMultiDrop('search','display_order_release/order_release_refnum_qual_xid', this.options);</value>
      <webElementGuid>4d278570-6e9f-4a8e-b2d0-f9dbede6a76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a233920f-f732-4464-9acb-8c3e4f681fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5a84f7f3-5994-4a1b-b089-b6573a34be47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AOBRANCH_CODEBUYER_NUMBERCANCEL_DATECGCOCRCUST_PODISPATCH_NUMBERDIVISIONDOEXTERNAL_CUSTOMER_IDGLOGGROSS_MARGIN_AMTGROSS_MARGIN_PCTIB_GL_CODEINTG_TYPEKEWILL_EXPORT_REASONLC2_ORIGIN_ORDER_IDLC2_SCENARIO_IDLINE_OF_BUSINESSOB_GL_CODEOP_UNITOP_UNIT_NAMEPALLET_COUNTPICKUP_NUMBERPOPO_NUMRAILCAR_IDRAIL_CONTRACT_NUMBERRAIL_GATEWAYRAIL_ROUTE_CODERELATED_ORDER_COMPANYRELATED_ORDER_LINERELATED_ORDER_NUMBERRELATED_ORDER_TYPEREVISIONREVNUMROUTE_IDRO_NUMSHIP_VIASISO_NUMSO_NUMSPLIT FROM ORDERSTTO_NUMUPDATE_REASON_CODE</value>
      <webElementGuid>d0a76495-3100-471f-87d5-7b613742831b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyDataDiv&quot;)/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;bodySectInCont w100&quot;]/tbody[1]/tr[3]/td[1]/div[@class=&quot;fieldCont&quot;]/div[2]/select[1]</value>
      <webElementGuid>a93aac79-98dd-4ba8-898a-cc9c715874fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Samsara/Page_Order Release Finder/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>569ce51d-5f43-4709-be44-5057798679cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='order_release/order_release_refnum_qual_xid@ID']</value>
      <webElementGuid>4465fc5a-0d9b-4cad-ac99-3ead4ec9e1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyDataDiv']/table/tbody/tr/td/table/tbody/tr[3]/td/div/div[2]/select</value>
      <webElementGuid>38d50d5a-8cc7-492d-a871-bec6a2f7dbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Release Reference Number Qualifier'])[1]/following::select[1]</value>
      <webElementGuid>cb453976-4fc2-40d3-b1b8-da4a6d6bc05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Release Reference Number'])[1]/following::select[2]</value>
      <webElementGuid>0cc4a666-5073-4e0a-b453-4497279876dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indicator'])[1]/preceding::select[1]</value>
      <webElementGuid>7a1a7a18-bea3-4be9-82b2-ffa362508ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Release Attribute'])[1]/preceding::select[2]</value>
      <webElementGuid>c4da4c14-8717-4cb4-9b34-ee05836b0410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>c1c9921a-e263-4755-aab2-a9a0df4adbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'order_release/order_release_refnum_qual_xid@ID' and (text() = 'AOBRANCH_CODEBUYER_NUMBERCANCEL_DATECGCOCRCUST_PODISPATCH_NUMBERDIVISIONDOEXTERNAL_CUSTOMER_IDGLOGGROSS_MARGIN_AMTGROSS_MARGIN_PCTIB_GL_CODEINTG_TYPEKEWILL_EXPORT_REASONLC2_ORIGIN_ORDER_IDLC2_SCENARIO_IDLINE_OF_BUSINESSOB_GL_CODEOP_UNITOP_UNIT_NAMEPALLET_COUNTPICKUP_NUMBERPOPO_NUMRAILCAR_IDRAIL_CONTRACT_NUMBERRAIL_GATEWAYRAIL_ROUTE_CODERELATED_ORDER_COMPANYRELATED_ORDER_LINERELATED_ORDER_NUMBERRELATED_ORDER_TYPEREVISIONREVNUMROUTE_IDRO_NUMSHIP_VIASISO_NUMSO_NUMSPLIT FROM ORDERSTTO_NUMUPDATE_REASON_CODE' or . = 'AOBRANCH_CODEBUYER_NUMBERCANCEL_DATECGCOCRCUST_PODISPATCH_NUMBERDIVISIONDOEXTERNAL_CUSTOMER_IDGLOGGROSS_MARGIN_AMTGROSS_MARGIN_PCTIB_GL_CODEINTG_TYPEKEWILL_EXPORT_REASONLC2_ORIGIN_ORDER_IDLC2_SCENARIO_IDLINE_OF_BUSINESSOB_GL_CODEOP_UNITOP_UNIT_NAMEPALLET_COUNTPICKUP_NUMBERPOPO_NUMRAILCAR_IDRAIL_CONTRACT_NUMBERRAIL_GATEWAYRAIL_ROUTE_CODERELATED_ORDER_COMPANYRELATED_ORDER_LINERELATED_ORDER_NUMBERRELATED_ORDER_TYPEREVISIONREVNUMROUTE_IDRO_NUMSHIP_VIASISO_NUMSO_NUMSPLIT FROM ORDERSTTO_NUMUPDATE_REASON_CODE')]</value>
      <webElementGuid>61ae2b6c-21c6-4ed2-b8b2-e44c2c0a6f00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
