<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</name>
   <tag></tag>
   <elementGuidId>773a8179-7a9c-4552-8d39-f5053ab8398b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mainIFrame&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainIFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mainIFrame</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2376d5c9-1524-4c57-b64b-881e93238e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainIFrame</value>
      <webElementGuid>e185975e-9ca0-4e1c-9b22-d67ee5b0bfea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oj-web-applayout-content-nopad</value>
      <webElementGuid>0ac9293c-9018-4a24-aab3-cc4af81b3770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>mainIFrameOnLoad()</value>
      <webElementGuid>f50bcb9f-ce09-43c0-ae4b-12af74759d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr : {src: IFRAME_URL}</value>
      <webElementGuid>31d76289-675c-4183-86a2-523f7f22404b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.finder.FinderServlet?bcKey=new&amp;query_name=glog.server.query.driver.DriverQuery&amp;finder_set_gid=BXC.DRIVER_UPDATE</value>
      <webElementGuid>ed0f6718-ab25-4d56-ba2f-69fd626a822f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainIFrame&quot;)</value>
      <webElementGuid>7e8e3946-72ef-4df5-954b-50962252d7a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainIFrame']</value>
      <webElementGuid>d1d0e091-1dbc-4122-b5a5-ac2080172f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//oj-module[@id='mainModule']/iframe</value>
      <webElementGuid>fec29a25-576f-4c0c-9fac-a8bd92ba568b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6a2d519a-f58c-4f51-a0eb-e6eca696242d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'mainIFrame' and @src = '/GC3/glog.webserver.finder.FinderServlet?bcKey=new&amp;query_name=glog.server.query.driver.DriverQuery&amp;finder_set_gid=BXC.DRIVER_UPDATE']</value>
      <webElementGuid>28e9dca9-804f-4a89-9720-dfac1e31892a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
