<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rates</name>
   <tag></tag>
   <elementGuidId>18562297-07a4-448d-b53d-409d9db9f80f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='sb_25_0']/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.oj-treeview-item-content.oj-hover.oj-focus > span.oj-treeview-item-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Rates&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6467922b-1ea2-4970-a842-503fd089840d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oj-treeview-item-text</value>
      <webElementGuid>353f2dac-e3ee-4738-bfae-992781cfc38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:title</name>
      <type>Main</type>
      <value>[[row.data.text]]</value>
      <webElementGuid>7e65c15c-f55c-4edf-8584-d35ffdf208a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:style</name>
      <type>Main</type>
      <value>[[{'color':theme_springboard_submenu_fontcolor}]]</value>
      <webElementGuid>8ca80954-c181-4834-bc5e-b44f446122e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rates</value>
      <webElementGuid>aefed6cd-cbcb-4dfe-bd15-84de0fb52e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                      Rates
                    </value>
      <webElementGuid>a04e7581-c622-4410-bb20-b25d87d4c46d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sb_25_0&quot;)/div[@class=&quot;oj-treeview-item-content oj-hover oj-focus&quot;]/span[@class=&quot;oj-treeview-item-text&quot;]</value>
      <webElementGuid>abe19305-9802-4da8-bcc8-a387ba9b1a6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='sb_25_0']/div/span[2]</value>
      <webElementGuid>77f73975-108c-4d98-b332-297e53d474e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open in New Window'])[30]/following::span[2]</value>
      <webElementGuid>4d51c84c-f520-400a-8774-73612a2db209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[29]/div/oj-tree-view/ul/li/div/span[2]</value>
      <webElementGuid>a3b60973-1621-4dd1-b8eb-cd2df18be61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Rates' and (text() = '
                      Rates
                    ' or . = '
                      Rates
                    ')]</value>
      <webElementGuid>9d6b9ddb-543f-4ffb-9706-eb1ab588723c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='sb_26_0']/div/span[2]</value>
      <webElementGuid>6a5c51d9-1293-476d-bbb2-ecbb7a7894a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open in New Window'])[31]/following::span[2]</value>
      <webElementGuid>f95ae26d-1b71-43f2-8e83-5393af830a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[30]/div/oj-tree-view/ul/li/div/span[2]</value>
      <webElementGuid>79c399a6-7f9a-4ca0-aa17-2786e9f0415e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
