<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_mainBody</name>
   <tag></tag>
   <elementGuidId>540eda2f-cccf-4a94-9414-86cf14f24528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainBodyFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainBodyFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;mainBody&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>22fbd75a-fbc7-474e-a4d0-bba5b4c2dfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframeBody</value>
      <webElementGuid>104e29d7-0f14-483f-8c6f-60f346483885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>6d5129ff-20f6-4ca8-83c1-0cba233810cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mainBody</value>
      <webElementGuid>4a783b8a-3ddd-46f4-97f7-bf2dfd1bad17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainBodyFrame</value>
      <webElementGuid>ae65a1f9-0303-4bc6-af45-331d28ace709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/GC3/glog.webserver.util.QueryResponseServlet/1758214085618?bcKey=new&amp;action_name=change_order_release_times&amp;finder_set_gid=BXC.ORDER%20RELEASE_UPDATE&amp;management_action=go&amp;finder_set_gid=BXC.ORDER%20RELEASE_UPDATE&amp;pk=BXC.SO_17558076_20250812_07-01-2025_TPA_V1H&amp;pk=BXC.SO_17564908_20250812_07-01-2025_TPA_V1H&amp;pk=BXC.SO_17545212_20250812_07-01-2025_TPA_V1H</value>
      <webElementGuid>20cba44a-d392-43de-b8a5-688fa639f79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainBodyFrame&quot;)</value>
      <webElementGuid>34ebd51f-97d1-4f9f-90da-db8f6e7e2c64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainBodyFrame']</value>
      <webElementGuid>390654ce-3ac7-42c9-91f9-d23f57e69f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>c75e3655-6c18-4f46-978a-4a61560c5a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'mainBody' and @id = 'mainBodyFrame' and @src = '/GC3/glog.webserver.util.QueryResponseServlet/1758214085618?bcKey=new&amp;action_name=change_order_release_times&amp;finder_set_gid=BXC.ORDER%20RELEASE_UPDATE&amp;management_action=go&amp;finder_set_gid=BXC.ORDER%20RELEASE_UPDATE&amp;pk=BXC.SO_17558076_20250812_07-01-2025_TPA_V1H&amp;pk=BXC.SO_17564908_20250812_07-01-2025_TPA_V1H&amp;pk=BXC.SO_17545212_20250812_07-01-2025_TPA_V1H']</value>
      <webElementGuid>ded45309-dc57-48e6-a8b2-3ec83c45c781</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
