<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Actions_finderActionButtonImg</name>
   <tag></tag>
   <elementGuidId>e64e80c5-2a45-4d96-9856-0b3adf6cbbad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;javascript:return loadFinderActionFrameAndAddCssClassToFinder(queryName, finderSetGid, this,'finderButtonOnClick', event);&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.finderActionButtonImg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Actions&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c22508b9-cd47-4e87-b585-81a3d2567269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>404c4606-9e3b-4d15-94a7-14aca40a3e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>finderActionButtonImg</value>
      <webElementGuid>16b9cf16-376d-4efa-a89d-10216c6c56a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>493e26ce-f882-436c-9d1b-eceed545c393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:return loadFinderActionFrameAndAddCssClassToFinder(queryName, finderSetGid, this,'finderButtonOnClick', event);</value>
      <webElementGuid>ceb26bcb-bf31-4f55-9135-fcd922573c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frToolbar&quot;)/tbody[1]/tr[1]/td[1]/div[@class=&quot;finderButton sgCaptionCol&quot;]/a[@class=&quot;finderActionButtonImg&quot;]</value>
      <webElementGuid>3dbf289a-bb5e-4239-9f4a-038b00cf8449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Bulk Creation/Page_Order Release Result/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>47d06e15-3d78-458a-912d-592ce420337a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;javascript:return loadFinderActionFrameAndAddCssClassToFinder(queryName, finderSetGid, this,'finderButtonOnClick', event);&quot;]</value>
      <webElementGuid>516cc950-da78-4bad-960e-ec12532b5464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='frToolbar']/tbody/tr/td/div/a</value>
      <webElementGuid>4e0cbb34-c56e-4ac2-b70e-8f2e2c0e7196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/following::a[1]</value>
      <webElementGuid>9c658303-a0dc-493f-b49d-644d60e57dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::a[1]</value>
      <webElementGuid>be7cc1bf-f779-4cd2-9232-159287db999b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>f7c986a8-3f29-498b-94c8-7e5b27079f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/div/a</value>
      <webElementGuid>bd9d1a56-9925-44b3-a2c0-4528b6b425ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);']</value>
      <webElementGuid>9b9e2309-e72f-43b6-87af-1837dffd3b09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
