<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Actions</name>
   <tag></tag>
   <elementGuidId>e16e8958-03e4-47d0-a668-5d4dcc3323da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.enButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Actions&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>990c6be6-d104-46d6-8799-8c2708eded53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>05de5364-26fd-4fa6-b4b0-186db0a52326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enButton</value>
      <webElementGuid>4b54c30f-71f2-4dd4-b1f1-ec2b624e1a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>function t() { javascript:return loadFinderActionFrameAndAddCssClassToFinder(queryName, finderSetGid, this,'finderButtonOnClick', event); return true; } if(t.call(this) !== false) { javascript:void(0); } else { return false; }</value>
      <webElementGuid>58d0a5a9-fdd5-4116-b93e-6c78de28ed22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ecd4dadd-c60b-4ff6-87bb-dd2dae28dc43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b8d064ba-0439-4c0e-8fb8-800739006968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actions</value>
      <webElementGuid>e6fe8a84-c013-49e2-a3ea-3a9787c27982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frToolbar&quot;)/tbody[1]/tr[1]/td[1]/div[@class=&quot;finderButton sgCaptionCol&quot;]/div[@class=&quot;buttonCont&quot;]/button[@class=&quot;enButton&quot;]</value>
      <webElementGuid>510dadb4-be26-4032-8f53-b6139e4ed75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Bulk Creation/Page_Order Release Result/iframe_GAURAV.PRASADBLUELINXCO.COM_mainIFrame</value>
      <webElementGuid>58e0a98f-04b8-4e12-911e-ab9081c71e88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='']</value>
      <webElementGuid>4e20f613-abd3-4d5a-a033-5bd3b0ebc7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='frToolbar']/tbody/tr/td/div/div/button</value>
      <webElementGuid>c542f81e-75a4-48f9-ba5e-c3407af180ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::button[1]</value>
      <webElementGuid>cef570b4-5fe9-4a59-a096-e6273567ac99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contains'])[1]/following::button[2]</value>
      <webElementGuid>0b4b3dc3-f27e-46a0-a015-8175a50e1e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Actions']/parent::*</value>
      <webElementGuid>4bb01591-106a-4cb5-ab7f-24e232457491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>890ea2a7-6720-437e-9dcc-40bf9144df03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Actions' or . = 'Actions')]</value>
      <webElementGuid>873873ad-d280-492b-9279-4df306ba3f78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
